### ISSUE TITLE
Create a new GitHub org and give scrooloose much kudos

### ISSUE THREAD

**Issue by docwhat** [vim-syntastic/syntastic#1905]
Based on a [comment by @scrooloose](https://github.com/scrooloose/syntastic/issues/699#issuecomment-255338765jk), he would be amiable to moving Syntastic to its own org, possibly splitting out the checkers.

I think this is a great idea and I created this issue to move the conversation out of #699.

In addition I think @scrooloose deserves a lot of kudos for his work on Syntastic over the years.  If there is a buy-a-beer-for-scrooloose fund someplace, I'd happily contribute!

**Comment by docwhat** [comment]
I also volunteer to do Ops & Cleaning if @lcd047 wants me:

* Cleaning up issues (removing "me toos", (pre-)formatting text).
* Helping out with CI, etc.
* Misc.

**Comment by scrooloose** [comment]
Done :)
