### ISSUE TITLE
Syntastic naviagation without the quickfix

### ISSUE THREAD

**Issue by sfahlberg** [vim-syntastic/syntastic#1907]
Hi there, is there a way to navigate around to the next error without having the quickfix window open? I feel like the quickfix takes up a lot of necessary screen real estate and I want to use `:lnext` to go to the next error but am having difficulties doing that if the quickfix is disabled. Is there any possibility of adding functionality to go from one error to the next without the quickfix? Thanks!

**Comment by lcd047** [comment]
This should do what you want:
```vim
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
```

**Comment by sfahlberg** [comment]
awesome! that's exactly what I was looking for!
