### ISSUE TITLE
 Syntastic.vim  detection failed

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [vim-syntastic/syntastic#1910]
system:Ubuntu14.04
The kernel version：4.2.0-27-generic

When I open a document, Syntastic.vim syntax error.I have determined that the file already exists on the system.

Look at the following error：
![image](https://cloud.githubusercontent.com/assets/14014477/20235685/8b39522a-a8d3-11e6-946f-aafd9ca36ba5.png)

**Comment by lcd047** [comment]
Contrary to the popular belief, syntastic is not supposed to detect your project's configuration.  It's up to you to configure it in a way that makes sense.  Since you seem to be working on a Linux module, please see #1383.

On a side note: next time please avoid posting screenshots.

**Comment by aixiaoxiaoyu** [comment]
When I tried to configure  syntastic_c_config_file, I did not find the .syntastic_c.conf file. Where is .syntastic_c.conf file  stored in general?(ubuntu 14.04)

**Comment by lcd047** [comment]
> When I tried to configure syntastic_c_config_file, I did not find the .syntastic_c.conf file.

1. The name of the file is set by the `g:syntastic_c_config_file` variable (cf. `:h 'g:syntastic_c_config_file')
2. Syntastic doesn't create the file, you have to create it yourself if you need it
3. Normally you'd put that file in the base directory of your project (cf. `:h syntastic-config-location`).
