### ISSUE TITLE
Syntastic suddenly got very slow

### ISSUE THREAD

**Issue by tandrewnichols** [vim-syntastic/syntastic#1913]
This bug(?) has a back story. I use syntastic on my Macbook (I have vim 8). I had to take my Macbook in for service and was using an old Linux laptop for development in the meantime and added a couple new plugins to vim (YouCompleteMe and Supertab). When I got my Mac back, I installed the new plugins and started working. I've noticed that some actions take considerably longer than they use to. For instance, I just had 13 different files with changes open, and did `:wq`. It took quite a while for all the files to save and for vim to close. Long enough that I decided to profile it. Here's the profile result:

<img width="587" alt="screen shot 1" src="https://cloud.githubusercontent.com/assets/2755760/20374737/97380cba-ac48-11e6-9742-d341e1cc802e.png">

As you can see, the top like 7 or 8 functions for total time are all in syntastic (coming in at around 8 seconds collectively).

The obvious thing to say here is that the new plugins are maybe not playing nicely with syntastic, but in my testing, that does't seem to be the case. If I disable YouCompleteMe and Supertab, saving those 13 files takes just as long as. If I disable syntastic, saving goes back to what I was used to before. Was there a recent change that would account for this suddenly much slower performance?

Tested on both Syntastic 3.7 and 3.8.

**Comment by tandrewnichols** [comment]
Well . . . I just realized that these files were coffeescript and I don't even have a coffeescript checker activated because I use vim-coffeescript which has it's own coffeelint integration (although . . . it doesn't seem to be auto activated on save so . . . ?). If I disable that plugin, everything seems to go back to normal as well. Is it possible they are somehow impeding one another in some way?

**Comment by tandrewnichols** [comment]
Coffeelint must be enabled by default?

<img width="369" alt="screen shot 2" src="https://cloud.githubusercontent.com/assets/2755760/20375315/83f005fa-ac4c-11e6-953a-d2095c38b0ed.png">

(Sorry to spam your inbox tonight . . . I'm just still investigating.)

**Comment by tandrewnichols** [comment]
Additionally, `let syntastic_coffee_checkers = []` speeds things up. Maybe coffeelint is just really slow.

**Comment by lcd047** [comment]
From the "Quick start" section in the manual, first paragraph:

> Syntastic comes preconfigured with a default list of enabled checkers per `filetype`. This list is kept reasonably short to prevent slowing down Vim or trying to use conflicting checkers.

Apparently said list is not short enough for `coffee`.  Well, syntastic is not the kind of plugin that you can afford to install and then forget about it.

Also, automatic checking is not really suitable for everyday use.  See `:h 'syntastic_mode_map'` and `:h :SyntasticToggleMode`.
