### ISSUE TITLE
Syntactic fails while processing scripts

### ISSUE THREAD

**Issue by decibel** [vim-syntastic/syntastic#1914]
I'm getting the following error while editing 4 files (Makefile, test.sh, lib.sh, setup.sh) at https://github.com/decibel/pgxntool-test/tree/a1198a32128f072a6f3a2813907069440d29a08d

These failures aren't completely deterministic... when I first open the 4 files everything is fine, but at some point I start getting these errors. Once I get the errors they seem pretty consistent.

I suspect the problem is that the Makefile will build a file (`.env`) that the others depend on, but that's just a guess, and presence or absence of that file doesn't seem to matter.

````
Error detected while processing function <SNR>35_BufWritePostHook[3]..<SNR>35_UpdateErrors[15]..<SNR>35_CacheErrors[35]..15[1]..14[23]..SyntaxCheckers_sh_sh_GetLocList[15]..SyntasticMake[29]..syntastic#util#system:
line    9:
E484: Can't open file /var/folders/mg/s6jx45m50zd32sy8mt60lk_00000gq/T/vakWpKz/16
Error detected while processing function <SNR>35_BufWritePostHook[3]..<SNR>35_UpdateErrors[15]..<SNR>35_CacheErrors:
line   35:
E170: Missing :endfor
Error detected while processing function <SNR>35_BufWritePostHook[3]..<SNR>35_UpdateErrors:
line   15:
E171: Missing :endif
````

**Comment by lcd047** [comment]
You probably have an `autocmd` or a plugin that messes the settings related to `shell`.

Please upgrade to the current master HEAD, then do whatever you're doing to trigger the problem, open a shell script, set `g:syntastic_debug` to 1, run `:SyntasticInfo`, and port the output.

**Comment by decibel** [comment]
`:SyntasticInfo`:
```
Syntastic version: 3.7.0-29 (Vim 800, Darwin)
Info for filetype: sh
Global mode: active
Filetype sh is active
The current file will be checked automatically
Available checker: sh
Currently enabled checker: sh
```

`:SyntasticCheck`:
```
syntastic: 351.735046: &shell = '/opt/local/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
syntastic: 351.735390: UpdateErrors: default checkers
syntastic: 351.735604: CacheErrors: default checkers
syntastic: 351.736424: g:syntastic_aggregate_errors = 0
syntastic: 351.736585: getcwd() = '/Users/decibel/git/pgxntool-test/tests'
syntastic: 351.736879: CacheErrors: Invoking checker: sh/sh
syntastic: 351.737506: SyntasticMake: called with options: {'errorformat': '%f: line %l: %m', 'makeprg': 'bash -n doc'}
Error detected while processing function SyntasticCheck[1]..<SNR>35_UpdateErrors[15]..<SNR>35_CacheErrors[35]..15[1]..14[23]..SyntaxCheckers_sh_sh_GetLocList[15]..SyntasticMake[29]..syntastic#util#system:
line    9:
E484: Can't open file /var/folders/mg/s6jx45m50zd32sy8mt60lk_00000gq/T/vyuWa5F/13
Error detected while processing function SyntasticCheck[1]..<SNR>35_UpdateErrors[15]..<SNR>35_CacheErrors:
line   35:
E170: Missing :endfor
Error detected while processing function SyntasticCheck[1]..<SNR>35_UpdateErrors:
line   15:
E171: Missing :endif
Press ENTER or type command to continue
```

The problem is likely that there are environment variables the script is looking at that might point to a location that doesn't exist.

**Comment by lcd047** [comment]
> `Syntastic version: 3.7.0-29 (Vim 800, Darwin)`

Please upgrade to the current master HEAD and try again.

**Comment by decibel** [comment]
Syntastic version: 3.7.0-29 (Vim 800, Darwin)
Info for filetype: sh
Global mode: active
Filetype sh is active
The current file will be checked automatically
Available checker: sh
Currently enabled checker: sh


> syntastic: 75.571647: &shell = '/opt/local/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''
> syntastic: 75.572026: UpdateErrors: default checkers
> syntastic: 75.572248: CacheErrors: default checkers
> syntastic: 75.572787: g:syntastic_aggregate_errors = 0
> syntastic: 75.572957: getcwd() = '/Users/decibel/git/pgxntool-test/tests'
> syntastic: 75.573262: CacheErrors: Invoking checker: sh/sh
> syntastic: 75.573946: SyntasticMake: called with options: {'errorformat': '%f: line %l: %m', 'makeprg': 'bash -n doc'}
> Error detected while processing function SyntasticCheck[1]..<SNR>35_UpdateErrors[15]..<SNR>35_CacheErrors[35]..15[1]..14[23]..SyntaxCheckers_sh_sh_GetLocList[15]..SyntasticMake[29]..syntastic#util#system:
> line    9:
> E484: Can't open file /var/folders/mg/s6jx45m50zd32sy8mt60lk_00000gq/T/vBddfUs/11
> Error detected while processing function SyntasticCheck[1]..<SNR>35_UpdateErrors[15]..<SNR>35_CacheErrors:
> line   35:
> E170: Missing :endfor
> Error detected while processing function SyntasticCheck[1]..<SNR>35_UpdateErrors:
> line   15:
> E171: Missing :endif

**Comment by lcd047** [comment]
Please follow the directions I posted above:

* trigger the bug
* open a shell script
* set `g:syntastic_debug  to 1`
* run `:SyntasticInfo`
* post the output.

**Comment by decibel** [comment]
I'm not following... the bug only triggers when I'm editing a shell script. Do you want me to open a different shell script?

**Comment by lcd047** [comment]
> Do you want me to open a different shell script?

No.  But I have no idea how you get to trigger the bug, and I'm trying to convince you to post useful logs of the actual problem.

> BTW,  `:set` didn't like `g:syntastic_debug`, so I've been using `:let`.

I never said you should use `:set`.  `:set` is used for setting builtin Vim options.  Setting Vim variables is done with `:let`.  The `g:` prefix is a hint that `syntastic_debug` is actually a variable, not a Vim option.

**Comment by decibel** [comment]
> No. But I have no idea how you get to trigger the bug, and I'm trying to convince you to post useful logs of the actual problem.

The process I've been using is this:

Run make. That creates a `.env` file that these scripts source.

----
gvim <shell script>
:let g:syntastic_debug=1
:SyntasticCheck
----

That works fine.

Run make again. That will create a *new* `.env` file, as well as removing a temporary directory that was referenced by the *old* `.env` file.

If I then do `:SyntasticCheck` I'll get an error, which I've pasted above, as well as the requested output of `:SyntasticInfo`.

[This is an example of one of the scripts.](https://github.com/decibel/pgxntool-test/blob/master/tests/doc) If you want to check out that repo and try this you should be able to recreate the error; you'd need an install of Postgres along with it's development tools (specifically, `pg_config`) for that to work.

An example of the `.env` file:
----
TOPDIR='/Users/decibel/git/pgxntool-test'
TEST_DIR='/var/folders/mg/s6jx45m50zd32sy8mt60lk_00000gq/T/pgxntool-test.XXXXXX.MARVRVc5'
RESULT_DIR='/Users/decibel/git/pgxntool-test/results'
----
That file is generated by [make-temp.sh](https://github.com/decibel/pgxntool-test/blob/master/make-temp.sh). The default make target will first run [clean-temp.sh](https://github.com/decibel/pgxntool-test/blob/master/clean-temp.sh), which removes `$TEST_DIR` BEFORE it runs make-temp.sh.

What I suspect is happening is the first time SyntacticCheck is run `.env` gets sourced (if it exists). That results in `$TEST_DIR` being set **during the syntax check**, and that setting is being remembered. If clean-temp.sh is later run, the directory `$TEST_DIR` points at will no longer exist, and any subsequent runs of SyntacticCheck fail with the error `E484: Can't open file /var/folders/mg/s6jx45m50zd32sy8mt60lk_00000gq/T/vyuWa5F/13`.

**Comment by lcd047** [comment]
> If I then do `:SyntasticCheck` I'll get an error, which I've pasted above, as well as the requested output of `:SyntasticInfo`.

Sadly, the useful part is not the output of `:SyntasticInfo`, but an additional debug trace that gets printed when you run `:SyntasticInfo` with `g:syntastic_debug=1`, with recent versions of syntastic.  Your output is for 3.7.0-29 , which is an year old.  Syntastic 3.7.0-29 doesn't print the debug trace I asked for.

> What I suspect is happening is the first time SyntacticCheck is run `.env` gets sourced (if it exists).

You don't need to suspect anything.  What syntastic does is shown in the logs you posted: it runs `bash -n doc`.  That's all there is to it.

`E484` means Vim can't create its temporary files.  This is typically caused by messed up `shell`-related options, but if you can also achieve the same effect by messing with `$TMPDIR` and the like (cf. `:h tempfile`).  It hasn't occurred to me until now that it might also be useful to log `$TMPDIR` along with the other junk, but sure, I'll add that.  Good luck making sense of the logs.

**Comment by decibel** [comment]
Bleh, I messed up my second install. I can't make it fail anymore.

FWIW, here's the new SyntasticInfo:
----
Syntastic version: 3.8.0-8 (Vim 800, Darwin, GUI)
Info for filetype: sh
Global mode: active
Filetype sh is active
The current file will be checked automatically
Available checker: sh
Currently enabled checker: sh
syntastic: 188.494868: &shell = '/opt/local/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 1 (!), &shellxescape = ''
----
