### ISSUE TITLE
sphinx unknow directive toctree

### ISSUE THREAD

**Issue by albasili** [vim-syntastic/syntastic#1915]
I've just started a sphinx configuration with sphinx-quickstart and the index.rst generated compiles and renders correctly, unfortunately I have the following from syntastic:

Unknown directive type "toctree".
source/index.rst|18 error| Unknown interpreted text role "ref".
source/index.rst|19 error| Unknown interpreted text role "ref".
source/index.rst|20 error| Unknown interpreted text role "ref".

also reported by @zh0uquan here: https://github.com/amix/vimrc/issues/176

Anything I can do to solve this?
Cheers,

Al

**Comment by lcd047** [comment]
Why are you using `rst2pseudoxml` to check `sphinx` dosuments?

**Comment by albasili** [comment]
I'm sorry I'm not really familiar with the configuration steps, could you highlight what would be needed? I've searched through the documentation but I'm a bit lost.

Any help is appreciated,

Al

**Comment by lcd047** [comment]
* Read the manual: `:h syntastic`
* Set `g:syntastic_rst_checkers`
* Read the docs for the `sphinx` checker`: `:h syntastic-rst-sphinx`

**Comment by albasili** [comment]
E121: Undefined variable: g:syntastic_rst_checkers

If I set manually the following:
:SyntasticCheck sphinx

it does work, but the conf is lost as soon as I save the file or come back to the buffer.

**Comment by lcd047** [comment]
> E121: Undefined variable: g:syntastic_rst_checkers

Well, syntastic is a development tool, you must have a working understanding of VimL in order to use it. _shrug_

**Comment by nosarthur** [comment]
You can add this line to your .vimrc

```
let g:syntastic_rst_checkers=['sphinx']
```
