### ISSUE TITLE
Forward declaration of enum in C++

### ISSUE THREAD

**Issue by BenSapiens** [vim-syntastic/syntastic#1917]
Syntastic doesn't recognize valid declarations of enum in C++, as introduced with C++11.

Valid declarations of enum now have three forms as described [here](http://en.cppreference.com/w/cpp/language/enum):

1. `enum name { enumerator = constexpr , enumerator = constexpr , ... }`

2. `enum name : type { enumerator = constexpr , enumerator = constexpr , ... }`

3. `enum name : type ;`

The latter two are new, and are not recognized by Syntastic.

Please excuse the title; I had a bit of an issue with forward declaration earlier, but this problem is not related to forward declaration specifically.

Likely this problem extends to all C++11-specific changes, but I don't know and don't know enough to test.

**Comment by lcd047** [comment]
Syntastic doesn't care about the contents of your files.  What syntastic does is run third-party linters against your files and show you the results in a window.  It's up to you to configure (1) what linters you want syntastic to run (see `:h syntastic-filetype-checkers`), and (2) what parameters you want to pass to said linters (cf. `:h syntastic-checkers-cpp` and `:h syntastic-debug`).  Feel free to reopen this if you find a linter that produce different sets of errors when run from syntastic and when run with the same options in a terminal; that would make a bug in syntastic.
