### ISSUE TITLE
[language_check] LaTeX (and probably others)

### ISSUE THREAD

**Issue by rubdos** [vim-syntastic/syntastic#1918]
I added `text/language_check` to `syntastic_tex_checkers`, which -- obviously -- doesn't really work perfectly.

How feasible would it be to kind of parse the LaTeX (and other) code before feeding it to `language_check`, or would it be more feasible to put some smartness in `language_check` itself?

"Real" programming languages would also benefit from such a feature, by for example grammar and spell checking on comments, or even variable names.

**Comment by lcd047** [comment]
> How feasible would it be to kind of parse the LaTeX (and other) code before feeding it to `language_check`

Probably not feasible.  The problem of dealing with template languages is substantially easier, and it's still unsolved.  Either way, a solution won't be part of syntastic.  Syntastic doesn't care about the _contents_ of your files, it only runs programs and parses their output.

> or would it be more feasible to put some smartness in `language_check` itself?

This approach might have more merits, but TeX is a macro language, and that makes some parsing operations really hard.  Various heuristics are of course possible, but the result is typically not that great.  I believe [proselint][proselint] already does something like that.

[proselint]: http://proselint.com/

**Comment by rubdos** [comment]
> >   or would it be more feasible to put some smartness in language_check itself?
> 
> This approach might have more merits, but TeX is a macro language, and that makes some parsing operations really hard. Various heuristics are of course possible, but the result is typically not that great. I believe proselint already does something like that.

Ok. I will make an issue with language_check then, let's see what we can do :)
