### ISSUE TITLE
eslint error markers are off by one

### ISSUE THREAD

**Issue by unphased** [vim-syntastic/syntastic#1922]
I use this in `.vimrc`: `let g:syntastic_javascript_checkers = ['eslint']`

    $ eslint --version
    v3.11.1

The syntastic highlight markers land on one character after where they should.

I'm not really asking for someone to guess or know or find out what causes this, I'm asking for debugging steps to figure out how syntastic knows to read eslint output and converts it into markers. So I can try to find the source of the off by one error.

**Comment by unphased** [comment]
Just skimming the code: https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/javascript/eslint.vim#L63

Looks like theres an explicit add one here. Maybe eslint changed from 0-indexed column number to 1-indexed?

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 33, run `:SyntasticCheck eslint`, run `:mes`, and post the output.

**Comment by unphased** [comment]
I've reinstalled everything on a different Linux system and everything seems to be fine with the latest eslint and syntastic. I will just have to try that on the other environment where I was seeing the problem.
