### ISSUE TITLE
how to parse glsl file?

### ISSUE THREAD

**Issue by mp5557** [vim-syntastic/syntastic#1923]
The doc says glsl have cgc checker to check glsl kind of file. However, it doesn't work to files such as *.glsl or *.vert. I run SyntasticInfo in these kind of file, then it says the filetype is conf. So does it need aditional configurations to let checker run?

**Comment by lcd047** [comment]
You need to set `filetype` correctly before running syntastic.  The `filetype` is normally detected by Vim (or by some dedicated plugin, see `:h filetype`), but this detection is heuristic and the results can be incorrect.  When that happens you can override the `filetype` in a modeline (see `:h modeline`).  That's all there is to it, it's up to to you to set it correctly, syntastic won't try to second-guess the value it receives from Vim.

**Comment by mp5557** [comment]
I have added modeline `// vim: filetype=glsl ` in the first line of my file. It did change the filetype of the file, which is glsl. However, the syntastic highlight still doesn't work.

**Comment by lcd047** [comment]
Sntastic is about syntax __checking__.  It has nothing to do with syntax __highlighting__.  For syntax highlighting for `glsl` you need a plugin such as [vim-glsl][vim-glsl] or [glsl.vim][glsl.vim].  Or wait until support for `glsl` is added to Vim.

[vim-glsl]: https://github.com/tikhomirov/vim-glsl
[glsl.vim]: https://github.com/beyondmarc/glsl.vim
