### ISSUE TITLE
variable g:syntastic_r_checkers has to be a list of strings

### ISSUE THREAD

**Issue by RUrlus** [vim-syntastic/syntastic#1926]
OS X 10.11
MacVim 8.0
Syntastic 3.8.0-10

After an update to vim & Syntastic I get the following error:
`error: variable g:syntastic_r_checkers has to be a list of strings`

Syntastic is installed trough Vundle and it works for different languages.

`:SyntasticInfo` output:
```
Syntastic version: 3.8.0-10 (Vim 800, Darwin, GUI)
Info for filetype: r
Global mode: active
Filetype r is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
```

vimrc relevant lines:
```
" R-linter
let g:syntastic_enable_r_lintr_checker = 1
let g:syntastic_r_checkers = ['liner']
```
Using the following instructions from https://github.com/jimhester/lintr:

> Put the file syntastic/lintr.vim in syntastic/syntax_checkers/r. If you are using pathogen this directory is ~/.vim/bundles/syntastic/syntax_checkers/r.
> 
> You will also need to add the following lines to your .vimrc.
> 
> ```
> let g:syntastic_enable_r_lintr_checker = 1
> let g:syntastic_r_checkers = ['liner']
> 
> ```

I've reread the documentation multiple times and can't find the issue, moreover, it's persistent on two machines with identical versions of Vim, Syntastic.

A solution would be much appreciated

**Comment by lcd047** [comment]
`s/liner/lintr/` and try again?

**Comment by lcd047** [comment]
Actually, those instructions tell you to override the `lintr` checker that comes with syntastic with something else.  Your waranty is void if you do that. :smile: Please consider asking the author of said instructions for help if you insist on doing it that way.

**Comment by RUrlus** [comment]
Apparently it was an error caused by the package installation on R's side, working again!
