### ISSUE TITLE
Python checker does not work on Mac OS and CentOS

### ISSUE THREAD

**Issue by johnnyshi1225** [vim-syntastic/syntastic#1927]
Here is my vimrc:

	114 " syntax check
	115 Plugin 'vim-syntastic/syntastic'
	116 let g:syntastic_always_populate_loc_list = 1
	117 let g:syntastic_auto_loc_list = 1
	118 let g:syntastic_check_on_open = 1
	119 let g:syntastic_check_on_wq = 0
	120 let g:syntastic_python_checkers = ['pylint']
	121 "let g:syntastic_python_checkers = ['flake8']
	122 let g:syntastic_python_flake8_args='--ignore=E501'
	123 nnoremap <leader>s : SyntasticToggleMode<CR>
	
And when editing a python file, I made some syntax errors on purpose but syntastic did show any error message.

Here is the result of `:SyntasticInfo`

	Syntastic version: 3.8.0-10 (Vim 800, Darwin)
	Info for filetype: python
	Global mode: active
	Filetype python is active
	The current file will be checked automatically
	Available checkers: pylint python
	Currently enabled checker: pylint
	
And the python code is like:

```python
clas MyClass(object:

    """Docstring for MyClass. """

    def __init__(self):
        """TODO: to be defined1. """
```

**Comment by PangPangPangPangPang** [comment]
How did you resolve the problem? Thx!
