### ISSUE TITLE
Syntastic giving less results compared to when the program is compiled on terminal (c++,clang)

### ISSUE THREAD

**Issue by FloatingFowl** [vim-syntastic/syntastic#1931]
I wrote a sample program and when I saved it, Syntastic returns only one error (missing semicolon) compared to eight errors when I ran `clang++ <program>` on the terminal. The Syntastic settings are below. The program and the screenshots of the error are [here](http://imgur.com/a/s5Pgv), the program is also pasted below the .vimrc settigns.

    "For Syntastic
    set statusline+=%#warningmsg#
    set statusline+=%{SyntasticStatuslineFlag()}
    set statusline+=%*
    "
    "For Syntastic again
    let g:syntastic_always_populate_loc_list = 1
    let g:syntastic_auto_loc_list = 1
    let g:syntastic_check_on_open = 1
    let g:syntastic_check_on_wq = 0
    let g:syntastic_cpp_compiler = "clang++"
    let g:syntastic_cpp_compiler_options = ' -std=c++14 -stdlib=libc++'

    "For Syntastic's window that manages size
    function! SyntasticCheckHook(errors)
        if !empty(a:errors)
            let g:syntastic_loc_list_height = min([len(a:errors), 10])
        endif
    endfunction

The program:

    #include <bits/stdc++.h>
    using namespace std;
    template <typename A,typename B>
    auto sum(A a,B b) -> typename common_type<A, B>::type {
        return static_cast<typename common_type<A,B>::type>(a) + static_cast<typename common_type<A, B>::type>(b);
    }
    
    template <typename A,typename B, typename... Args>
    auto sum(A a,B b, Args... args) -> typename common_type <A, B, Args...>::type {
        return sum(sum(a, b), args...);
    }
    int main()
    {
        int x;
        int y;
        int z;
        int w
        cin>>x>>y>>z;
        cout<<x+y<<'\n';
        cout<<sum(1,2,3,4,5)<<'\n';
        return 0;
    }

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 3, run `:SyntasticCheck gcc`, run `:mes`, and post the output.  Please use copy & paste rather than screenshots.

**Comment by FloatingFowl** [comment]
@lcd047 Here's the output after doing your instructions:

```
"~/.vim/template/cpp.template" 9L, 223C
--No lines in buffer--
"simply.cpp" [New] 22L, 561C written
Pattern not found: syntastic_debug=3
syntastic: 81.216585: g:syntastic_version = '3.8.0-9 (Vim 800, Darwin)'
syntastic: 81.216972: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir
= 0, &shellxescape = ''
syntastic: 81.218585: UpdateErrors: gcc
syntastic: 81.219173: CacheErrors: gcc
syntastic: 81.220850: g:syntastic_aggregate_errors = 0
syntastic: 81.221469: getcwd() = '/Users/Mohsin'
syntastic: 81.222289: CacheErrors: Invoking checker: cpp/gcc
syntastic: 81.223558: SyntasticMake: called with options: {'postprocess': [], 'errorformat': '%-G%f:%s:,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f
:%l: %tarning: %m,%f:%l: %m', 'makeprg': '''clang++'' -x c++ -fsyntax-only  -std=c++14 -stdlib=libc++ -I. -I.. -Iinclude -Iincludes -I../include -I../includes   simply.cpp'}
syntastic: 82.321727: system: command run in 1.097541s
syntastic: 82.322055: checker output: ['simply.cpp:17:10: error: expected '';'' at end of declaration', '    int w', '         ^', '         ;', '1 error generated.', '']
syntastic: 82.366843: raw loclist: [{'lnum': 17, 'bufnr': 1, 'col': 10, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'e', 'pattern': '', 'text': 'expected '';'' at end of declaration'},
 {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    int w'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -
1, 'type': '', 'pattern': '', 'text': '         ^'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '         ;'}, {'lnum': 0,
 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '1 error generated.'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1,
'type': '', 'pattern': '', 'text': ''}]
syntastic: 82.367540: getLocList: checker cpp/gcc returned 1
syntastic: 82.367754: cpp/gcc raw: [{'lnum': 17, 'bufnr': 1, 'col': 10, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'e', 'pattern': '', 'text': 'expected '';'' at end of declaration'},
 {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    int w'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -
1, 'type': '', 'pattern': '', 'text': '         ^'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '         ;'}, {'lnum': 0,
 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '1 error generated.'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1,
'type': '', 'pattern': '', 'text': ''}]
syntastic: 82.368369: quiet_messages filter: {}
syntastic: 82.368601: getLocList: checker cpp/gcc run in 1.146131s
syntastic: 82.369279: aggregated: {'_sorted': 0, '_name': 'gcc (cpp)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 17, 'bufnr': 1, 'col': 10, 'valid': 1, 'vcol': 0, 'nr': -
1, 'type': 'e', 'pattern': '', 'text': 'expected '';'' at end of declaration'}]}

```

**Comment by lcd047** [comment]
Now please run this in a terminal and compare the results:
```sh
cd /Users/Mohsin
clang++ -x c++ -fsyntax-only  -std=c++14 -stdlib=libc++ -I. -I.. -Iinclude -Iincludes -I../include -I../includes   simply.cpp
```

**Comment by FloatingFowl** [comment]
@lcd047 Yeah in this case I only get that single error which Syntastic shows

**Comment by lcd047** [comment]
That's the command syntastic runs.  The `-x c++ -fsyntax-only` options are mandatory, and you can skip the includes by setting `g:syntastic_cpp_include_dirs`.  The remaining `-std=c++14 -stdlib=libc++` are your own doing.
