### ISSUE TITLE
Frosted not reading configuration file

### ISSUE THREAD

**Issue by nlw0** [vim-syntastic/syntastic#1933]
I'm trying to use the Frosted plugin, but it seems to ignore the configuration file at `~/.frosted.cfg`. What could be going on? How do I properly configure the plugin?

**Comment by lcd047** [comment]
Please open your test file, run `:SyntasticInfo` and post the output.  Then set `g:syntastic_debug` to 3, run `:SyntasticCheck frosted`, run `:mes`, and post the output again.  Please avoid screenshots, use copy & paste instead.

**Comment by nlw0** [comment]
Syntastic version: 3.8.0-10 (Vim 704, Linux)
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
Available checkers: flake8 frosted pyflakes python
Currently enabled checkers: flake8 frosted
syntastic: 13.425254: g:syntastic_version = '3.8.0-10 (Vim 704, Linux)'
syntastic: 13.425521: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 13.426426: UpdateErrors: frosted
syntastic: 13.426830: CacheErrors: frosted
syntastic: 13.427987: g:syntastic_aggregate_errors = 0
syntastic: 13.428344: getcwd() = '/home/nic'
syntastic: 13.429155: CacheErrors: Invoking checker: python/frosted
syntastic: 13.430217: SyntasticMake: called with options: {'errorformat': '%f:%l:%c:%m,%E%f:%l: %m,%-Z%p^,%-G%.%#', 'makeprg': 'frosted -vb src/code/file.py', 'env': {'TERM': 'dumb'}, 'returns': [0, 1]}
syntastic: 13.582746: system: command run in 0.151955s
syntastic: 13.583009: checker output: ['']
syntastic: 13.583493: raw loclist: []
syntastic: 13.583779: getLocList: checker python/frosted returned 0
syntastic: 13.583966: python/frosted raw: []
syntastic: 13.584248: quiet_messages filter: {}
syntastic: 13.584446: getLocList: checker python/frosted run in 0.155087s
syntastic: 13.584883: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
Press ENTER or type command to continue

**Comment by lcd047** [comment]
> syntastic: 13.583009: checker output: ['']

Now please run this in a terminal, and compare the results:
```sh
cd /home/nic
frosted -vb src/code/file.py
```

**Comment by nlw0** [comment]
Nothing is reported. And If I remove the "ignore_frosted_errors=E101" from my `~/.frosted.cfg` it does report it...

**Comment by lcd047** [comment]
> Nothing is reported.

Excellent: results shown by syntastic are in synch with results produced by `frosted`.  Feel free to re-open this if you can find a situation when you get different results when running `frosted` from syntastic and when running it in a terminal.  You can tell syntastic to pass options to `frosted` using the `g:syntastic_python_frosted_args` variable (cf. `:h 'syntastic_<filetype>_<checker>_<option>'`).  Beyond that, if `frosted` doesn't behave the way you expect it when running it in a terminal you should probably open an issue at the `frosted` project.

**Comment by nlw0** [comment]
I don't get it, it is ignoring the error as it should in the terminal but it still gets reported on vim... But anyway, I have solved it using `g:syntastic_python_frosted_args` like you said.

**Comment by lcd047** [comment]
> I don't get it, it is ignoring the error as it should in the terminal but it still gets reported on vim...

Your logs above show otherwise:

> syntastic: 13.583009: checker output: ['']

**Comment by nlw0** [comment]
OK, the message is now actually coming from flake8, so it's all right... I actually will have to check all that in a different machine now. But thanks for the help, now I know how to debug it!

**Comment by lcd047** [comment]
Reading the manual could have saved you a lot of time.  In this particular case: `:h 'syntastic_<filetype>_<checker>_<option>'` and `:h syntastic-debug`.
