### ISSUE TITLE
'invalid syntax' reported for Python 

### ISSUE THREAD

**Issue by OolonColoophid** [vim-syntastic/syntastic#1938]
Hi there

macOS 10.12.1; Vim 8.0; Syntastic 3.8.0-10 (Vim 800, Darwin); Available checker: Python

Great plugin, thanks.

I'm learning Python and have been using the following way of calling the print() function:

```
print(
    """
    Hello world
    """
)
```

This is the form used in my textbook, and Python3 renders the script happily, but Syntastic reports the following error:

> invalid syntax

Is this perhaps a Python 2/3 difference? (New to Python so I can't be sure).

Cheers

Ian

**Comment by OolonColoophid** [comment]
> Currently enabled checker: python

**Comment by lcd047** [comment]
> > Currently enabled checker: python

So, what checker reports it?

**Comment by OolonColoophid** [comment]
Sorry, lcd047, you've lost me. I thought that was the checker... How, precisely, do I get the info you're requesting?

**Comment by lcd047** [comment]
That's what syntastic runs by default.  It may or may not be the checker that produced the errors.

To answer your question: `:h syntastic-debug`.  Or just look at the statusline of the error window.

_If_ it really is the `python` checker, you should probably look first at line endings of your source (LF vs. CR vs. CRLF).  Syntastic doesn't "invent" error messages, it's always an external program that produces them.

**Comment by OolonColoophid** [comment]
Thanks, lcd. This isn't in my status line (I'm using Airline; might be why) but setting the debug variable did the trick. The checker is confirmed as 'python/python', as far as I can see from the debug message, and Vim (given the command `set ff? ffs?` returns 'fileformats=unix,dos')---when I force LF endings using `setlocal ff=unix` and save the file, the python checker still reports the above syntax as in error.

**Comment by lcd047** [comment]
> I'm using Airline; might be why

`airline` does show the name of the checker by default:
![2016-12-28-101445_377x74](https://cloud.githubusercontent.com/assets/1281736/21517345/07857cbe-cce7-11e6-9c54-585b43336887.png)

> Vim (given the command `set ff? ffs?`) returns 'fileformats=unix,dos'.

`set ff? ffs?` will tell you how Vim _detects_ line endings and how it _writes_ the file.  It won't tell you anything about the _current_ line endings.  Actually, Vim is not the right tool to find out whether your file contains binary junk, use `od` instead.

> When I force LF endings using `setlocal ff=unix` and save the file, the python checker still reports the above syntax as in error.

Syntastic checks the file on disk, not the contents of the current buffer.  So changing `ff` will take effect only after you write the file.  It also won't affect BOMs.

Anyway, like I said, the problem has nothing to do with syntastic.  You'll probably get the same error when you try to run the file.

**Comment by OolonColoophid** [comment]
Morning,

Thanks for getting back to me. I think we’re going around in circles a bit.  Not sure if this email will reach you, but some comments below. Since you’ve closed the issue, you might want to move on with your life! No need to reply if you’d prefer not to.

> On 28 Dec 2016, at 08:25, LCD 047 <notifications@github.com> wrote:
> 
> I'm using Airline; might be why
> 
> airline does show the name of the checker by default:
>  <https://cloud.githubusercontent.com/assets/1281736/21517345/07857cbe-cce7-11e6-9c54-585b43336887.png>
> 

Quite possibly it does, but I’m not using the default settings.

> Vim (given the command set ff? ffs?) returns 'fileformats=unix,dos'.
> 
> set ff? ffs? will tell you how Vim detects line endings and how it writes the file. It won't tell you anything about the current line endings. Actually, Vim is not the right tool to find out whether your file contains binary junk, use od instead.
> 
Thanks - I didn’t know about ‘od’. I don’t have any reason to think Vim is using non-standard line endings - I’ve never changed that. 

> When I force LF endings using setlocal ff=unix and save the file, the python checker still reports the above syntax as in error.
> 
> Syntastic checks the file on disk, not the contents of the current buffer. So changing ff will take effect only after you write the file. It also won't affect BOMs
> 
Sure - but if Syntastic is checking the written form of the file, saving the file after ff-unix would therefore fix it because this is changing the written form. Am I missing something?
> Anyway, like I said, the problem has nothing to do with syntastic. You'll probably get the same error when you try to run the file.
> 

I don’t see any evidence that it’s anything other than Syntastic, and, as I wrote in earlier, my Python interpreter is not reporting a syntax error when running the script—there isn’t one because the syntax is valid (or at least appears to be).

Do you have any ideas what I could do next?

Cheers

Ian

**Comment by OolonColoophid** [comment]
Hi Lcd

Further to my last email, I’ve realised that this is indeed a Python version issue (stupidly, I was looking at the wrong line in the file; it’s a Python3-specific version of the ‘print’ function that is causing the error).

This makes it much easier to solve. Thanks again for your help.

Cheers

Ian

**Comment by lcd047** [comment]
> Am I missing something?

Nope, you (almost) ruled out the cause being line endings.  There are still plenty of weird corner cases left for you to explore: BOM, the environment in Vim being different from the environment in your terminal, `autocmd`s and / or other plugins interferring, the error list being actually produced by some other plugin, and so on.  Life with Vim is usually infuriating, but never boring. _shrug_

> I don’t see any evidence that it’s anything other than Syntastic

As I said: syntastic doesn't pull error messages out of thin air.  Syntastic doesn't now, nor care, about the contents of your files.  What syntastic does is run some linters against your files, and shows you the results in a window.  As such, the answer to "why do I get message X?" is never ever syntastic.  Some checker produces the error messages, not syntastic itself.  Syntastic _could_ be (and often is) the answer to the question "why I _don't_ get message X?" (because that might be a parsing bug).

> Do you have any ideas what I could do next?

Ok.  Please set `g:syntastic_debug` to 3, run the checker, run `:mes` and post the output.
