### ISSUE TITLE
The vim cursor become strange when It detects there are syntax error

### ISSUE THREAD

**Issue by haolly** [vim-syntastic/syntastic#1939]
I use luac for my lua checker, when there are syntax error, the cursor become strange like this:
![image](https://cloud.githubusercontent.com/assets/2383231/21535579/1434aa22-cdb2-11e6-8cf9-3e396c8cf111.png)

the error line will appear strange too. My cursor is not in the end of the line

![image](https://cloud.githubusercontent.com/assets/2383231/21535635/b913078c-cdb2-11e6-8cf3-e41556b96cdc.png)

**Comment by lcd047** [comment]
Syntastic has no control over low-level screen refreshes.  Please see #822 for more comments and approach suggestions.
