### ISSUE TITLE
Way to toggle quickfix arrows?

### ISSUE THREAD

**Issue by impulkit** [vim-syntastic/syntastic#1943]
Hi,

When syntastic displays the quickfix arrows, I am unable to copy using mouse as the quickfix arrows are also copied.
I was wondering if there was a way to toggle the quickfix arrows ?

**Comment by lcd047** [comment]
I presume "quickfix arrows" is your term for Vim's signs (`:h sign-support`).  Signs are managed by Vim, not by syntastic.  With Vim 8 you can turn them off with `set scl=no`, then you can turn them back on with `set scl=auto` (see `:h 'signcolumn'`).  With earlier versions of Vim there's no `scl`, but you can just set `g:syntastic_enable_signs` to 0 and run the checker again.
