### ISSUE TITLE
MacVim makes Vint (VimL linter) crash, but only when invoked from Finder

### ISSUE THREAD

**Issue by rlue** [vim-syntastic/syntastic#1945]
I'm getting an error when I run `:SyntasticCheck` on VimL files with vint. Here's the output for the Syntastic debug log:

```
syntastic: warning: checker vim/vint: unrecognized error format (crashed checker?)
syntastic: 255.519186: g:syntastic_version = '3.8.0-3 (Vim 800, Darwin, GUI)'
syntastic: 255.519360: &shell = '/bin/bash', &shellcmdflag = '-c', 
  &shellpipe = '2>&1 | tee', 
  &shellquote = '', 
  &shellredir = '>%s 2>&1', 
  &shelltemp = 1, 
  &shellxquote = '', 
  &autochdir = 0, 
  &shellxescape = ''
syntastic: 255.519927: UpdateErrors: vint
syntastic: 255.520186: CacheErrors: vint
syntastic: 255.520800: g:syntastic_aggregate_errors = 0
syntastic: 255.520984: getcwd() = '/Users/rlue'
syntastic: 255.521474: CacheErrors: Invoking checker: vim/vint
syntastic: 255.522067: SyntasticMake: called with options: 
  {'preprocess': 'vint', 
   'errorformat': '%f:%l:%c:%t: %m', 
   'makeprg': 'vint /Users/rlue/.vim/config/mappings.vim --json', 
   'returns': [0, 1]}
syntastic: 255.847839: system: command run in 0.325377s
syntastic: 255.848224: checker output: 
  ['Traceback (most recent call last):', 
   '  File "/usr/local/bin/vint", line 11, in <module>', 
   '    sys.exit(main())', 
   '  File "/usr/local/lib/python2.7/site-packages/vint/__init__.py", line 11, in main', 
   '    init_cli()', 
   '  File "/usr/local/lib/python2.7/site-packages/vint/bootstrap.py", line 22, ininit_cli', 
   '    cli.start()', 
   '  File "/usr/local/lib/python2.7/site-packages/vint/linting/cli.py", line 26, in start', 
   '    config_dict = self._build_config_dict(env)',
   '  File "/usr/local/lib/python2.7/site-packages/vint/linting/cli.py", line 56, in _build_config_dict', 
   '    ConfigDefaultSource(env),', 
   '  File "/usr/local/lib/python2.7/site-packages/vint/linting/config/config_file_source.py", line 12, in __init__', 
   ' with config_file_path.open() as file_obj:', 
   '  File "/usr/local/lib/python2.7/site-packages/pathlib.py", line 1077, in open', 
   '    return io.open(str(self), mode, buffering, encoding, errors, newline)', 
   'LookupError: unknown encoding: ', '']
syntastic: warning: checker vim/vint: unrecognized error format (crashed checker?)
syntastic: 255.849312: preprocess: []
syntastic: 255.849533: raw loclist: []
syntastic: 255.849727: getLocList: checker vim/vint returned 1
syntastic: 255.849863: vim/vint raw: []
syntastic: 255.850016: quiet_messages filter: {}
syntastic: 255.850130: getLocList: checker vim/vint run in 0.328544s
syntastic: 255.850399: aggregated: {'_sorted': 0, '_name': '', '_owner': 2, '_columns': 1, '_rawLoclist': []}
```

Again, this only happens when MacVim is invoked from the Finder. No such errors crop up in terminal vim, nor when MacVim is launched with `mvim` from the Terminal.

Originally posted as an issue with Vint [here](https://github.com/Kuniwak/vint/issues/198).

**Comment by lcd047** [comment]
You should be able to reproduce the problem outside syntastic, by running:
```vim
:echo system('vint /Users/rlue/.vim/config/mappings.vim --json')
```
Hope this helps.

**Comment by lcd047** [comment]
You might be able to get some useful information by comparing the results of `:echo system('env')` when you start MacVim from Finder and when you start it outside Finder.

**Comment by rlue** [comment]
You're absolutely correct. I get the same traceback as posted above, and no error at all when running the same command from `mvim`. 

I'm gonna go ahead and close this comment, but I don't suppose you have any insight as to how different environment variables might affect the behavior, do you? I removed all the lines these two had in common, and what's left is this from `mvim` launched in the terminal:

    TERM_PROGRAM=Apple_Terminal
    TERM=xterm-256color
    TERM_PROGRAM_VERSION=361.1
    TERM_SESSION_ID=510177A0-89AD-482B-93E8-313C3DD5A225
    SHLVL=3
    LC_CTYPE=UTF-8

and this from MacVim launched from the Finder:

    SHLVL=1

**Comment by lcd047** [comment]
> I don't suppose you have any insight as to how different environment variables might affect the behavior, do you?

Do you still get the same problem when you explicitly add `LC_CTYPE`, like this:
```vim
:echo system('LC_CTYPE=UTF-8 vint /Users/rlue/.vim/config/mappings.vim --json')
```

**Comment by rlue** [comment]
That's a bingo! (Is that the way you say it? “That's a bingo?”)

**Comment by lcd047** [comment]
That seems to be the crux of the matter: Finder kills locales.  You should report this upstream.

In the mean time, this should be a good workaround for syntastic:
```vim
let g:syntastic_vim_vint_exe = 'LC_CTYPE=UTF-8 vint'
```
You could also try to export `LC_CTYPE=UTF-8` from `bash(1)`, but doing that for non-interactive shells is a bit of a pain.

Also, `vint` should provide some kind of fallbaxk when locales are not available.

**Comment by rlue** [comment]
Brilliant!

Sorry, upstream as in with Apple? Do they listen to stuff like this?

**Comment by lcd047** [comment]
> upstream as in with Apple?

Yup.

> Do they listen to stuff like this?

No idea about that, sorry.

**Comment by rlue** [comment]
cool – well, I guess I'll see how far I get. Thanks for all your help!
