### ISSUE TITLE
Syntastic doesn't find eslint

### ISSUE THREAD

**Issue by exos** [vim-syntastic/syntastic#1949]
I've installed eslint via npm, and it's on a nvm path, but works, I read [this ISSUE](https://github.com/vim-syntastic/syntastic/issues/1110) but without results.

In my ```.vimrc```:

```
let g:loaded_syntastic_javascript_eslint_checker = 1
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exec = '/home/exos/.nvm/versions/node/v5.11.1/bin/eslint'
```

$PATH from Syntastic:
```
/usr/local/bin:/usr/local/bin:/home/exos/.nvm/versions/node/v5.11.1/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-to
ols:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```
And the path is correct:
```
$ whereis eslint
eslint: /home/exos/.nvm/versions/node/v5.11.1/bin/eslint
```

But SyntasticInfo shows:
```
Syntastic version: 3.8.0-14 (Vim 800, Linux, GUI)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checker: jshint
Currently enabled checkers: -
Press ENTER or type command to continue
```
There are some wrong?

Thanks

**Comment by exos** [comment]
Sorry, It was a problem with ```.zhenv```, fixing that,  I add by error the line ```let g:loaded_syntastic_javascript_eslint_checker = 1```.

It's working well now.

**Comment by lcd047** [comment]
For what it's worth: setting `g:loaded_syntastic_javascript_eslint_checker` prevents the checker from loading.  So if it seems to be working, either you're setting it too late to take any effect, or you aren't actually running syntastic.  If you want to have `eslint` installed locally you should read #1692. _shrug_
