### ISSUE TITLE
Support -iquote in .syntastic_c_config

### ISSUE THREAD

**Issue by Nemo157** [vim-syntastic/syntastic#1952]
Currently there's special-casing for `-I./blah` in `.syntastic_c_config` to work when the file being checked is in a subdirectory by replacing `.` by the path to the directory that `.syntastic_c_config` is in, this could be extended to also support `-iquote./blah` lines as they have a similar issue.

**Comment by lcd047** [comment]
I'm not sure I understand your point.  Syntastic has nothing to do with `clang_complete`.

**Comment by Nemo157** [comment]
See https://github.com/vim-syntastic/syntastic/blob/b03f26d049c31c9ae341a94f4f3c680fecd9eda5/autoload/syntastic/c.vim#L54-L66

**Comment by Nemo157** [comment]
Whoops, I override the config file to `.clang_complete` the default one is `.syntastic_c_config`, I'll update the first post.

**Comment by lcd047** [comment]
Please.  I wrote that piece of code, I'm familiar with it.  Me trying to mind-read what you're trying to do is not how this is supposed to work.  Please explain (preferably in full English sentences) what you want, and how this is relevant to syntastic.

**Comment by Nemo157** [comment]
C compilers support two ways to define include directories `-I<path>` for paths that should be resolvable for `#include <foo.h>` and `-iquote<path>` for paths that should be resolvable for `#include "foo.h"`.

The current `c.vim` allows you to specify a relative path in the config file for `-I<path>` lines and will automatically fix it when invoking the compiler, but any `-iquote<path>` line will be passed verbatim to the compiler and not resolve correctly for source files that are not stored in the same directory as the config file.

**Comment by Nemo157** [comment]
For example with the directory tree

```
 +- source
    +- foo
    |  +- bar
    |     +- foobar.c
    +- .syntastic_c_config
    +- inc.h
```

If `.syntastic_c_config` has `-I.` and `foobar.c` has `#include <inc.h>` then everything will run correctly because of the path replacement.

However, if `.syntastic_c_config` has `-iquote.` and `foobar.c` has `#include "inc.h"` then you will get `fatal error: 'inc.h' file not found` because the `-iquote.` line is not replaced with the absolute path.

**Comment by lcd047** [comment]
This has been discussed a number of times in the past.  It's a reasonable request, but sadly there is no reasonable way to satisfy it.

The mechanism of config files is intended to save you the pain of quoting arguments according to Vim rules, not to add syntactic sugar to compiler options.  It's used for ~25 completely unrelated compilers, not only for GCC and CLang (see `:h syntastic-config-checkers`).  Most of these compilers don't support `-iquote`.

But even if you focus only on GCC, there are about a dozen other `-ijunk`, `-ijunkdir`, `-prefixjunk`, etc. that would need the same change, and even the list of these varies wildly across versions of GCC.  The point being, the key for using the same config file function for 25 compilers has been it being _dumb_.  Write a script (or use Vim :smile:) if you need to massage directories in config files. _shrug_
