### ISSUE TITLE
 Can't open temp file on windows 10

### ISSUE THREAD

**Issue by aballway** [vim-syntastic/syntastic#1955]
When trying to go through the steps in the FAQ 4.1 to figure out why HLint isn't working I get:

syntastic: error: exception running system('echo %PATH%'): Vim(let):E484: Can't open file C:/Users/my_user_name/AppData/Local/Temp/VIo806F.tmp

syntastic: 3.492532: getcwd() = 'C:\Users\my_user_name'
syntastic: 3.492715: &shell = 'powershell' (!), &shellcmdflag = '-command' (!), &shellpipe = '>', &shellquote = '', &shellredir = '>', &shelltemp = 1, &shellxquote = '"', &autochdir = 1 (!), &shellslash = 0, &shellxescape = '"&|<>()@^'

this happens when I have my shell set to powershell and when I leave it as default.
my local repo is up to date with master

**Comment by lcd047** [comment]
Please read `:h syntastic-powershell`.  On a side note, `autochdir` won't work with some checkers, either.

**Comment by aballway** [comment]
Thanks for the quick reply.  Switching from powershell to cmd whenever I try to open my file I get booted into a command prompt with:

syntastic: 0.060281: SyntasticMake: called w... 'hlint "C:\Users\my_user_name\haskell\simple.hs"'}Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

but the top bar shows I'm still in vim with:

Command Prompt - vim simple.hs - !(hlint ^"C:\Users\my_user_name\haskell\simplehs^" ^>C:/Users/my_user_name/AppData/Local/Temp/Vl01987.tmp 2^>^&1)

**Comment by lcd047** [comment]
You have other shell-related settings you need to undo. From your logs above, `shellcmdflag` is one of them, but there might be others.  Syntastic needs a working `system()`.  Fix that, and syntastil will (hopefully) also start working.

**Comment by aballway** [comment]
Alrighty, so I got rid of that and it fixed the command prompt issue, but still not working.  I still get

**syntastic: error: exception running system('echo %PATH%'): Vim(let):E484: Can't open file C:\Users\my_user_name\AppData\Local\Temp\VIoCE1E.tmp**

syntastic: 254.674087: $PATH = 'C:\Program Files\Haskell\bin;C:\Program Files\Haskell Platform\8.0.2\lib\extralibs\bin;C:\Program Files\Haskell Platform\8.0.2\bin;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\LLVM\bin;C:\Program Files (x86)\WindowsKits\10\WindowsPerformanceToolkit\;C:\ProgramData\chocolatey\bin;C:\ProgramData\chocolatey\lib\Elixir/bin;C:\Program Files\Git\cmd;C:\Go\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\ProgramFiles(x86)\nodejs\;C:\ProgramFiles\HaskellPlatform\8.0.2\mingw\bin;C:\Users\my_user_name\AppData\Roaming\cabal\bin;C:\Users\my_user_name\AppData\Roaming\local\bin;C:\Users\my_user_name\.cargo\bin;C:\Users\my_user_name\AppData\Local\Microsoft\WindowsApps;C:\Users\my_user_name\AppData\Roaming\npm;C:\cygwin64\bin;C:\Users\my_user_name\AppData\Roaming\local\bin\;C:\Program Files (x86)\Vim\vim80'

syntastic: 254.675168: getcwd() = 'C:\Users\my_user_name\haskell'
syntastic: 254.675301: &shell = 'C:\Windows\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquot
e = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '(', &autochdir = 0, &shellslash = 0, &shellxescape = '
"&|<>()@^'

Thanks again for the help!

**Comment by lcd047** [comment]
Like I said: you need a working `system()`.  That has nothing to do with syntastic.  Sadly, the last version of Windows I actually used was 3.1, in ~1993.  So debugging what _else_ you might need to undo from your vimrc to get it working is out of my league. :smile: Perhaps ask on some Windows forum?

**Comment by aballway** [comment]
Oh I see, thanks!  I'll update this if I ever get it to work 😆

**Comment by aballway** [comment]
I was able to get it working by modifying my .vimrc with the following

```
set shell=cmd
set shellcmdflag=/c
```

It seems on Windows the `system` command will fail unless these are set, which causes all of the nonsense as seen above.  It may be worth adding this to the "Reasons it might not be working" section of the FAQ.

Thanks for all of the help, I really appreciate it!
