### ISSUE TITLE
Can't change the colour of the hat beneath character for style warnings

### ISSUE THREAD

**Issue by jamesdhooks** [vim-syntastic/syntastic#1956]
Googled around and couldn't solve it. For style warnings it places a hat ^ beneath the character and is currently dark blue, which is difficult to see. I can't find the setting under my highlights with a colour that matches and have tried overriding all highlight groups in the docs. What is the highlight for this?

**Comment by lcd047** [comment]
From `:h syntastic-error-window`:
> By default the SpellBad syntax highlight group is used to color errors,
and the SpellCap group is used for warnings. If you wish to customize the
colors for highlighting you can use the following groups:
>
>    SyntasticError - Links to "SpellBad" by default (see hl-SpellBad)
>    SyntasticWarning - Links to "SpellCap" by default (see hl-SpellCap)
>    SyntasticStyleError - Links to "SyntasticError" by default  
>    SyntasticStyleWarning - Links to "SyntasticWarning" by default

**Comment by jamesdhooks** [comment]
Changing SpellCap fixed it thank you!
