### ISSUE TITLE
Java: importing user made packages.

### ISSUE THREAD

**Issue by FizzyQuizzler** [vim-syntastic/syntastic#1959]
I have been working on figuring this out for about a week now, I have a Java class that is importing classes from another package in the same folder. however syntastic says that the package XXXXX.Gui.GetPane; does not exist and that it "cannot find symbol" for any of the methods called from this package. it does compile fine it just wont find any of these packages... am I doing something wrong?

**Comment by lcd047** [comment]
Please read `:h syntastic-config-makeprg` and `:h syntastic-config-debug`.
