### ISSUE TITLE
Preview of perl6 support (redux)

### ISSUE THREAD

**Issue by nxadm** [vim-syntastic/syntastic#1961]
Hi @lcd047 (and co.),

The [syntastic-perl6 repo](https://github.com/nxadm/syntastic-perl6) was updated to support the perl6 JSON error output. I am by no mean an expert on vimscript, but the new plugin seems to work and is more robust than the regex based code/

I'll wait on input from the community to improve it and if the code evolves to be OK, prepare a PR.

Regards,

C.

**Comment by lcd047** [comment]
Let's switch back to the old thread #1846.
