### ISSUE TITLE
Javascript/flow checker fails silently if flow-bin version is below 0.34

### ISSUE THREAD

**Issue by shofel** [vim-syntastic/syntastic#1963]
## Summary
[screencast](https://asciinema.org/a/5bv88jodm2ei57qfo0we5osm8) reproducing the bug

## Steps to reproduce:
1. Install flow-bin 0.33
```
$ yarn global add flow-bin@0.33
...
$ flow version
Flow, a static type checker for JavaScript, version 0.33.0
```
2. Open any `.js` file with flow errors
3. Expect: errors in location window
4. Got:
* no errors reported
* got the message: `syntastic: 0.214280: CacheErrors: Checker javascript/flow is not available`
### (bonus)
5. update flow-bin
```
$ yarn global add flow-bin@0.34
...
$ flow version
Flow, a static type checker for JavaScript, version 0.34.0
```
6. Open the same `.js` file
7. Got some errors reported 

## Possible Root of the Evil
https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/javascript/flow.vim#L28

### Vim Version
```
:ver                                                                                                     
NVIM 0.2.0-dev                                                                                            
Build type: RelWithDebInfo                                                                                
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-securit
y -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unu
sed-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINC
LUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-38GZXR/neovim-0.1.7ubuntu1+git20
1701281330+3091+23~ubuntu16.04.1/build/config -I/build/neovim-38GZXR/neovim-0.1.7ubuntu1+git201701281330+3
091+23~ubuntu16.04.1/src -I/build/neovim-38GZXR/neovim-0.1.7ubuntu1+git201701281330+3091+23~ubuntu16.04.1/
.deps/usr/include -I/build/neovim-38GZXR/neovim-0.1.7ubuntu1+git201701281330+3091+23~ubuntu16.04.1/.deps/u
sr/include -I/build/neovim-38GZXR/neovim-0.1.7ubuntu1+git201701281330+3091+23~ubuntu16.04.1/.deps/usr/incl
ude -I/build/neovim-38GZXR/neovim-0.1.7ubuntu1+git201701281330+3091+23~ubuntu16.04.1/.deps/usr/include -I/
build/neovim-38GZXR/neovim-0.1.7ubuntu1+git201701281330+3091+23~ubuntu16.04.1/.deps/usr/include -I/build/n
eovim-38GZXR/neovim-0.1.7ubuntu1+git201701281330+3091+23~ubuntu16.04.1/.deps/usr/include -I/usr/include -I
/build/neovim-38GZXR/neovim-0.1.7ubuntu1+git201701281330+3091+23~ubuntu16.04.1/build/src/nvim/auto -I/buil
d/neovim-38GZXR/neovim-0.1.7ubuntu1+git201701281330+3091+23~ubuntu16.04.1/build/include                   
Compiled by root@lgw01-31                                                                                 
                                                                                                          
Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui                                
For differences from Vim, see :help vim-differences                                                       
                                                                                                          
   system vimrc file: "$VIM/sysinit.vim"                                                                  
  fall-back for $VIM: "/usr/share/nvim"                                                                   
```

### Syntastic Version
```
Syntastic version: 3.8.0-21 (Vim 704, Neovim, Linux)                                                      
Info for filetype: javascript                                                                             
Global mode: active                                                                                       
Filetype javascript is active                                                                             
The current file will be checked automatically                                                            
syntastic: 975.810029: system: command run in 0.181361s                                                   
syntastic: 976.044979: system: command run in 0.230846s                                                   
Available checkers: eslint standard                                                                       
Currently enabled checkers: -                                                                             
syntastic: 976.046169: &shell = '/usr/bin/fish', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquo
te = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''  
```

**Comment by shofel** [comment]
According to [the search](https://github.com/vim-syntastic/syntastic/search?utf8=%E2%9C%93&q=versionIsAtLeast) for usage of `syntastic#util#versionIsAtLeast` method, this is a common pattern to ignore checkers based on some minimal version.

So, this is a feature, but not a bug?
As for me, I expect some message explaining about `flow-bin` version below `0.34` is not suitable for `Syntastic`. This is at least not obvious :)

**Comment by lcd047** [comment]
The root of all evil is you not reading the manual.  What you were supposed to do was:

* read `:h syntastic-javascript-flow`; there, you'd find that:
    > Syntastic requires "Flow" version 0.34.0 or later.
* install flow version 0.34.0 or later
* run `:SyntasticInfo javascript`, and make sure `flow` is marked as available
* add `flow` to `g:syntastic_javascript_checkers`.

> As for me, I expect some message explaining about `flow-bin` version below `0.34` is not suitable for `Syntastic`. This is at least not obvious :)

That would be possible if syntastic tried to autodetect `flow` for you.  This is not how syntastic works.  Read the archives if you're curious to find out why autodetection doesn't make sense. _shrug_

**Comment by shofel** [comment]
@lcd047, first of all, sorry if my messages are looking bully or somewhat. I haven't done that deliberately :slightly_smiling_face:

I agree with you about reading the docs. Surely this is true - at least for the first-time set up. When I was setting up this initially, I read the docs and easily succeed thankful to them.

My current story is about mystic break of the flow checker. So, the story is the following.

1) I've had the flow checker working:
``` vim
let g:syntastic_javascript_eslint_exec = 'eslint'
let g:syntastic_javascript_flow_exec = 'flow'
let g:syntastic_javascript_checkers = ['eslint', 'flow']
```
2. Then eventually, it has stopped working
3. The way I have been searching for the reason:
* check `flow` starts from the shell
* check `.vimrc` settings
* `let g:syntastic_debug = 1`, got the message `...Checker javascript/flow is not available`
* google `syntastic Checker is not available`
* finally, looked at the `/syntax_checkers/javascript/flow.vim` and have found the answer

The questions:
* How often a user supposed reading the docs? (I'm really not sure about this)
* What is the best way to be in touch with the breaking changes in `Syntastic`? ([The changelog](https://github.com/vim-syntastic/syntastic/wiki/Changelog) or anything else)

**Comment by shofel** [comment]
I've tried googling `syntastic autodetection`, `syntastic autodetect` and haven't succeed. Could you please give me a hint where can I read about this?

**Comment by lcd047** [comment]
Re: breaking changes.  I _do_ try to keep incompatible changes to a minimum.  I also try to document them to `Changelog`.  However, both are best effort attempts, not guarantees.  And people already grumble all day long about me rejecting changes to default options for this very reason.

If you want to minimise the effects of my fumbling to your workflow you get the choice between (1) installing only [released versions](https://github.com/vim-syntastic/syntastic/releases) of syntastic, or (2) following development and subscribing to this issue tracker.

If you install only releases, you'd only need to check your favourite checkers still work only when a new release comes out, which is about once a year or so.

On the other hand, if you subscribe to this issue tracker you can see all changes as they happen.  In particular, changing the minimum version requirement for `flow` happened in #1954, two weeks ago.  You can also find there the reason for the change, and the history behind it.

Re: autodetection.  Validating a checker for use with syntastic can be _slow_.  Running `rubocop --version` used to take ~5 seconds on some systems.  No idea if that's still the case, but you don't want to wait that long when you run checks for the first time in a session, particularly if you don't care about `rubocop`.  Also some checkers conflict with each other (f.i. `GCC` and `AVR-GCC`).  There is no set of options that works well for everybody, which is why you're supposed to configure the list of checkers explicitly.  Not doing so will cost you time.
