### ISSUE TITLE
Syntastic check not checking errors

### ISSUE THREAD

**Issue by asknet** [vim-syntastic/syntastic#1964]
Hi,
Syntastic check not checking errors. Done Troubleshoot as per https://github.com/vim-syntastic/syntastic#faqinfo. But no success. I'm checking for java and see javac executable present in path. And by the way it's working for c filetype (gcc executable present in path). I think this is some setup issue. But unable to troubleshoot further. Please help

I'm on Windows 10 and following command gives error

:echo syntastic#util#system('echo %PATH%')  
syntastic: error: exception running system('echo %PATH%'): Vim(let):E484: Can't open file C:\Users\Parrot\AppData\Local\Temp\VIo9A1C.tmp

Figured out 'echo %path%' not working due to space after echo

**Comment by lcd047** [comment]
Please read `:h syntastic-powershell`.  Does that address your problem?

**Comment by asknet** [comment]
Strange. After couple of restarts. It's working. Thanks
