### ISSUE TITLE
Syntastic for cu file types

### ISSUE THREAD

**Issue by Badhi** [vim-syntastic/syntastic#1965]
Im trying to use syntastic for cuda syntax files with the file extension `.cu`. But when I get `SyntasticInfo`  from the `.cu` file it gives following information 

    Syntastic version: 3.8.0-9 (Vim 704, Linux)
    Info for filetype: cpp
    Global mode: active
    Filetype cpp is active
    The current file will be checked automatically
    Available checker: gcc
    Currently enabled checker: gcc

From what I understand from this log is that the Syntastic has identified `cu` file as a `cpp` file and trying to compile is with `gcc`.  Do I need to set a special configuration to enable `nvcc` for `.cu` file type?

**Comment by lcd047** [comment]
> Do I need to set a special configuration to enable `nvcc` for `.cu` file type?

Yes, it's up to you to make sure `filetype` is set properly.  Normally either Vim itself or some CUDA-related plugin should take care of that, but if `filetype` detection fails you can fix it easily:
```vim
autocmd BufNewFile,BufRead *.cu  set filetype=cuda
autocmd BufNewFile,BufRead *.cuh set filetype=cuda
```
