### ISSUE TITLE
Syntastic can't find pylint, pyflakes (after :SyntasticCheck pylint) even though in $PATH (as seen by syntastic#util#shell) 

### ISSUE THREAD

**Issue by lukelbd** [vim-syntastic/syntastic#1967]
Here's the output with `g:syntastic_debug=3` after using `:SyntasticCheck pylint`.

```
syntastic: 954.489072: g:syntastic_version = '3.8.0-24 (Vim 800, Darwin)'
syntastic: 954.489246: &shell = '/bin/bash', &shellcmdflag = '-ic' (!), &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shell
xescape = ''
syntastic: 954.489685: UpdateErrors: pylint
syntastic: 954.489971: CacheErrors: pylint
syntastic: 954.490617: g:syntastic_aggregate_errors = 0
syntastic: 954.490842: getcwd() = '/Users/ldavis'
syntastic: warning: checker pylint is not available
```

and here's the output of `echo syntastic#util#system('echo "$PATH"')`:

```syntastic: 1064.360088: system: command run in 0.077615s
/Users/ldavis:/Users/ldavis/anaconda3/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Library/TeX/texbin:/Users/ldavis:/Users/ldavis/anaco
nda3/bin:/opt/local/bin:/opt/local/sbin:/Users/ldavis/bin
```

with `which pylint` indicating a `pylint` executable in the `/Users/ldavis/anaconda3/bin` directory. Any idea what could be going on?.

**Comment by lcd047** [comment]
> `syntastic: 954.489246: &shell = '/bin/bash', &shellcmdflag = '-ic' (!),`

You changed options affecting `system()`.  This is not supported.

> Any idea what could be going on?

Please quit Vim, start it again, open a Python file, and post the output of:
```vim
:SyntasticInfo
:echo executable('pylint')
:echo syntastic#util#system('pylint --version')
```

**Comment by lukelbd** [comment]
Ah, well if that's the problem... how can I get syntastic to point to the `pylint` in an anaconda distribution? I have in my `.vimrc` the line `set shellcmdflag=-ic`, which loads my `.bashrc` and sets up my `$PATH` to point to the anaconda bin. 

Now when I run `:SyntasticInfo` I get nothing; with the `ic` flag, I was getting `executable('pylint')=1` (anaconda was in the path), but now it returns `0` (no longer in path).

**Comment by lcd047** [comment]
Please consider answering the question I asked.  Post a new issue if you still have problems after resolving this one.

**Comment by lukelbd** [comment]
I did answer your question: the second paragraph. But here is the verbatim output.

```:SyntasticInfo
Syntastic version: 3.8.0-24 (Vim 800, Darwin)
Info for filetype: vim
Global mode: active
Filetype vim is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
```:echo executable('pylint')
0```
```:echo syntastic#util#system('pylint --version')
/bin/bash: pylint: command not found````

Does the problem "getting syntastic to view a 'checker' *outside* of the default `$PATH`, and without modifying `shellcmdflag` (because that breaks it)" warrant a new thread?

**Comment by lcd047** [comment]
> Does the problem "getting syntastic to view a 'checker' *outside* of the default `$PATH`, and without modifying `shellcmdflag` (because that breaks it)" warrant a new thread?

This is described in the manual, at `:h syntastic-config-exec`: point `g:syntastic_python_pylint_exec` to the executable.  This might not be your only problem though. _shrug_
