### ISSUE TITLE
How to make it work with tern-lint?

### ISSUE THREAD

**Issue by alex-shamshurin** [vim-syntastic/syntastic#1969]
Are there any gotchas for best IDE-level javascript linting and syntax highlighting? When I run tern-lint I get out of memory errors or call stack size exceeded.

**Comment by lcd047** [comment]
What exactly gives you out of memory errors and stack size exceeded?

**Comment by alex-shamshurin** [comment]
![tern-issues](https://cloud.githubusercontent.com/assets/1595209/23281248/9abedea8-fa2d-11e6-9542-d3cc0c2b44bb.jpg)

**Comment by lcd047** [comment]
So your `tern-lint` crashes under its own weight.  Perhaps you should report that to some Tern forum?

**Comment by alex-shamshurin** [comment]
yes, of course, but may be you have some experience with it.  This is one big issue, it's not just about tags, it's about syntastic also https://github.com/ramitos/jsctags/issues/50

**Comment by lcd047** [comment]
> may be you have some experience with it.

I believe I used `tern-lint` exactly the ~10 minutes it took to write a syntastic checker for it.  Aside from some other ~5 minutes reading the docs, that's about my entire experience with it.

> This is one big issue, it's not just about tags, it's about syntastic also https://github.com/ramitos/jsctags/issues/50

What syntastic does is run `tern-lint` against your files, and parse the resulting JSON.  As far as syntastic is concerned the data involved is tiny, and munging it is completely straightforward.  Unless you can point to a case where syntastic doesn't parse `tern-lint` results correctly, there is very little help you can get here.  Sorry about that.
