### ISSUE TITLE
hitting enter on error line in list opens empty buffer of the same file

### ISSUE THREAD

**Issue by sandrodz** [vim-syntastic/syntastic#1978]
<img width="1627" alt="screen shot 2017-03-06 at 4 58 37 pm" src="https://cloud.githubusercontent.com/assets/8479569/23610940/2ea936f0-028e-11e7-898e-454b046915a6.png">

**Comment by lcd047** [comment]
So, does the file `/app/src/WeAreDe/TbcPay/TbcPayProcessor.php` exist?

**Comment by sandrodz** [comment]
@lcd047 its url inside container. So obviously syntastic doesn't see it in FS.
Any ideas?

**Comment by lcd047** [comment]
Syntastic doesn't care about the contents of your files.  What syntastic does is run linters against your files, parse their output, and show you the results in a window.  It's up to you to configure the linters to give you results that make sense...

**Comment by sandrodz** [comment]
For the record I used newest PHP_CodeSniffer-3.0.0RC4 which has flag `--basepath=/app/` I stripped off path from docker container effectively fixing this issue.
