### ISSUE TITLE
syntastic does not display warnings

### ISSUE THREAD

**Issue by sandrodz** [vim-syntastic/syntastic#1979]
In .vimrc I have:

`let g:syntastic_quiet_messages = {'level': 'warnings'}`

phpcs reports warnings:

<img width="561" alt="screen shot 2017-03-06 at 6 03 43 pm" src="https://cloud.githubusercontent.com/assets/8479569/23613112/82f3eb02-0297-11e7-95c5-42f8b6149471.png">

but syntastic still doesn't display warnings:

<img width="1135" alt="screen shot 2017-03-06 at 6 03 56 pm" src="https://cloud.githubusercontent.com/assets/8479569/23613151/a8d0ed02-0297-11e7-9c45-69cf6d2f4d1f.png">

**Comment by lcd047** [comment]
You tell syntastic to quiet warnings then you ask why warnings are not displayed?

**Comment by sandrodz** [comment]
@lcd047 its not clear which way that var goes. So which level displays all errors+warnings?

**Comment by lcd047** [comment]
All messages produced by the liter are displayed by default.  If you set `quiet_messages` some of these messages are filtered out.

**Comment by sandrodz** [comment]
@lcd047 strange, so because it didn't display warnings for me out of the box, I searched around for setting like `g:syntastic_quiet_messages `

anyways, removing that line, I still don't get warnings.

**Comment by sandrodz** [comment]
in fact problem was `let g:syntastic_php_phpcs_args = '--standard=PSR2 -n'`

-n flag blocks warnings.
