### ISSUE TITLE
javascript checker not working

### ISSUE THREAD

**Issue by argaen** [vim-syntastic/syntastic#1982]
Hi, I've been trying for a while to have eslint working as the checker but no luck. I already tried other issues but its not exactly the same.

Debug output:

```
"client/src/App.js" 30L, 651C written
syntastic: 9.694507: g:syntastic_version = '3.8.0-26 (Vim 704, Darwin, GUI)'
syntastic: 9.694673: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 9.695213: UpdateErrors (auto): default checkers
syntastic: 9.695678: CacheErrors: default checkers
syntastic: 9.696351: g:syntastic_aggregate_errors = 0
syntastic: 9.696550: getcwd() = '/Users/manuelmiranda/Projects/hotelsconnect'
Error detected while processing function <SNR>31_BufWritePostHook[4]..<SNR>31_UpdateErrors[15]..<SNR>31_CacheErrors[31]..23[7]..SyntaxCheckers_javascript_eslint_IsAvailable:
line    5:
E117: Unknown function: syntastic#util#getVersion
E15: Invalid expression: syntastic#util#getVersion(self.getExecEscaped() . ' --version')
line    6:
E121: Undefined variable: ver
E116: Invalid arguments for function 21
line    8:
E121: Undefined variable: ver
E116: Invalid arguments for function syntastic#util#versionIsAtLeast(ver, [0, 1])
E15: Invalid expression: syntastic#util#versionIsAtLeast(ver, [0, 1])
syntastic: 9.719251: CacheErrors: Checker javascript/eslint is not available
syntastic: 9.719535: CacheErrors: no checkers available for javascript
syntastic: 9.719681: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
```

variable set: `let g:syntastic_javascript_checkers = ['eslint',]`

eslint is in my path and I can execute it in the terminal. Same happens with jshint... any ideas?

**Comment by lcd047** [comment]
This looks like a broken installation of syntastic and / or a misconfigured plugin manager.  What version of Vim are you using, what plugin manager, and how did you install syntastic?

**Comment by argaen** [comment]
It works fine with python checkers that's why I would discard broken installation... I'm up to date with the repo.

vim version is 7.4 and I installed syntastic with Vundle

**Comment by lcd047** [comment]
Well, your error message says line 5 in function `SyntaxCheckers_javascript_eslint_IsAvailable()` calls `syntastic#util#getVersion`:

> `Error detected while processing function <SNR>31_BufWritePostHook[4]..<SNR>31_UpdateErrors> [15]..<SNR>31_CacheErrors[31]..23[7]..SyntaxCheckers_javascript_eslint_IsAvailable:`
> `line    5:`
> `E117: Unknown function: syntastic#util#getVersion`

As you can [see][isavailable] however, line 5 in said function makes no reference to `syntastic#util#getVersion`.  In fact `syntastic#util#getVersion()` has been removed a long time ago.

For some reasons syntastic finds an older version of a file `syntax_checkers/javascript/eslint.vim` before the current one.  That isn't a correct installation of syntastic. _shrug_

Run `:scriptnames` to find out what files are currently loaded.

[isavailable]: https://github.com/vim-syntastic/syntastic/blob/48e8b0e9d2721f608fd1d1157c9388b2626cbddf/syntax_checkers/javascript/eslint.vim#L28-L37

**Comment by argaen** [comment]
Appart from the normal installation with Vundle, I had a folder `syntax_checkers` under `.vim` folder and that was the one being used 😓. Removed and reinstalled syntastic just in case and works. Sorry for the noise
