### ISSUE TITLE
is there a way to define different cs for different projects of the same filetype?

### ISSUE THREAD

**Issue by sandrodz** [vim-syntastic/syntastic#1983]
In some projects I use psr2 and in some wpcs (WordPress). Filetype for both is .php.

phpcs provides both psr2 and wpcs, what are my options for syntastic to differentiate between these two?

I've seen this issue #1180

**Comment by lcd047** [comment]
Set `b:syntastic_php_phpcs_args` from `autocmd`s on `BufRead` matching your projects.  Not exactly painless, but that's the Vim way of doing it. _shrug_

**Comment by sandrodz** [comment]
What do you mean by "not exactly painless" ?

**Comment by lcd047** [comment]
Do you enjoy writing `autocmd`s?  Personally, I don't.
