### ISSUE TITLE
Cannot use eslint and flow checkers at the same time

### ISSUE THREAD

**Issue by sdeleon28** [vim-syntastic/syntastic#1985]
I'm trying to use ESLint and Flow at the same time to check the syntax of a react-native project. However, syntastic will only use the fist checker declared in `g:syntastic_javascript_checkers`.

My checkers config looks like this:

```vim
let g:syntastic_javascript_checkers = ['eslint', 'flow']
```

In that case, only ESLint errors are displayed. If I flip the positions, I only get Flow errors but no ESLint. If I only list one of them, it works without problems.

Is this a bug or am I missing some config in order to get them both working at the same time?

**Comment by lcd047** [comment]
Try reading `:h 'syntastic_aggregate_errors'`.

**Comment by sdeleon28** [comment]
Setting `let g:syntastic_aggregate_errors = 1` fixed it. Thanks!
