### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by brainscience** [vim-syntastic/syntastic#1987]
I'm using windows 10 and a powershell shell. I'm running in a virtual python environment using python 3.6. Installed Syntastic using Pathogen. My syntax checker is pyflakes which works from the Powershell prompt and from within Vim with a !pyflakes %.  When running syntastic all I get is a bunch of garbage characters. Any thoughts or actions?

**Comment by lcd047** [comment]
Please read `:h syntastic-powershell`.

**Comment by brainscience** [comment]
That fixed it. Thanks for the quick reply.
