### ISSUE TITLE
Eslint is not invoked

### ISSUE THREAD

**Issue by barothardik** [vim-syntastic/syntastic#1988]
Do not understand why the eslint checker is not opening up.

Installed eslint (/usr/local/bin/eslint)
==========================
sudo npm install -g eslint (yeah I have to run sudo for whatever reason)

:echo syntastic#util#system('echo "$PATH"')
==================================
~/.rbenv/shims:/usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

.vimrc looks like
============

execute pathogen#infect()
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_debug = 25

let g:syntastic_javascript_checkers = ['eslint']

Here is the output for :SyntasticInfo javascript for debug=25
=============================================

syntastic: 0.027112: autocmd: BufReadPost, buffer 1 = 'somefile.js'
syntastic: 0.027318: autocmd: BufWinEnter, buffer 1 = 'somefile.js', &buftype = ''
syntastic: 0.027512: autocmd: BufEnter, buffer 1 = 'somefile.js', &buftype = ''
syntastic: 0.027705: autocmd: VimEnter, buffer 1 = 'somefile.js', &buftype = ''
syntastic: 1.228887: g:syntastic_version = '3.8.0-33 (Vim 703, Darwin)'
syntastic: 1.245110: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0
syntastic: 1.245804: g:syntastic_aggregate_errors = 0
syntastic: 1.245804: g:syntastic_always_populate_loc_list = 1
syntastic: 1.245804: g:syntastic_auto_jump = 0
syntastic: 1.245804: g:syntastic_auto_loc_list = 1
syntastic: 1.245804: g:syntastic_check_on_open = 1
syntastic: 1.245804: g:syntastic_check_on_wq = 1
syntastic: 1.245804: g:syntastic_cursor_columns = 1
syntastic: 1.245804: g:syntastic_debug = 25
syntastic: 1.245804: g:syntastic_echo_current_error = 1
syntastic: 1.245804: g:syntastic_enable_balloons = 0
syntastic: 1.245804: g:syntastic_enable_highlighting = 1
syntastic: 1.245804: g:syntastic_enable_signs = 1
syntastic: 1.245804: g:syntastic_error_symbol = '>>'
syntastic: 1.245804: g:syntastic_exit_checks = 1
syntastic: 1.245804: g:syntastic_filetype_map = {}
syntastic: 1.245804: g:syntastic_full_redraws = 1
syntastic: 1.245804: g:syntastic_id_checkers = 1
syntastic: 1.245804: g:syntastic_ignore_extensions = '\c\v^([gx]?z|lzma|bz2)$'
syntastic: 1.245804: g:syntastic_ignore_files = []
syntastic: 1.245804: g:syntastic_loc_list_height = 10
syntastic: 1.245804: g:syntastic_nested_autocommands = 0
syntastic: 1.245804: g:syntastic_quiet_messages = {}
syntastic: 1.245804: g:syntastic_reuse_loc_lists = 1
syntastic: 1.245804: g:syntastic_shell = '/bin/bash'
syntastic: 1.245804: g:syntastic_sort_aggregated_errors = 1
syntastic: 1.245804: g:syntastic_stl_format = '[Syntax: line:%F (%t)]'
syntastic: 1.245804: g:syntastic_style_error_symbol = 'S>'
syntastic: 1.245804: g:syntastic_style_warning_symbol = 'S>'
syntastic: 1.245804: g:syntastic_warning_symbol = '>>'
syntastic: 1.247625: UpdateErrors (auto): default checkers
syntastic: 1.248783: CacheErrors: default checkers
syntastic: 1.250864: g:syntastic_aggregate_errors = 0
syntastic: 1.251255: getcwd() = '/Users/hardik.barot/emberProjects/map-ui-ember'
syntastic: 1.251585: CacheErrors: no checkers available for

Here is the output for debug = 0
========================
Syntastic version: 3.8.0-33 (Vim 703, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
Available checkers: eslint jslint
Currently enabled checker: eslint

**Comment by lcd047** [comment]
Please explain what did you do, what did you expect to happen, and what happened instead.

**Comment by barothardik** [comment]
I opened VIM and removed a semicolon and saved it.
Given,
g:syntastic_auto_loc_list = 1
g:syntastic_check_on_open = 1
g:syntastic_check_on_wq = 1,

I was expecting the error to show up on the location in the file but that did not come up.
I next set the debug to a higher number and saw :mes. The output on the last line said
"CacheErrors: no checkers available for"

So I believe the checker did not get invoked because.
Because looking at other issues on github, most of them have this line as
"CacheErrors: Invoked ....."

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output.

**Comment by barothardik** [comment]
syntastic: 0.032159: g:syntastic_version = '3.8.0-33 (Vim 703, Darwin)'
syntastic: 0.032276: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &
autochdir = 0
syntastic: 0.032654: UpdateErrors (auto): default checkers
syntastic: 0.033163: CacheErrors: default checkers
syntastic: 0.033910: g:syntastic_aggregate_errors = 0
syntastic: 0.034091: getcwd() = '/Users/hardik.barot/emberProjects/map-ui-ember'
syntastic: 0.034352: CacheErrors: no checkers available for
syntastic: 0.034423: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
Syntastic version: 3.8.0-33 (Vim 703, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
syntastic: 15.500516: system: command run in 1.517380s
Available checkers: eslint jslint
Currently enabled checker: eslint
syntastic: 15.505921: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '',
&autochdir = 0

**Comment by barothardik** [comment]
To add some more information, eslint is available as part of the project under node_modules and also available globally under /usr/local/bin/eslint.
Do I need to set the "g:syntastic_javascript_eslint_exec" ? (I believe I do not have to since,
"Currently enabled checker: eslint")

**Comment by lcd047** [comment]
Whaty happens if you run `:SyntasticCheck`?

**Comment by barothardik** [comment]
syntastic: 0.026422: g:syntastic_version = '3.8.0-33 (Vim 703, Darwin)'
syntastic: 0.026537: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0
syntastic: 0.026909: UpdateErrors (auto): default checkers
syntastic: 0.027383: CacheErrors: default checkers
syntastic: 0.028099: g:syntastic_aggregate_errors = 0
syntastic: 0.028274: getcwd() = '/Users/hardik.barot/emberProjects/map-ui-ember'
syntastic: 0.028543: CacheErrors: no checkers available for
syntastic: 0.028617: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
syntastic: 4.084590: g:syntastic_version = '3.8.0-33 (Vim 703, Darwin)'
syntastic: 4.084765: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0
syntastic: 4.085192: UpdateErrors: default checkers
syntastic: 4.086145: CacheErrors: default checkers
syntastic: 4.087413: g:syntastic_aggregate_errors = 0
syntastic: 4.087635: getcwd() = '/Users/hardik.barot/emberProjects/map-ui-ember'
syntastic: 4.087961: CacheErrors: no checkers available for
syntastic: 4.088055: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}

**Comment by lcd047** [comment]
Sadly, that doesn't make sense.  Can you reproduce the problem with all other plugins disabled?  What is the output of `:scriptnames` after you run `:SyntasticCheck` with all other plugins disabled?  You seem to be running a very old version of Vim, can you reproduce the problem with a more recent one?

**Comment by barothardik** [comment]
I do not have a lot of plugins. Here is the output of :scriptnames
Meanwhile I am going to install vim 8.0 and see what happens.

  1: /usr/share/vim/vimrc
  2: /Users/hardik.barot/.vimrc
  3: /Users/hardik.barot/.vim/autoload/pathogen.vim
  4: /Users/hardik.barot/.vim/plugin/editorconfig.vim
  5: /Users/hardik.barot/.vim/bundle/syntastic/plugin/syntastic/autoloclist.vim
  6: /Users/hardik.barot/.vim/bundle/syntastic/plugin/syntastic/balloons.vim
  7: /Users/hardik.barot/.vim/bundle/syntastic/plugin/syntastic/checker.vim
  8: /Users/hardik.barot/.vim/bundle/syntastic/plugin/syntastic/cursor.vim
  9: /Users/hardik.barot/.vim/bundle/syntastic/plugin/syntastic/highlighting.vim
 10: /Users/hardik.barot/.vim/bundle/syntastic/plugin/syntastic/loclist.vim
 11: /Users/hardik.barot/.vim/bundle/syntastic/plugin/syntastic/modemap.vim
 12: /Users/hardik.barot/.vim/bundle/syntastic/plugin/syntastic/notifiers.vim
 13: /Users/hardik.barot/.vim/bundle/syntastic/plugin/syntastic/registry.vim
 14: /Users/hardik.barot/.vim/bundle/syntastic/plugin/syntastic/signs.vim
 15: /Users/hardik.barot/.vim/bundle/syntastic/plugin/syntastic.vim
 16: /Users/hardik.barot/.vim/bundle/syntastic/autoload/syntastic/log.vim
 17: /Users/hardik.barot/.vim/bundle/syntastic/autoload/syntastic/util.vim
 18: /usr/share/vim/vim73/plugin/getscriptPlugin.vim
 19: /usr/share/vim/vim73/plugin/gzip.vim
 20: /usr/share/vim/vim73/plugin/matchparen.vim
 21: /usr/share/vim/vim73/plugin/netrwPlugin.vim
 22: /usr/share/vim/vim73/plugin/rrhelper.vim
 23: /usr/share/vim/vim73/plugin/spellfile.vim
 24: /usr/share/vim/vim73/plugin/tarPlugin.vim
 25: /usr/share/vim/vim73/plugin/tohtml.vim
 26: /usr/share/vim/vim73/plugin/vimballPlugin.vim
 27: /usr/share/vim/vim73/plugin/zipPlugin.vim
 28: /Users/hardik.barot/.vim/autoload/editorconfig.vim

**Comment by barothardik** [comment]
Really interesting what happened. I was trying to add some colours to my vim. As part of that I added "syntax on" to my .vimrc and the checker started working.

**Comment by lcd047** [comment]
This shouldn't be relevant to syntastic.
