### ISSUE TITLE
Shadow declaration warnings giving out as errors

### ISSUE THREAD

**Issue by Badhi** [vim-syntastic/syntastic#1991]
Tried the following code with syntastic

    int a;
    
    int main()
    {
    int a;
              
      a = 5;
    }

Syntastic recongnize the shadowing of variable a as an error though it should be showed as a warning

![image](https://cloud.githubusercontent.com/assets/10277051/24236244/19642b56-0fc7-11e7-9c74-452fa9a611cf.png)

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output.

**Comment by Badhi** [comment]
"globalTest.cpp" 9L, 55C
    "globalTest.cpp" 9L, 55C written
    syntastic: 1.116514: g:syntastic_version = '3.8.0-24 (Vim 704, Linux)'
    syntastic: 1.116639: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
    syntastic: 1.117016: UpdateErrors (auto): default checkers
    syntastic: 1.117323: CacheErrors: default checkers
    syntastic: 1.117827: g:syntastic_aggregate_errors = 0
    syntastic: 1.117976: getcwd() = '/home/hwac-bhashithaa/TestProgs_hwac'
    syntastic: 1.125656: CacheErrors: Invoking checker: cpp/gcc
    syntastic: 1.127060: SyntasticMake: called with options: {'postprocess': [], 'errorformat': '%-G%f:%s:,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%f:%l: %m', 'makeprg': '''g++'' -x c++ -fsyntax-only -DNO_SOCI -DNO_CUB -D
    SPLIT_PHASE_CALC -std=c++11 -Wshadow -Wpointer-arith -Wcast-qual -Wmaybe-uninitialized  -I. -I.. -Iinclude -Iincludes -I../include -I../includes -I/home/hwac-bhashithaa/repositories/ccp/ccp_application/app_base_HWACMRisk/src/libMRISK/include/ -I/usr/lib64/R/library/RInsid
    e/include -I/home/hwac-bhashithaa/repositories/ccp/ccp_application/test_base_TestAPIHWACMRisk/src/TestMRISK/src/ -I/home/hwac-bhashithaa/repositories/ccp/ccp_application/test_base_TestAPIHWACMRisk/src/TestMRISK/src/Mock -I/home/hwac-bhashithaa/repositories/ccp/ccp_applica
    tion/test_base_TestAPIHWACMRisk/src/TestMRISK/src/CsvUtils -I/usr/lib64/R/library/Rcpp/include -I/usr/lib64/R/include -I/home/hwac-bhashithaa/repositories/ccp/ccp_application/test_base_TestHWACMRisk/src/TestMRISK/include/   globalTest.cpp'}
    syntastic: 1.148460: system: command run in 0.021090s
    syntastic: 1.148563: checker output: ['globalTest.cpp: In function ‘int main()’:', 'globalTest.cpp:6:9: warning: declaration of ‘a’ shadows a global declaration [-Wshadow]', '     int a;', '         ^', 'globalTest.cpp:1:5: note: shadowed declaration is here', ' int a;',
    '     ^', '']
    syntastic: 1.149018: raw loclist: [{'lnum': 6, 'bufnr': 1, 'col': 9, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'w', 'pattern': '', 'text': 'declaration of ‘a’ shadows a global declaration [-Wshadow]'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'typ
    e': '', 'pattern': '', 'text': '     int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '         ^'}, {'lnum': 1, 'bufnr': 1, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'note:
     shadowed declaration is here'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ' int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '     ^'}, {'lnum': 0,
    'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
    syntastic: 1.149277: getLocList: checker cpp/gcc returned 0
    syntastic: 1.149365: cpp/gcc raw: [{'lnum': 6, 'bufnr': 1, 'col': 9, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'w', 'pattern': '', 'text': 'declaration of ‘a’ shadows a global declaration [-Wshadow]'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'typ
    e': '', 'pattern': '', 'text': '     int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '         ^'}, {'lnum': 1, 'bufnr': 1, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'note:
     shadowed declaration is here'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ' int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '     ^'}, {'lnum': 0,
    'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
    syntastic: 1.149607: quiet_messages filter: {}
    syntastic: 1.149690: getLocList: checker cpp/gcc run in 0.023953s
    syntastic: 1.149963: aggregated: {'_sorted': 0, '_name': 'gcc (cpp)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 6, 'bufnr': 1, 'col': 9, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'w', 'pattern': '', 'text': 'declaration of ‘a’ shadows a global declaration [-Wsha
    dow]'}, {'lnum': 1, 'bufnr': 1, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'E', 'pattern': '', 'text': 'note: shadowed declaration is here'}]}

**Comment by Badhi** [comment]
"globalTest.cpp" 9L, 55C
    "globalTest.cpp" 9L, 55C written
    syntastic: 1.116514: g:syntastic_version = '3.8.0-24 (Vim 704, Linux)'
    syntastic: 1.116639: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
    syntastic: 1.117016: UpdateErrors (auto): default checkers
    syntastic: 1.117323: CacheErrors: default checkers
    syntastic: 1.117827: g:syntastic_aggregate_errors = 0
    syntastic: 1.117976: getcwd() = '/home/****'
    syntastic: 1.125656: CacheErrors: Invoking checker: cpp/gcc
    syntastic: 1.127060: SyntasticMake: called with options: {'postprocess': [], 'errorformat': '%-G%f:%s:,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%f:%l: %m', 'makeprg': '''g++'' -x c++ -fsyntax-only  globalTest.cpp'}
    syntastic: 1.148460: system: command run in 0.021090s
    syntastic: 1.148563: checker output: ['globalTest.cpp: In function ‘int main()’:', 'globalTest.cpp:6:9: warning: declaration of ‘a’ shadows a global declaration [-Wshadow]', '     int a;', '         ^', 'globalTest.cpp:1:5: note: shadowed declaration is here', ' int a;',
    '     ^', '']
    syntastic: 1.149018: raw loclist: [{'lnum': 6, 'bufnr': 1, 'col': 9, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'w', 'pattern': '', 'text': 'declaration of ‘a’ shadows a global declaration [-Wshadow]'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'typ
    e': '', 'pattern': '', 'text': '     int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '         ^'}, {'lnum': 1, 'bufnr': 1, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'note:
     shadowed declaration is here'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ' int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '     ^'}, {'lnum': 0,
    'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
    syntastic: 1.149277: getLocList: checker cpp/gcc returned 0
    syntastic: 1.149365: cpp/gcc raw: [{'lnum': 6, 'bufnr': 1, 'col': 9, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'w', 'pattern': '', 'text': 'declaration of ‘a’ shadows a global declaration [-Wshadow]'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'typ
    e': '', 'pattern': '', 'text': '     int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '         ^'}, {'lnum': 1, 'bufnr': 1, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'note:
     shadowed declaration is here'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ' int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '     ^'}, {'lnum': 0,
    'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
    syntastic: 1.149607: quiet_messages filter: {}
    syntastic: 1.149690: getLocList: checker cpp/gcc run in 0.023953s
    syntastic: 1.149963: aggregated: {'_sorted': 0, '_name': 'gcc (cpp)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 6, 'bufnr': 1, 'col': 9, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'w', 'pattern': '', 'text': 'declaration of ‘a’ shadows a global declaration [-Wsha
    dow]'}, {'lnum': 1, 'bufnr': 1, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'E', 'pattern': '', 'text': 'note: shadowed declaration is here'}]}

**Comment by Badhi** [comment]
"globalTest.cpp" 9L, 55C
    "globalTest.cpp" 9L, 55C written
    syntastic: 1.116514: g:syntastic_version = '3.8.0-24 (Vim 704, Linux)'
    syntastic: 1.116639: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
    syntastic: 1.117016: UpdateErrors (auto): default checkers
    syntastic: 1.117323: CacheErrors: default checkers
    syntastic: 1.117827: g:syntastic_aggregate_errors = 0
    syntastic: 1.117976: getcwd() = '/home/****'
    syntastic: 1.125656: CacheErrors: Invoking checker: cpp/gcc
    syntastic: 1.127060: SyntasticMake: called with options: {'postprocess': [], 'errorformat': '%-G%f:%s:,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%f:%l: %m', 'makeprg': '''g++'' -x c++ -fsyntax-only  globalTest.cpp'}
    syntastic: 1.148460: system: command run in 0.021090s
    syntastic: 1.148563: checker output: ['globalTest.cpp: In function ‘int main()’:', 'globalTest.cpp:6:9: warning: declaration of ‘a’ shadows a global declaration [-Wshadow]', '     int a;', '         ^', 'globalTest.cpp:1:5: note: shadowed declaration is here', ' int a;',
    '     ^', '']
    syntastic: 1.149018: raw loclist: [{'lnum': 6, 'bufnr': 1, 'col': 9, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'w', 'pattern': '', 'text': 'declaration of ‘a’ shadows a global declaration [-Wshadow]'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'typ
    e': '', 'pattern': '', 'text': '     int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '         ^'}, {'lnum': 1, 'bufnr': 1, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'note:
     shadowed declaration is here'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ' int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '     ^'}, {'lnum': 0,
    'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
    syntastic: 1.149277: getLocList: checker cpp/gcc returned 0
    syntastic: 1.149365: cpp/gcc raw: [{'lnum': 6, 'bufnr': 1, 'col': 9, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'w', 'pattern': '', 'text': 'declaration of ‘a’ shadows a global declaration [-Wshadow]'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'typ
    e': '', 'pattern': '', 'text': '     int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '         ^'}, {'lnum': 1, 'bufnr': 1, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'note:
     shadowed declaration is here'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ' int a;'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '     ^'}, {'lnum': 0,
    'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
    syntastic: 1.149607: quiet_messages filter: {}
    syntastic: 1.149690: getLocList: checker cpp/gcc run in 0.023953s
    syntastic: 1.149963: aggregated: {'_sorted': 0, '_name': 'gcc (cpp)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 6, 'bufnr': 1, 'col': 9, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'w', 'pattern': '', 'text': 'declaration of ‘a’ shadows a global declaration [-Wsha
    dow]'}, {'lnum': 1, 'bufnr': 1, 'col': 5, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'E', 'pattern': '', 'text': 'note: shadowed declaration is here'}]}

**Comment by lcd047** [comment]
Right: syntastic can only handle `error` and `warning` messages, any other error levels are assimilated to errors.  For the `cpp/gcc` checker you can "fix" that by setting `g:syntastic_cpp_errorformat`, but this is not a supported configuration:
```vim
let g:syntastic_cpp_errorformat =
    \     '%-G%f:%s:,' .
    \     '%f:%l:%c: %trror: %m,' .
    \     '%f:%l:%c: %tarning: %m,' .
    \     '%f:%l:%c: %m,' .
    \     '%f:%l: %trror: %m,' .
    \     '%f:%l: %tarning: %m,' .
    \     '%W%f:%l: note: %m,' .
    \     '%W%f:%l: info: %m,' .
    \     '%f:%l: %m'
```
