### ISSUE TITLE
Define Specific Colors

### ISSUE THREAD

**Issue by Hacksaurus** [vim-syntastic/syntastic#1998]
This isn't really and **issue** and more of a personal question...

1. I want the bg of ">>" to be the same color of the number line
2. I also want, "[Syntax: line:4 (1)]" to also have the same background color as the one to the right
3. The text in the VERY bottom is also very light... How can I manually change that? 

![screenshot_2017-04-04_20-14-09](https://cloud.githubusercontent.com/assets/24832107/24688706/8d89746a-1976-11e7-9153-e4646a2e82d4.png)

Thanks for any help!

**Comment by lcd047** [comment]
For signs, a quick search seems to [imply][SO] you're looking for the `SignColumn` group.

The `statusline` color is just standard stuff.  Where the [recommended settings][recommended] tell you to do this:

```vim
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
```

you just need to replace it with some other highlight group, or just omit the highlighting altogether.  See `:h 'stl'` for the gory details.

As for the light background, that's the cursor line in the quickfix window.  You need to dig around to find it, but [apparently][vimuse] it's the `Search` group.

I'm afraid my knowledge about Vim doesn't quite reach to these particular corners.  You might have better luck asking on some Vim forum. _shrug_

[SO]:  http://stackoverflow.com/questions/15277241/changing-vim-gutter-color
[recommended]: https://github.com/vim-syntastic/syntastic#settings
[vimuse]: https://groups.google.com/forum/#!topic/vim_use/sksBNn0QA1Q

**Comment by Hacksaurus** [comment]
Ah ok... Also offtopic question Every time I make a tab in a python file it gets converted into spaces, but every other file type it doesn't... How do I disable that?

**Comment by lcd047** [comment]
> Also offtopic question Every time I make a tab in a python file it gets converted into spaces, but every other file type it doesn't... How do I disable that?

Sadly, debugging people's configurations is not a service I offer.  If I ever gave you the impression I do, I'm so very sorry, that was never my intention.

> Another question, how does have NO text in the lwindow... So it won't print out "[Location List] :SyntasticCheck python (python)"

I can't really parse what you're asking here, but my approximation would be: that isn't possible, the status line of the error window is controlled by Vim, not by syntastic.

**Comment by Hacksaurus** [comment]
I figured out how to do the last part... And I thought the tabs python thing was something that syntastic did... Thanks for the help.
