### ISSUE TITLE
Send arguments to gometalinter on save?

### ISSUE THREAD

**Issue by shadyabhi** [vim-syntastic/syntastic#2002]
Hi, 

I would like to send `--fast` argument to gometalinter when it gets called. How can I do that using `.vimrc`?

For now, I've directly modified the `gometalinter.vim` like this.

```
  function! SyntaxCheckers_go_gometalinter_GetLocList() dict
      let makeprg = self.makeprgBuild({
          \ 'args': '-t --fast',
          \ 'fname': syntastic#util#shexpand('%:p:h') })
```

**Comment by lcd047** [comment]
A poorly understood fact about syntastic is that you can save a lot of time just by spending a few minutes reading the manual.  In this particular case, `:h syntastic-go-gometalinter` points you to `:h syntastic-config-makeprg`.
