### ISSUE TITLE
syntastic can`t identify localtime_r

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [vim-syntastic/syntastic#2005]
In my code,I use localtime_r instead of localtime to adjust the mulitithread environment.But syntastic always  
think of it a error,and the error message is implicit declaration of function 'localtime_r' is invalid in C99 (FixIt).The funciton localtime_r decalare in time.h,and in my code ,I have included time.h.

**Comment by lcd047** [comment]
What checker produces this message?

**Comment by Keepmoving-ZXY** [comment]
In my .vimrc, let g:syntastic_c_checkers=['gcc']

**Comment by lcd047** [comment]
> In my .vimrc, let g:syntastic_c_checkers=['gcc']

Excellent.  Then all you need to do is read the manual (`:h syntastic-c-gcc`), and configure syntastic to pass the apropriate flags to `gcc`.  You can enable debugging (`:h syntastic-debug`) to see the command line formed by syntastic.

**Comment by Keepmoving-ZXY** [comment]
ok,thank you.
