### ISSUE TITLE
How to set -I option (g++)

### ISSUE THREAD

**Issue by xahon** [vim-syntastic/syntastic#2012]
Cannot set sources path in syntastic. Tried let `g:syntastic_cpp_config_file = '.syntastic_cpp_config'`  
All my sources are in `lib` folder and i compile with `-I lib` option, so my config file should look like
`.syntastic_cpp_config`:
        `-Ilib/`

`.syntastic_cpp_config` is in my project root
But `#include`s not recognizing

**Comment by lcd047** [comment]
1. From `:h syntastic-config-format`:

> If the path following an `-I` is relative, it's treated as being relative to the current configuration file, and is replaced by the corresponding absolute path.

So, is the file `.syntastic_cpp_config` in the same directory as the `lib` you want to add to the include path?

2. The usual convention is to put header files in `include` and libraries in `lib`.  Just saying.

3. To see the command line constructed by syntastic you can enable debugging (`:h syntastic-debug`).

**Comment by sirspinach** [comment]
I actually happen to need the `-l` option, because I want to load libcurl via something like`gcc main.cpp ... -lcurl`.
In this case order matters -- that is, -lcurl needs to come after main.cpp.

When I run `:SyntasticCheck` in debug mode, I get the following:
```
{'postprocess': [], 'errorformat': '%-G%f:%s:,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%f:%l
: %m', 'makeprg': '''g++-7'' -x c++ -fsyntax-only  -std=c++17 -L/home/ubuntu/openstackapi/third-party/cpr/build/lib -I/home/ubuntu/openstackapi/third-party/rapidjson/include -lcpr -lcurl -I. -I.. -Iinclud
e -Iincludes -I../include -I../includes   lbaas.cc'}
```

Anyone know how I can put the `-lcurl` at the end of the command?

**Comment by lcd047** [comment]
@sirspinach It isn't currently possible to add options after the filename for the `gcc` checker (and other checkers that use the `syntastic#c#GetLocList()` framework).  The fact that nobody asked for it yet should be a hint that such a feature is not actually needed: `-lcurl` is a linker option, it has no effect after `-fsyntax-only`.

**Comment by sirspinach** [comment]
Ah, I see. Thanks!
