### ISSUE TITLE
Syntastic Error When Opening Vim

### ISSUE THREAD

**Issue by HabbaRazzer** [vim-syntastic/syntastic#2013]
Running into the following issue whenever I start vim:
```
syntastic: error: exception running system('uname'): Vim(let):E484: Can't open file /tmp/vDxlRus/0
Error detected while processing function syntastic#util#system:
line   19:
E121: Undefined variable: g:_SYNTASTIC_DEBUG_CHECKERS
E116: Invalid arguments for function syntastic#log#debug
```

System:
`3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64`

Vim 7.4

I had just recently installed Syntastic via Pathogen. Let me know what other information I can provide to help!

**Comment by lcd047** [comment]
Your `system()` function in Vim is broken.  It's up to you to find out how or why; that has nothing to do with syntastic.  My first guess would be that you messed up some of the variables affecting shell running (`shell`, `shellcmdflag`, `shellquote` etc.).

**Comment by HabbaRazzer** [comment]
Ok, thank you!

**Comment by HabbaRazzer** [comment]
Solved - shell variable was set to fish. Apparently fish doesn't work well with Syntastic. Fix was to set shell to bash.
`:set shell=/usr/bin/bash`

**Comment by lcd047** [comment]
Believe it or not, this is documented: `:h syntastic-fish`.

**Comment by HabbaRazzer** [comment]
Thanks. In the future I be sure to read through documentation before I post an issue.
