### ISSUE TITLE
javascript/jshint: getVersion: 'jshint --version': ['']

### ISSUE THREAD

**Issue by jZhangTk** [vim-syntastic/syntastic#2014]
jshint stopped working recently, but I'm not sure what changed (updates?). It now displays error `syntastic: error: checker javascript/jshint: can't parse version string (abnormal termination?)`. Did a bit debugging, it seems that jshint is not recognized within vim.

I'm using `Syntastic version: 3.8.0-51` and `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 19 2017 03:58:09)` with osx.

With `let g:syntastic_debug = 33`
```
syntastic: 0.846101: g:syntastic_version = '3.8.0-51 (Vim 800, Darwin, GUI)'
syntastic: 0.846284: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 0.847168: UpdateErrors (auto): default checkers
syntastic: 0.847675: CacheErrors: default checkers
syntastic: 0.848466: g:syntastic_aggregate_errors = 0
syntastic: 0.848652: $TERM = 'xterm-256color'
syntastic: 0.848770: $TMPDIR = '/var/folders/x7/_shskyts6w966_8kgq512jfh0000gn/T/'
syntastic: 0.848899: $PATH = '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
syntastic: 0.849037: getcwd() = '/Users/ac/Developer/test'
syntastic: 1.177190: system: command run in 0.309148s
syntastic: 1.177411: javascript/jshint: getVersion: 'jshint --version': ['']
syntastic: error: checker output:
syntastic: error: checker javascript/jshint: can't parse version string (abnormal termination?)
syntastic: 1.385977: CacheErrors: Checker javascript/jshint is not available
syntastic: 1.386419: CacheErrors: Checker javascript/jslint is not available
syntastic: 1.386657: CacheErrors: no checkers available for javascript
```

vimrc syntastic settings
```
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 2
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
```

Here's what I tried.
`jshint --version` works properly in terminal.
`:JSHint` works properly in vim.
`:echo system('jshint --version')` returns nothing in vim.
`:echo system('/usr/local/lib/node_modules/jshint/bin/jshint --version')` returns nothing in vim.
`:echo system('node --version')` returns properly in vim.
`:echo $PATH` returns `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

Adding below lines to vimrc didn't help.
```
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_javascript_jshint_exec = '/usr/local/bin/jshint'
```

I also tried reinstall almost everything, including node, npm, jshint, all vim plugins (jshint.vim, syntastic), still no luck (in osx). I also did the same setup in "Bash on Ubuntu on Windows", same issue. However, the same setup in Windows 10, it worked flawlessly.

**Comment by lcd047** [comment]
> `:echo system('jshint --version')` returns nothing in vim.
> `:echo system('/usr/local/lib/node_modules/jshint/bin/jshint --version')` returns nothing in vim.

Well, you need to find out why this happens and fix it.  It has nothing to do with syntastic, it's between your shell, Vim, `node`, and `jshint`.  Once you fix it syntastic should start working again (or at least it should solve the "can't parse version string" problem). _shrug_

**Comment by jZhangTk** [comment]
I'm not saying it is syntastic's fault. But how can I find out the root cause of the issue? They all run perfectly without syntastic, and it was working fine a few days ago. I don't think I changed anything related to shell, Vim, node, and jshint (other than update the packages).

I need a way to figure out what's wrong with it. Please let me know how. Thanks.

**Comment by lcd047** [comment]
> But how can I find out the root cause of the issue?

I wouldn't know.  Really.  Why do you expect me to be able to figure out what happens on your machine?  Syntastic doesn't even come into play here.  My educated guess would be the problem has something to do with `node`, but the truth is I have absolutely no idea.

> They all run perfectly without syntastic

No, they don't.  `:echo system('jshint --version')` should not return an empty string.  Your `system()` in Vim is broken, for whatever reason.  Syntastic needs a working `system()` to function.  Like I said, fix it, and syntastic should start working again.

> I need a way to figure out what's wrong with it. Please let me know how.

Sorry, but I'm not a fairy.  I have no idea what your machine is, what state it was in a few days ago when it was supposedly working, what you did in the mean time, what went wrong, what went right, what broke, and generally why `:echo system('jshint --version')` returns an empty string.  There are all sorts of tracers in syntastic, but your problem happens regardless of syntastic.  Not sure what else I could tell you.  Sorry about that. _shrug_

**Comment by jZhangTk** [comment]
Is there a way to debug why `:echo system('jshint --version')` doesn't return anything? I just have no idea why. You are the one who created it in the way it is, and you should be more familiar with the process. I really appreciate if you can help me out.

The thing puzzling me is that `jshint --version` works fine in terminal, and `:echo system('node --version')` works fine in vim, and `jshint` and `node` are both in `/usr/local/bin`, so `node` and `jshint` should just do the same. However, they don't...

Another thing is even with `let g:syntastic_javascript_jshint_exec = '/usr/local/bin/jshint'`, jshint still doesn't work.

Can you point me to the direction how I can further understand the problem? Thanks a lot.

**Comment by lcd047** [comment]
> Can you point me to the direction how I can further understand the problem?

Feel free to ask on forums related to Vim, `node`, and `jshint`.
