### ISSUE TITLE
Disable automatic Checking on write

### ISSUE THREAD

**Issue by giper45** [vim-syntastic/syntastic#2015]
In order to speed up Vim I disable syntactic on open, and I active  :SyntasticCheck when I need . Is there a way to disable auto checking when I save a file (:w) ? Thanks in advance !

**Comment by giper45** [comment]
I solved by this conf 
```
let g:syntastic_mode_map = { 'mode': 'passive',
                            \ 'active_filetypes': ['python'],
                            \ 'passive_filetypes': ['html', 'javascript'] }
```
When I save js files this doesn't call the checker and I call syntastic on demand . Thanks anyway !

**Comment by andrewhanlon** [comment]
Is there a way to disable this for all file types? It's a little annoying to have to wait for the check every time I want to save a file...
