### ISSUE TITLE
error: illegal start of expression              for Java8 Lambda expression

### ISSUE THREAD

**Issue by P2000K** [vim-syntastic/syntastic#2017]
```java
public class TypeInterfaceClass {

	public static void main(String[] args) {
		System.out.println(" Lambdas  .. ");
		System.out.println(System.getProperty("java.version"));
		
		PrintIt printItNow = () -> System.out.println(" Print .. ");
		
	}

	interface PrintIt {
		void print();
	}

}
```
*******************************************************************************************************

```
D:\Prakash\Practice>java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

D:\Prakash\Practice>javac TypeInterfaceClass.java
TypeInterfaceClass.java:7: error: illegal start of expression
                PrintIt printItNow = () -> System.out.println(" Print .. ");
                                      ^
TypeInterfaceClass.java:7: error: illegal start of expression
                PrintIt printItNow = () -> System.out.println(" Print .. ");
                                         ^
2 errors

D:\Prakash\Practice>
```

**Comment by P2000K** [comment]
D:\Prakash\Practice>java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

D:\Prakash\Practice>javac TypeInterfaceClass.java
TypeInterfaceClass.java:7: error: illegal start of expression
                PrintIt printItNow = () -> System.out.println(" Print .. ");
                                      ^
TypeInterfaceClass.java:7: error: illegal start of expression
                PrintIt printItNow = () -> System.out.println(" Print .. ");
                                         ^
2 errors

D:\Prakash\Practice>

**Comment by lcd047** [comment]
Please explain (preferably in full English sentences) what did you do, what did you expect to happen, and what happened instead.  Don't assume I can infer what you think is wrong from the above snippets.

**Comment by P2000K** [comment]
what did you do
I have written a simple program on Java8 using lambda expression.

what did you expect to happen
I expect to compile and run the code.

what happened instead
It did not compiled and giving compilation error :- "error: illegal start of expression" instead

Thanking you for helping

**Comment by lcd047** [comment]
Why do you think this has anything to do with syntastic?

**Comment by P2000K** [comment]
I am not sure if it is syntastic.

I tried my first code on Java compile 1.8 and facing issue.
Can you help on this.

**Comment by lcd047** [comment]
For what it's worth, I can't reproduce the error with Oracle Java 1.8.0_131.  Please consider asking on a Java forum.
