### ISSUE TITLE
JavaScript Checker Not Working

### ISSUE THREAD

**Issue by sgharms** [vim-syntastic/syntastic#2019]
At risk of great personal embarrassment I'm flummoxed to say that I can't get basic checking working. I'll hope to redeem myself by listing the process I've followed. I'm using Vim 8 in the terminal.

## Vim

```text
➜  ~ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 15 2017 02:52:29)
MacOS X (unix) version
Included patches: 1-329
```

## Plugin Loaded by vim 8 native

`:scr` shows:

```text
 46: ~/.vim/pack/plugins/start/syntastic/plugin/syntastic/autoloclist.vim
 47: ~/.vim/pack/plugins/start/syntastic/plugin/syntastic/balloons.vim
 48: ~/.vim/pack/plugins/start/syntastic/plugin/syntastic/checker.vim
 49: ~/.vim/pack/plugins/start/syntastic/plugin/syntastic/cursor.vim
 50: ~/.vim/pack/plugins/start/syntastic/plugin/syntastic/highlighting.vim
 51: ~/.vim/pack/plugins/start/syntastic/plugin/syntastic/loclist.vim
 52: ~/.vim/pack/plugins/start/syntastic/plugin/syntastic/modemap.vim
 53: ~/.vim/pack/plugins/start/syntastic/plugin/syntastic/notifiers.vim
 54: ~/.vim/pack/plugins/start/syntastic/plugin/syntastic/registry.vim
 55: ~/.vim/pack/plugins/start/syntastic/plugin/syntastic/signs.vim
 56: ~/.vim/pack/plugins/start/syntastic/plugin/syntastic.vim
 57: ~/.vim/pack/plugins/start/syntastic/autoload/syntastic/util.vim
```

## Minimal .vimrc

```viml
syntax on
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exe = 'npm run lint --'
```

## Edit a broken .js file

```javascript
Consle.log("hi world")

[1,2].forEach( x => x + 1)

consle.log("hi world');
```

### Run file through eslint in the shell

```text
➜  ~ eslint derp.js

/Users/sgharms/derp.js
  5:12  error  Parsing error: Unterminated string constant

✖ 1 problem (1 error, 0 warnings)

```
Well, yeah that should definitely break :)

## SyntasticInfo

```
Syntastic version: 3.8.0-53 (Vim 800, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checker: eslint
Currently enabled checker: eslint
```

## Is the `signs` not working?

No, I used the docs to manually insert a double `>>` successfully

```text
::sign define piet text=>> texthl=Search
::exe ":sign place 2 line=3 name=piet file=" . expand("%:p")
```

<img width="380" alt="screen shot 2017-05-13 at 9 57 27 am" src="https://cloud.githubusercontent.com/assets/50019/26026063/a1cdb62e-37c2-11e7-8894-da4f7d0b207a.png">

## Get more debug data

```text
let g:syntastic_debug = 33
let g:syntastic_debug_file = "~/syntastic.log"
```

Run `SyntasticCheck`

Logfile:

```text
syntastic: 1810.626257: g:syntastic_version = '3.8.0-53 (Vim 800, Darwin)'
syntastic: 1810.626765: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 1810.627626: UpdateErrors: default checkers
syntastic: 1810.628137: CacheErrors: default checkers
syntastic: 1810.629011: g:syntastic_aggregate_errors = 0
syntastic: 1810.629644: $TERM = 'xterm'
syntastic: 1810.629916: $TMPDIR = ''
syntastic: 1810.630150: $PATH = '/usr/local/heroku/bin:/usr/local/yubi/bin:/Users/sgharms/.gem/ruby/2.4.1/bin:/Users/sgharms/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/bin:/Users/sgharms/.rubies/ruby-2.4.1/bin:/Users/sgharms/vim8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/texbin:/Users/sgharms/bin:/usr/local/MacGPG2/bin:/usr/local/Cellar/node/7.7.4/bin'
syntastic: 1810.630446: getcwd() = '/Users/sgharms'
syntastic: 1810.631177: CacheErrors: Invoking checker: javascript/eslint
syntastic: 1810.632052: SyntasticMake: called with options: {'postprocess': ['guards'], 'errorformat': '%E%f: line %l\, col %c\, Error - %m,%W%f: line %l\, col %c\, Warning - %m', 'makeprg': 'npm run lint -- -f compact derp.js'}
syntastic: 1811.188124: system: command run in 0.555447s
syntastic: 1811.189538: getLocList: checker javascript/eslint returned 1
syntastic: 1811.190328: getLocList: checker javascript/eslint run in 0.558890s
```

## Interesting(?)

Even after I corrected the code, the syntastic debug still showed javascript/eslint returning `1`. `eslint` returned status code `0`. Maybe it's a thing?

## FAQ Points

1. Checkers seem installed
1. Checkers seem enabled
1. `:echo syntastic#util#system('echo "$PATH"')` was the same as my PATH from shell and I just installed `eslint` today....so likely no old conflicts

Well, so that's it. I'm stymied. I hate to put a PEBKAC problem in the tools repo, but I'm either missing something in docs or in interpreting the diagnostic data. Can anyone shed light here?

**Comment by lcd047** [comment]
First you set the `exe`:

> `let g:syntastic_javascript_eslint_exe = 'npm run lint --'`

Then you're comparing syntastic's results to:

> `➜  ~ eslint derp.js`

**Comment by sgharms** [comment]
@lcd047 Thanks for the help.

Let's agree that I want to run `eslint`.

I changed the value of `g:syntastic_javascript_eslint_exe` from `'npm run lint --'` to `eslint --` 

Given this the debug output is:

```text
syntastic: 10456.526966: g:syntastic_version = '3.8.0-53 (Vim 800, Darwin)'
syntastic: 10456.527466: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote
 = '', &autochdir = 0, &shellxescape = ''
syntastic: 10456.528379: UpdateErrors (auto): default checkers
syntastic: 10456.529136: CacheErrors: default checkers
syntastic: 10456.530367: g:syntastic_aggregate_errors = 0
syntastic: 10456.530831: $TERM = 'xterm'
syntastic: 10456.531135: $TMPDIR = ''
syntastic: 10456.531432: $PATH = '/usr/local/heroku/bin:/usr/local/yubi/bin:/Users/sgharms/.gem/ruby/2.4.1/bin:/Users/sgharms/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/b
in:/Users/sgharms/.rubies/ruby-2.4.1/bin:/Users/sgharms/vim8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/texbin:/Users/sgharms/bin:/usr/local/M
acGPG2/bin:/usr/local/Cellar/node/7.7.4/bin'
syntastic: 10456.531845: getcwd() = '/Users/sgharms'
syntastic: 10456.533500: CacheErrors: Invoking checker: javascript/eslint
syntastic: 10456.535027: SyntasticMake: called with options: {'postprocess': ['guards'], 'errorformat': '%E%f: line %l\, col %c\, Error - %m,%W%f: line %l\, col %c\,
Warning - %m', 'makeprg': 'eslint -- -f compact derp.js'}
syntastic: 10457.211718: system: command run in 0.674556s
syntastic: 10457.212726: getLocList: checker javascript/eslint returned 1
syntastic: 10457.213211: getLocList: checker javascript/eslint run in 0.679231s
```
Running the 'makeprg' line: `eslint -- -f compact derp.js` I see....

```text
➜  ~ eslint -- -f compact derp.js

/Users/sgharms/derp.js
  1:23  error  Missing semicolon  semi

✖ 1 problem (1 error, 0 warnings)
```

Nevertheless, the same behavior as originally reported is seen: no `signs` and no quickfix window.

**Comment by lcd047** [comment]
> Let's agree that I want to run `eslint`.

Then leave the `exe` alone.  Go back to it once you start understanding what you're doing.

> `/Users/sgharms/derp.js`
> `  1:23  error  Missing semicolon  semi`

This is the wrong format, because `eslint` ignores `-f compact`.  Which in turn happens because you set the `exe` to `eslint --`.

> Nevertheless, the same behavior as originally reported is seen: no `signs` and no quickfix window.

Assuming you left `exe` unset, please open your test file, set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output.

**Comment by sgharms** [comment]
1. Step one: comment out the `let g:syntastic_javascript_eslint_exe` line
2. Issuing: `set g:syntastic_javascript_eslint_exe` returns `E518: Unknown option: g:syntastic_javascript_eslint_exe` – so I think it's safe to say, it's not set
3. ....and YES! It works!

So clearly, my understanding of the _exe variable is why I was broken. As for why it was there, I took the formula from: https://medium.com/@hpux/vim-and-eslint-16fa08cc580f.

Pairing that with your response in #1692, I think that the `_exe` path should become `let g:syntastic_javascript_eslint_exe = 'yarn run eslint --'`. Having done so, everything still works.

Thanks for the help. Is there any subtlety I should be aware of?

**Comment by lcd047** [comment]
> Issuing: `set g:syntastic_javascript_eslint_exe` returns `E518: Unknown option: g:syntastic_javascript_eslint_exe`

Well, `set` is for Vim _options_.  Vim _variables_ are set with `let`.

> Thanks for the help. Is there any subtlety I should be aware of?

Several, but you'll probably clear them out once you spend a few minutes reading the manual. :)

**Comment by sgharms** [comment]
Sounds good, thanks for the help.
