### ISSUE TITLE
Warninings won't be displayed for puppet-lint when there already is a puppet warning/error

### ISSUE THREAD

**Issue by stefanandres** [vim-syntastic/syntastic#2020]
Scenario:
* foo.pp contains a puppet warning/error and puppet-lint warnings/errors
* syntastic is called

=> syntastic will only display the puppet warning/error, ignoring all puppet-lint warnings/errors

**Comment by lcd047** [comment]
Please read: `:h syntastic-aggregating-errors`.

**Comment by stefanandres** [comment]
Thanks,
```
let g:syntastic_aggregate_errors = 1
```  
in the vimrc works.
