### ISSUE TITLE
clang_check/clang_tidy options for clang passed without -extra-arg

### ISSUE THREAD

**Issue by nakal** [vim-syntastic/syntastic#2022]
The `clang_check` checker overrides the configuration that is usually made in the CMake output file `compile_commands.json`, because it uses the `--` variant. See [docs](http://clang.llvm.org/docs/LibTooling.html).

I have a fix that is probably incomplete and you would need to check it, but to give you an idea how additional options needs to be passed down to clang. The patch refers to [this line](https://github.com/vim-syntastic/syntastic/blob/8f97e64c78e9ade6cf09fc5d5446f5d2a8deaa35/syntax_checkers/c/clang_check.vim#L29).

```
    let makeprg = self.makeprgBuild({
        \ 'post_args':
        \   '-extra-arg=-fshow-column ' .
        \   '-extra-arg=-fshow-source-location ' .
        \   '-extra-arg=-fno-caret-diagnostics ' .
        \   '-extra-arg=-fno-color-diagnostics ' .
        \   '-extra-arg=-fdiagnostics-format=clang '.
        \   syntastic#c#ReadConfig(g:syntastic_clang_check_config_file)})
```

Note that I've removed the `--` entirely and `syntastic#c#ReadConfig()` was adding options *after* `--`, so this might break for everyone, but actually makes more sense, in my opinion.

Please also check `clang_tidy` and eventually other *LibTooling* checkers (if there are more of them).

**Comment by lcd047** [comment]
From the manual, assuming C++:

> By default you can set "ClangCheck" parameters in `g:syntastic_cpp_clang_check_args`, and compilation parameters (defines, optimisation flags, etc.) in the configuration file.
>
> However, if you want "ClangCheck" to use compilation databases (http://clang.llvm.org/docs/JSONCompilationDatabase.html) -- perhaps generated by "CMake" (https://github.com/rizsotto/Bear) or "Build EAR" (https://github.com/rizsotto/Bear) -- rather than pass compilation flags explicitly, set `g:syntastic_cpp_clang_check_post_args` to an empty string:
> ```vim
> let g:syntastic_cpp_clang_check_post_args = ""  
> ```
>                                                     
> Configuration files pointed to by `g:syntastic_clang_check_config_file` are then ignored.

There is a similar mechanism for C.

**Comment by nakal** [comment]
Ok, because it looked like, you would like to strip colors and force showing columns etc to avoid getting escape codes and wrong error message formats. With
```
let g:syntastic_cpp_clang_check_post_args = ""
```
these options are not passed down to `clang_check`. The documentation does not mention, if the removed `-f` options are important. I assumed they are.

**Comment by lcd047** [comment]
They are mostly defaults.  Also, if you force colours on in the compilation database you deserve what you get. :smirk:

**Comment by nakal** [comment]
I don't see any of these `-f` options set/forced. Ok, I understand that the `-f` options are redundant, because they are default. Thank you for the information.

**Comment by lcd047** [comment]
> I don't see any of these `-f` options set/forced.

There were people who did that in the past.
