### ISSUE TITLE
Error while doing :echo syntastic#util#system('echo %PATH%')

### ISSUE THREAD

**Issue by mjezzini** [vim-syntastic/syntastic#2023]
I am using Vim 8.0 in Windows 7. Syntastic version: 3.8.0-55 (Vim 800, Windows, GUI).

I am setting up `language-check`, so  I am trying to make  `language-check` available to  `syntastic`, I tried to add it to the path by `let $PATH .= ';' . 'C:\Python27\Scripts\'`. Then tried to check the `$PATH` by `:echo syntastic#util#system('echo %PATH%')` as suggested in the [faq](https://github.com/vim-syntastic/syntastic#4-faq) but I get the next error: 

> syntastic: error: exception running system('echo %PATH%'): Vim(let):E484: Can't open file C:\Users\MOISES~1.JEZ\AppData\Local\Temp\VIoE8FD.tmp

Can somebody guide me to the cause of this error?
Thanks

**Comment by lcd047** [comment]
> I tried to add it to the path by `let $PATH .= ';' . 'C:\Python27\Scripts\'`.

This changes Vim's idea of `PATH`.  The easier way to make syntastic find `language-check` is probably to set `g:syntastic_python_language_check_exec`.

On a side note: `language-check` only runs under Python 3.  IIRC, it's been doing that for a few years now.

> Then tried to check the `$PATH` by `:echo syntastic#util#system('echo %PATH%')`

This prints your shell's idea of `PATH` when run from Vim's `system()`.

> `syntastic: error: exception running system('echo %PATH%'): Vim(let):E484: Can't open file C:\Users\MOISES~1.JEZ\AppData\Local\Temp\VIoE8FD.tmp`

That's most likely because you messed up (one or more of) the shell-related options: `shell`, `shellcmdflag`, `shellpipe`, `shellquote`, `shellredir`, `shelltemp`, `shellxquote`, `shellxescape`.  You broke your Vim's `system()` in the process.  This has nothing to do with syntastic, but syntastic does need a working `system()`.  So come back here once you have a working `system()`.

**Comment by mjezzini** [comment]
These are my shell-related options (by `:set shell?` etc)

>   shell=C:\Windows\system32\cmd.exe
  shellcmdflag=/c
  shellpipe=>%s 2>&1
  shellquote=
  shellredir=>%s 2>&1
  shelltemp
  shellxquote=(
  shellxescape="&|<>()@^

Anyway, the plug in is working fine exept for running `:echo syntastic#util#system('echo %PATH%')` wich I am only doing trying to debug to understand how to set up language-check. Going back to that if I set:

```vim
let g:syntastic_tex_checkers = ['chktex', 'text/language_check']
let g:syntastic_tex_language_check_exec = 'C:\Python34\python.exe C:\Python34\Scripts\language-check'
let g:syntastic_tex_language_check_args = '--language=en-GB'
```
and then open a tex file and do `:SyntasticInfo` I get:

> Syntastic version: 3.8.0-55 (Vim 800, Windows, GUI)
Info for filetype: tex
Global mode: active
Filetype tex is active
The current file will be checked automatically
Available checker: chktex
Currently enabled checker: chktex
 
I can not make language_check available. 

Thanks for the help and for this amazing plug-in.

**Comment by lcd047** [comment]
> These are my shell-related options (by `:set shell?` etc)

That's great but not really relevant.  If you want to provide useful debug information please set `g:syntastic_debug` to 1, run `:SyntasticInfo`, and post the output.

> Anyway, the plug in is working fine exept for running `:echo syntastic#util#system('echo %PATH%')` 

Which is to say it _isn't_ working fine. :smile:

> `let g:syntastic_tex_language_check_exec = 'C:\Python34\python.exe C:\Python34\Scripts\language-check'`

No.  Please try:
```vim
let g:syntastic_text_language_check_exec = 'C:\Python34\Scripts\language-check'
```
Only if that doesn't work, add:
```vim
let g:syntastic_text_language_check_exe = 'C:\Python34\python.exe C:\Python34\Scripts\language-check'
```

**Comment by lcd047** [comment]
> `Currently enabled checkers: chktex text/language_check`
[...]
> `error list 1 of 1; 3 errors : noautocmd lgetexpr err_lines`

Believe it or not but we're actually making progress, now syntastic does run `language-check`. :smile:

> `:Errors`  does nothing.

Now to find out why this happens.  Ok, please open your test file, set `g:syntastic_debug` to 3, run `:SyntasticCheck text/language_check`, run `:mes`, and post the output.

**Comment by mjezzini** [comment]
These are the results

> syntastic: 34.910080: g:syntastic_version = '3.8.0-55 (Vim 800, Windows, GUI)'
syntastic: 34.912564: &shell = 'C:\Windows\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '(', &autochdir = 0, &shellslash = 0, &shellxescape = '"&|<>()@^'
syntastic: 34.921110: UpdateErrors: text/language_check
syntastic: 34.928896: CacheErrors: text/language_check
syntastic: 34.935610: g:syntastic_aggregate_errors = 0
syntastic: 34.941314: getcwd() = 'U:\GitHub\IEEE_LTCC_Transition_Coverletter'
syntastic: 34.960954: CacheErrors: Invoking checker: text/language_check
syntastic: 34.964552: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%f:%l:%c: %m', 'makeprg': '"C:\Python34\Scripts\language-check" --language=en-GB main.tex', 'returns': [0, 2]}
syntastic: 35.012508: system: command run in 0.041332s
syntastic: 35.014001: checker output: ['''"C:\Python34\Scripts\language-check"'' is not recognized as an internal or external command,', 'operable program or batch file.', '']
error list 1 of 1; 3 errors       :        noautocmd lgetexpr err_lines
syntastic: 35.025235: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '''"C:\Python34\Scripts\language-check"'' is not recognized as an internal or external command,'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'operable program or batch file.'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 35.044538: getLocList: checker text/language_check returned 1
syntastic: 35.050781: text/language_check raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'subtype': 'Style', 'text': '''"C:\Python34\Scripts\language-check"'' is not recognized as an internal or external command,'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'subtype': 'Style', 'text': 'operable program or batch file.'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'subtype': 'Style', 'text': ''}]
syntastic: 35.070485: quiet_messages filter: {'file:p': [], 'regex': '^Could not execute LaTeX command.', 'type': [], '!level': []}
syntastic: 35.077538: filtered by quiet_messages: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'subtype': 'Style', 'text': '''"C:\Python34\Scripts\language-check"'' is not recognized as an internal or external command,'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'subtype': 'Style', 'text': 'operable program or batch file.'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'subtype': 'Style', 'text': ''}]
syntastic: 35.097176: getLocList: checker text/language_check run in 0.133386s
syntastic: 35.106092: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}

**Comment by lcd047** [comment]
> `syntastic: 35.014001: checker output: ['''"C:\Python34\Scripts\language-check"'' is not recognized as an internal or external command,', 'operable program or batch file.', '']`

Ok, please try again with:
```vim
let g:syntastic_text_language_check_exec = 'C:\Python34\Scripts\language-check'
let g:syntastic_text_language_check_exe = 'C:\Python34\python.exe C:\Python34\Scripts\language-check'
```

**Comment by mjezzini** [comment]
In this case I get a very long message:

>"main.tex" 87L, 2648C
syntastic: 9.800558: g:syntastic_version = '3.8.0-55 (Vim 800, Windows, GUI)'
syntastic: 9.800841: &shell = 'C:\Windows\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '(', &autochdir = 0, &shellslash = 0, &shellxescape = '"&|<>()@^'
syntastic: 9.808428: UpdateErrors: text/language_check
syntastic: 9.815130: CacheErrors: text/language_check
syntastic: 9.821827: g:syntastic_aggregate_errors = 0
syntastic: 9.827461: getcwd() = 'U:\GitHub\IEEE_LTCC_Transition_Coverletter'
syntastic: 9.834096: CacheErrors: Invoking checker: text/language_check
syntastic: 9.839952: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%f:%l:%c: %m', 'makeprg': 'C:\Python34\python.exe C:\Python34\Scripts\language-check main.tex', 'returns': [0, 2]}
syntastic: 11.639034: system: command run in 1.792929s
syntastic: 11.639307: checker output: ['Traceback (most recent call last):', '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 529, in get_languages', '    languages = cache[''languages'']', 'KeyError: ''languages''', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 310, in _get_root', '    with urlopen(url, data, cls._TIMEOUT) as f:', '  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen', '    return opener.open(url, data, timeout)', '  File "C:\Python34\lib\urllib\request.py", line 469, in open', '    response = meth(req, response)', '  File "C:\Python34\lib\urllib\request.py", line 579, in http_response', '    ''http'', request, response, code, msg, hdrs)', '  File "C:\Python34\lib\urllib\request.py", line 507, in error', '    return self._call_chain(*args)', '  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain', '    result = func(*args)', '  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'urllib.error.HTTPError: HTTP Error 400: Bad Request', '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "C:\Python34\Scripts\language-check", line 6, in <module>', '    sys.exit(main.main())', '  File "C:\Python34\lib\site-packages\language_check\main.py", line 112, in main', '    remote_server=remote_server,', '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 201, in __init__', '    self._language = LanguageTag(language)', '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 453, in __new__', '    return str.__new__(cls, cls._normalize(tag))', '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 474, in _normalize', '    for language in get_languages()}', '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 531, in get_languages', '    languages = LanguageTool._get_languages()', '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 291, in _get_languages', '    for e in cls._get_root(url, num_tries=1):', '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 317, in _get_root', '    raise Error(''{}: {}''.format(cls._url, e))', 'language_check.Error: http://127.0.0.1:8081: HTTP Error 400: Bad Request', '']
syntastic: 11.712887: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Traceback (most recent call last):'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 529, in get_languages'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    languages = cache[''languages'']'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'KeyError: ''languages'''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'During handling of the above exception, another exception occurred:'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Traceback (most recent call last):'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 310, in _get_root'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    with urlopen(url, data, cls._TIMEOUT) as f:'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    return opener.open(url, data, timeout)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\urllib\request.py", line 469, in open'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    response = meth(req, response)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\urllib\request.py", line 579, in http_response'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    ''http'', request, response, code, msg, hdrs)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\urllib\request.py", line 507, in error'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    return self._call_chain(*args)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    result = func(*args)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    raise HTTPError(req.full_url, code, msg, hdrs, fp)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'urllib.error.HTTPError: HTTP Error 400: Bad Request'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'During handling of the above exception, another exception occurred:'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Traceback (most recent call last):'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\Scripts\language-check", line 6, in <module>'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    sys.exit(main.main())'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\site-packages\language_check\main.py", line 112, in main'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    remote_server=remote_server,'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 201, in __init__'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    self._language = LanguageTag(language)'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 453, in __new__'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    return str.__new__(cls, cls._normalize(tag))'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 474, in _normalize'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    for language in get_languages()}'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 531, in get_languages'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    languages = LanguageTool._get_languages()'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 291, in _get_languages'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    for e in cls._get_root(url, num_tries=1):'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '  File "C:\Python34\lib\site-packages\language_check\__init__.py", line 317, in _get_root'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': '    raise Error(''{}: {}''.format(cls._url, e))'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'language_check.Error: http://127.0.0.1:8081: HTTP Error 400: Bad Request'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]

**Comment by lcd047** [comment]
> `syntastic: 11.639307: checker output: ['Traceback (most recent call last):', ' File "C:\Python34\lib\site-packages\language_check_init_.py", line 529, in get_languages', ...`

Yeah, `language-check` crashes.  Not something I can help you with, I'm afraid.  Sorry about that.
