### ISSUE TITLE
does not support vim 8.0

### ISSUE THREAD

**Issue by brucelau-github** [vim-syntastic/syntastic#2025]
In my debian system, it would not work functionally after installing this plug in with vundle.

**Comment by lcd047** [comment]
This is probably the most descriptive bug report I ever read. :smile:

So, what did you do, what did you expect to happen, and what happened instead?

**Comment by vitaly-zdanevich** [comment]
Syntastic works on my macOS with Vim 8 from Homebrew.

**Comment by lcd047** [comment]
Well, no details, no cry.  Feel free to reopen this when / if you can disclose what the problem is. _shrug_
