### ISSUE TITLE
Syntastic don't work with Vim 7.0.237

### ISSUE THREAD

**Issue by andreyorst** [vim-syntastic/syntastic#2026]
Hello, just installed Syntastic via vundle to my work pc, with CentOS 5.10, and upon vim launch i recieve this error message: 
_syntastic: error: need Vim version 7.0.175 or later
Press ENTER or type command to continue_
But my Vim version is 7.0.237.

> :ver
> VIM - Vi IMproved 7.0 (2006 May 7, compiled Jan  8 2013 23:55:00)
> Included patches: 1, 3-4, 7-9, 11, 13-17, 19-26, 29-31, 34-44, 47, 50-56, 58-64, 66-73, 75, 77-92, 94-107, 
>  109, 202, 234-237
> Modified by <bugzilla@redhat.com>
> Compiled by <bugzilla@redhat.com>

**Comment by lcd047** [comment]
> But my Vim version is 7.0.237.

Not really.  Your version is essentially 7.0.109 with a smattering of later patches.  It misses the critical patch 175. :smile: But even aside from your Vim being a Frankestein, 7.0.237 was all the rage in June 2007.  Syntastic is currently a one-man show, you can't realistically expect me to tell you anything else than to upgrade your Vim.

If you want to provide useful input to this project get a [clean 7.0.175][7.0.175], compile it, and see if the latest version of syntastic works with it (or rather, tell me how it breaks).  To the best of my knowledge nobody has tried that yet.

[7.0.175]: https://github.com/vim/vim/commit/61b974b

**Comment by matthewd** [comment]
FWIW, I just tripped over breakage on 7.1.138, because [`getpid()` isn't there](https://github.com/vim/vim/commit/18081e3c4ea6291b549bff3a17f54d3162c3f278):

```
Error detected while processing .../syntastic/autoload/syntastic/util.vim:
line  404:
E117: Unknown function: getpid
E15: Invalid expression: 'syntastic_' . getpid() . '_' . reltimestr(g:_SYNTASTIC_START) . '_'
```

I am indeed applying the "upgrade your Vim[!]" strategy, but figured I'd pass on an FYI-in-passing that the minimum does seem to have exceeded the check. :heart:

**Comment by lcd047** [comment]
@matthewd Fixed (well, sort of) in 49a94fe6.

**Comment by andreyorst** [comment]
> I am indeed applying the "upgrade your Vim[!]" strategy

Unfortunately i'm not able to upgrade vim, since it is on server with a really old CentOS, and our admins doesn't want to install any package which isn't in official repo (or another stupid excuse, they have a lot)

**Comment by lcd047** [comment]
@andreyorst You can always compile and install your own version in your `$HOME`.
