### ISSUE TITLE
python 3.5 typed params: invalid syntax

### ISSUE THREAD

**Issue by vitaly-zdanevich** [vim-syntastic/syntastic#2027]
![screen shot 2017-06-06 at 10 32 56 am](https://cloud.githubusercontent.com/assets/3514015/26818502/8f16f1dc-4aa3-11e7-9b5a-8fe62ebb4245.png)

**Comment by lcd047** [comment]
Please read the [FAQ][FAQ].  If that doesn't address your problem, then please explain what am I supposed to see above.  What did you do, what did you expect to happen, and what happened instead.  Also, please avoid screenshots.  They can't de indexed, so your post is useless for people searching the archives.

[FAQ]: https://github.com/vim-syntastic/syntastic#faqpython

**Comment by vitaly-zdanevich** [comment]
ok thank you, I add in my `.vimrc`:

`let g:syntastic_python_checkers=['pylint', 'flake8', 'mypy']`
