### ISSUE TITLE
My <c-a> binding crashes vim 

### ISSUE THREAD

**Issue by EdmundsEcho** [vim-syntastic/syntastic#2028]
Syntastic + my <c-a> binding  crashes vim.  My bindings seem no to have any conflicts that I could detect looking at :map    Any ideas as to what is going on?

**Comment by lcd047** [comment]
Syntastic doesn't define, use, or care about key mappings.

On the other hand, `<C-a>` is the standard binding for increasing numbers (cf. `:h CTRL-A`).  It has a long history of crashing Vim in various situations, and bugs about it seems are found and fixed every once in a while.  However, you don't offer enough details to identify the problem, so who knows what's actually going on.

Feel free to re-open this if (1) you can actually provide an actionable description of the problem, and (2) you have evidence of it being somehow related to syntastic. _shrug_

**Comment by EdmundsEcho** [comment]
Thank you for the FYI.  I tried to learn more about the historical issues with `<C-a>` but was not able to solve it.  I did pull a log from nvim.  I have <c-a> mapped to writing and clearing whitespace. Only when I have syntastic loaded do I freeze nvim.  I turn off just this one plugin, everything works. Here are the last few lines of the nvim log.  Thank in advance for any guidance.  - E  (PS: everything has been updated to the latest stable version)

continuing in function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[8]..282[8]..289

calling function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[8]..282[8]..289[4]..syntastic#util#argsescape

function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[8]..282[8]..289[4]..syntastic#util#argsescape returning []

continuing in function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[8]..282[8]..289

function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[8]..282[8]..289 returning []

continuing in function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[8]..282

function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[8]..282 returning 'hdevtools check /Users/edmund/Dropbox....drop/pack_2/Learning/words/src/Lib.hs'

continuing in function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList

calling function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake

calling function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[1]..syntastic#log#debug

calling function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[1]..syntastic#log#debug[1]..<SNR>147__isDebugEnabled_smart

function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[1]..syntastic#log#debug[1]..<SNR>147__isDebugEnabled_smart returning #0

continuing in function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[1]..syntastic#log#debug

function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[1]..syntastic#log#debug returning #0

continuing in function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake

calling function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[30]..syntastic#util#system

calling function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[30]..syntastic#util#system[5]..syntastic#util#var

calling function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[30]..syntastic#util#system[5]..syntastic#util#var[1]..syntastic#util#rawVar

function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[30]..syntastic#util#system[5]..syntastic#util#var[1]..syntastic#util#rawVar returning '/bin/zsh'

continuing in function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[30]..syntastic#util#system[5]..syntastic#util#var

function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[30]..syntastic#util#system[5]..syntastic#util#var returning '/bin/zsh'

continuing in function <SNR>86_BufWritePostHook[4]..<SNR>86_UpdateErrors[15]..<SNR>86_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_haskell_hdevtools_GetLocList[22]..SyntasticMake[30]..syntastic#util#system

Writing ShaDa file "/Users/edmund/.local/share/nvim/shada/main.shada"

**Comment by lcd047** [comment]
Your description of the problem is still useless.  Random logs are not useful without a context.  Please show the famous map.  Explain what you did, what did you expect to happen, and what happened instead.  Can you reproduce the problem with all other plugins uninstalled?  Neovim is not supported, can you reproduce the problem with plain Vim?

**Comment by EdmundsEcho** [comment]
It happens as follows:
filetype: haskell (no issues with rc files for instance; I don't use syntastic for non haskell)
trigger:    :w   -- when I write to file
fix: <c-c>      -- this will give me back control

here is a profile of what happens when I open a file, change one thing, write to file.  I understand how it is likely not syntastic.  However, I keep getting pulled back to thinking this is the place to figure it out.  The syntastic plugin is hanging when I write to file.  I've checked through as much as I can on other functions that might be causing the hang with syntastic to no avail.  I've also read through the documentation for working with other plugins (e.g., airline), and can't see the culprit. I really appreciate your help.

`FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   5.241389   0.000042  <SNR>78_BufWritePostHook()
    1   5.241252   0.000181  <SNR>78_UpdateErrors()
    1   5.239761   0.000432  <SNR>78_CacheErrors()
    2   5.234591   0.000031  278()
    2   5.234417   0.000252  277()
    2   5.232387   0.002393  SyntasticMake()
    2   5.229147   5.229076  syntastic#util#system()
    1   4.989335   0.000102  SyntaxCheckers_haskell_hdevtools_GetLocList()
    1   0.244254   0.000085  SyntaxCheckers_haskell_hlint_GetLocList()
   20   0.050187   0.002133  airline#check_mode()
    2   0.047513   0.005951  airline#highlighter#highlight()
  161   0.035233   0.009992  airline#highlighter#exec()
   20   0.026361   0.000444  airline#extensions#branch#get_head()
   20   0.025917   0.000652  airline#extensions#branch#head()
  247   0.022992   0.006853  airline#highlighter#get_highlight()
    1   0.019267   0.000032  provider#clipboard#Call()
    1   0.019235   0.000046  373()
    1   0.019189             <SNR>135_try_cmd()
   20   0.017005   0.002044  <SNR>117_update_untracked()
   39   0.016281   0.001590  <SNR>129_exec_separator()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    2   5.229147   5.229076  syntastic#util#system()
    1              0.019189  <SNR>135_try_cmd()
  494              0.014446  <SNR>129_get_syn()
    2   0.014414   0.014383  airline#util#system()
  161   0.035233   0.009992  airline#highlighter#exec()
  247   0.022992   0.006853  airline#highlighter#get_highlight()
    2   0.047513   0.005951  airline#highlighter#highlight()
  742              0.005322  <SNR>129_Get()
  161              0.004880  <SNR>129_CheckDefined()
   20   0.008201   0.002487  <SNR>117_update_branch()
    2   5.232387   0.002393  SyntasticMake()
    1   0.003183   0.002312  353()
   20   0.050187   0.002133  airline#check_mode()
   20   0.017005   0.002044  <SNR>117_update_untracked()
   20   0.002673   0.001973  airline#extensions#whitespace#check()
  247              0.001693  <SNR>129_get_array()
   39   0.016281   0.001590  <SNR>129_exec_separator()
  120              0.001439  airline#util#append()
   40              0.001383  <SNR>26_repo()
   20              0.001276  310()`

**Comment by lcd047** [comment]
Please answer my questions:

1. What is the `<C-a>` map?
2. What did you do?
3. What did you expect to happen?
4. What happened instead?

**Comment by EdmundsEcho** [comment]
I found the incompatible plugin: eagletmt/neco-ghc
1. What is the `<C-a>` map? A:  `:w`  (it also triggered a function that cleaned up the whitespace; I disabled that early in the process)
2. What did you do? A: I could replicate the problem by using `:w` directly
3. What did you expect to happen? A: I expected the buffer to write to file and see syntastic do it's magic (i.e., check my syntax and style using ghc-mod and lint; both operating when called directly)
4. What happened instead? A: Vim would freeze, be unresponsive _until_ I hit `<c-c>` (note: `<c-q>` did not work).  Following `<c-c>` syntastic operated as expected.

My baseline configuration is <haskell-vim-now>.  Once I disabled `eagletmt/neco-ghc` syntastic functioned as designed. 

Thank you for your help.  I appreciate your keeping at it.  

Takeaway: Perhaps one benefit for these efforts might be to update the syntastic documentation to include a warning specifically using <haskell-vim-now> and or the `neco-ghc` plugin.    

The longer answer has to do with finding how `neco-ghc` was triggered with `:w`.  I still have not solved that one.  However, the `neco-ghc` functionality is somewhat redundant with syntastic so having both working side-by-side is not likely useful.

**Comment by lcd047** [comment]
It's far from clear (at least to me) that your analysis is correct.  At this point I see no reason for `ghc-mod` to be incompatible to syntastic.  Do you have `autocmd`s triggered on write?  Can you reproduce the problem with only syntastic and `neco-ghc`, and all other plugins disabled?

**Comment by EdmundsEcho** [comment]
Based on your input I tried `syntastic` with `neco-ghc`.  The two work together, and more, when I reloaded (systematically) the rest of the plugins, they continued to work.  *But*, the system is not able to find types nor perform any of the tab complete lookups.  I'll take another crack at it later in the week and update you accordingly.  - E

**Comment by EdmundsEcho** [comment]
I was able to get everything to work with neco-ghc, ghcmod-vim, deoplete.nvim and neomake.  Syntastic does not officially support neovim.  It looks like that was the the answer.  I'm still not 100% convinced that it would not eventually work and/or that I'm missing something obvious, but I have the functionality I need with the above mentioned mix of plugins.  Thank you for your help and support of this resource.  - E
