### ISSUE TITLE
syntastic status shows using hdevtools but I only have ghc-mod installed...

### ISSUE THREAD

**Issue by EdmundsEcho** [vim-syntastic/syntastic#2029]
![screen shot 2017-06-11 at 12 33 30 am](https://user-images.githubusercontent.com/11245417/27008391-b09e7d64-4e3d-11e7-9da0-67799b4d7389.png)

The status of syntastic is confusing.  Given the toggled history of working with ghc-mod I wanted to confirm what was going on here.  Thanks in advance. 

- E

**Comment by lcd047** [comment]
Please explain what did you do, what did you expect to happen, and what happened instead.
