### ISSUE TITLE
js file how ignore semicolon warning?

### ISSUE THREAD

**Issue by gatspy** [vim-syntastic/syntastic#2033]
open js file,  a lot of many warning about `Missing semicolon.`
how configuration ignore this warning.

**Comment by lcd047** [comment]
First you choose what checkers you want to run (`:h syntastic-filetype-checkers`), then you configure said checkers to give you only meaningful messages (`:h syntastic-config-makeprg`), then you tell syntastic to kill useless messages that can't be killed by other means (`:h 'syntastic_quiet_messages'`).  It's all in the manual.
