### ISSUE TITLE
Ignore an error or warning only in certain line

### ISSUE THREAD

**Issue by mjezzini** [vim-syntastic/syntastic#2034]
I have a latex document with the next commands (from package silence)

```tex
\WarningFilter*{minitoc(hints)}{W0023}
\WarningFilter*{minitoc(hints)}{W0024}
\WarningFilter*{minitoc(hints)}{W0025}
\WarningFilter*{minitoc(hints)}{W0026}
```
Now, I get the next syntastic warnings:
> preamble.tex|7 col 32 warning  36| You should put a space in front of parenthesis.
preamble.tex|8 col 32 warning  36| You should put a space in front of parenthesis.
preamble.tex|9 col 32 warning  36| You should put a space in front of parenthesis.
preamble.tex|10 col 32 warning  36| You should put a space in front of parenthesis.

I can disable the warning by `let g:syntastic_quiet_messages = { 'regex': 'You should put a space'}` but if I don't put a space later in my document I would not get the error.

Is there a way to ignore only the error in columns 8 to 10? or maybe disable syntastic inside `\WarningFilter{}`?

**Comment by lcd047** [comment]
> Is there a way to ignore only the error in columns 8 to 10?

No.  `syntastic_quiet_messages` and `syntastic_<filetype>_<checker>_quiet_messages` are the only mechanisms to kill error messages on syntastic's side.

> or maybe disable syntastic inside `\WarningFilter{}`?

Syntastic doesn't care about the contents of your files.  What syntastic does is run third party linters against your files, parse their output, and show you the results in a window.  So the only way to do what you want would be to configure said linters to ignore everything inside `\WarningFilter{}`.  Sadly the linters for TeX / LaTeX known to syntastic (`chktex` and `lacheck`) are are not particularly useful.
