### ISSUE TITLE
syntastic#util#tmpdir uses s:fuzz but the function is actually s:_fuzz

### ISSUE THREAD

**Issue by Drako** [vim-syntastic/syntastic#2036]
What the title says.

Sadly this breaks the kotlinc checker of [udalov/kotlin-vim](https://github.com/udalov/kotlin-vim).
Though it can be worked around by setting `g:syntastic_kotlin_kotlinc_delete_output = 0`.

**Comment by lcd047** [comment]
Fixed by 75d2d98.
