### ISSUE TITLE
Use only error side bar display

### ISSUE THREAD

**Issue by tdroxler** [vim-syntastic/syntastic#2038]
Hi everyone,

I'm using [sarsi](https://github.com/aloiscochard/sarsi) that already populate my quickfix window with errors.

Is it possible to use _syntastic_ to only display the error location in the side bar, without running the syntax checker (since it's already done by my build tool)?

thanks, cheers

**Comment by lcd047** [comment]
No, this is not possible, nor would it make sense from syntastic's point of view, for many reasons.  I suppose you could suggest it as a feature to `sarsi` developers though.
