### ISSUE TITLE
Automatically reload file after saving when linter performs fixes

### ISSUE THREAD

**Issue by nyuszika7h** [vim-syntastic/syntastic#2040]
I have these relevant options in `~/.config/nvim/init.vim`:

```vim
set autoread

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_args = '--fix'
```

Despite having `autoread`, when I use `:w`, the file does not get automatically reloaded when eslint performs automatic fixes.

**Comment by lcd047** [comment]
Syntastic doesn't support `--fix`.  This is true for all checkers, not just `eslint`: changing the input file on the fly is not supported.

**Comment by IanEdington** [comment]
With more and more checkers allowing automatic fixing, is this something that could be considered?

**Comment by lcd047** [comment]
@IanEdington Not without a major re-design of syntastic, sorry.  Back in the days when YCM relied on syntastic to display errors, people wanted syntastic to run as fast as possible.  Some of the optimisations added on that occasion relied on the assumption that the file stays immutable while syntastic runs.  Sorry about that.

**Comment by IanEdington** [comment]
Thanks for the quick reply and the speedy plugin 🐎 
I do love how fast syntastic runs!

I found an auto-formatter plugin that looks like it will do what I want it to.
https://github.com/Chiel92/vim-autoformat
