### ISSUE TITLE
Error detected while processing function <SNR>58_AdjustWindowHeight

### ISSUE THREAD

**Issue by tylucaskelley** [vim-syntastic/syntastic#2041]
Getting an error whenever the "state" of my syntax errors / warnings changes. I think this is a Syntastic issue, as I haven't seen this until updating my vim plugins recently; haven't changed my setup in about 2-3 months. This happens with any filetype, whenever I write to the file and there are new errors / errors are corrected w/ my syntax.

<img width="827" alt="screen shot 2017-07-11 at 11 57 50 pm" src="https://user-images.githubusercontent.com/5448759/28101202-fa37e61c-6694-11e7-9f07-96fb4dfbf0f3.png">

**Comment by lcd047** [comment]
`AdjustWindowHeight()` is not a syntastic function.  Please find out which plugin defines this function, and report back.

**Comment by tylucaskelley** [comment]
Found it! https://github.com/flowtype/vim-flow/issues/61
