### ISSUE TITLE
Last version of rubocop that appears to work is 0.28.0

### ISSUE THREAD

**Issue by ygt-mikekchar** [vim-syntastic/syntastic#2044]
At least for me.  It's very possible that I'm doing something wrong since 0.28.0 came out in 2015 and I've seen issues referencing rubocop since then.  I'm not quite sure how to debug it since syntastic does not output any error information for me to look at.

Everything works fine for version 0.28.0 and below.  For versions greater than 0.28.0, `:SyntasticInfo` claims rubocop is enabled, but I get no warning/errors. `:Error` does not open up the error list (as if there are no errors), so I'm guessing there is something slightly different in the parsing.  Is there a good way for me to debug the situation?  I'm not at all familiar with vim plugins, I'm afraid, but I'm willing to do my best :-)

**Comment by lcd047** [comment]
> It's very possible that I'm doing something wrong since 0.28.0 came out in 2015

The usual suspect is mixing several versions of `ruby` (cf. [FAQ][FAQ]).

> Is there a good way for me to debug the situation?

Yes, you can enable debugging.  Open your test file, run `:let g:syntastic_debug = 3`, then `:SyntasticCheck rubocop`, then `:mes`.

[FAQ]: https://github.com/vim-syntastic/syntastic#faqruby

**Comment by ygt-mikekchar** [comment]
Kind of embarrassing, but the problem turned out to be that I inadvertently was pointing to a version of syntastic from circa 2015 :-P  Sorry to be a pain.  Everything works great now!
