### ISSUE TITLE
Delaying sign initialization breaks ability to override signs

### ISSUE THREAD

**Issue by etiennedi** [vim-syntastic/syntastic#2046]
I found #179 back from 2012 which provides a nice possibility to override the signs with Powerline symbols. The answers in the old issue suggest to use a `~/.vim/after/plugin/syntastic.vim` file, so syntastic won't override the custom settings.

However b9620a60b74af9729bf5986e0b046eb4801852d0 introduces a "lazy setup" which only initializes signs when they're actually needed. This makes it rather impossible to override  the signs. 

Assuming I am correct, I see two potential fixes:

1. Add on option to disable "lazy setup", this would default to "lazy setup enabled" to not be a breaking change.

or

2. Let users specify signs in configuration variables and set them during initial setup.

I'd be happy to provide a PR for the preffered option. I am, however, completely new to vim plugins, so it might take a while ;)

Thanks for an amazing plugin! I hope to hear from you soon.

**Comment by lcd047** [comment]
This is described in the manual.  Please read `:h 'syntastic_error_symbol'`.

**Comment by etiennedi** [comment]
Perfect, thanks, also for the super quick response!
