### ISSUE TITLE
Ruby: bundler is not taken into account

### ISSUE THREAD

**Issue by lloeki** [vim-syntastic/syntastic#2051]
### Your environment

- vim version: 8.0.648
- Syntastic version: 3.8.0-63 (Vim 800, Darwin)

### Expected behavior

Existing `Gemfile`s should be taken into account when running ruby linters.

### Actual behavior

Existing `Gemfile`s are ignored when running linters. This does not just makes for distracting warnings when a project lags behind the latest bundler installed but altogether disables them since some newer versions can outright bail out when they don't know anymore about some deprecated config file structure. Being able to handle multiple Gemfile (possibly in nested directories) is important for monorepos and vendoring.

### Steps to reproduce the problem

```bash
mkdir -p repro/{foo,bar}
cd repro
cat > foo/foo.rb <<'EOF'
if 42 == answer
  # there should not be a linter warning above
  # but a Style/YodaCondition is raised
end
EOF
cat > bar/bar.rb <<'EOF'
if 42 == answer
  # there should be a Style/YodaCondition linter warning above
end
EOF
cat > foo/Gemfile <<'EOF'
source 'https://rubygems.org'

gem 'rubocop', '~> 0.46.0'
EOF
cat > bar/Gemfile <<'EOF'
source 'https://rubygems.org'

gem 'rubocop', '~> 0.49.0'
EOF
(cd foo; bundle install)
(cd bar; bundle install)
vim foo/foo.rb bar/bar.rb
# now look at foo.rb and bar.rb
# nested variants include foo being inside bar as well as bar being inside foo
```

**Comment by lcd047** [comment]
Please read the [FAQ](https://github.com/vim-syntastic/syntastic#faqruby).

**Comment by lloeki** [comment]
This is not meant to deal with different versions of ruby but call the proper version of the checker. the use case falls in neither of those two paragraphs (which seem to have been loosely copy-pasted from the python one and don't really make sense for ruby but I sort of get the point):

> A. Install a Ruby version manager such as rvm or rbenv, activate the environment for the relevant version of Ruby, and install in it the checkers you want to use. Set g:syntastic_ruby_checkers accordingly in your vimrc, and run Vim from the virtual environment.
>
> If you're starting Vim from a desktop manager rather than from a terminal you might need to write wrapper scripts around your checkers, to activate the virtual environment before running the actual checks. Then you'll need to point the relevant g:syntastic_ruby_<checker>_exec variables to the wrapper scripts.

From your terse answer I suppose the suggested fix is to write a wrapper script that will find the correct version of the checker from the file's path and execute it. Turns out this wrapper exists and is invoked as `bundle exec <checker>` when called from the file's `dirname`. I thought it would be nice if Syntastic could handle that by itself.

**Comment by lcd047** [comment]
> This is not meant to deal with different versions of ruby but call the proper version of the checker.

However, the same approach would also solve your problem.

> seem to have been loosely copy-pasted from the python one and don't really make sense for ruby

Please feel free to suggest a better phasing, that doesn't remotely ressemble the answer for Python, and makes complete sense for Ruby.

> Turns out this wrapper exists and is invoked as `bundle exec <checker>` when called from the file's `dirname`.

Changing the command line of the checkers is described in the manual (cf. `:h syntastic-config-makeprg`):
```vim
let g:syntastic_ruby_rubocop_exe = 'bundle exec rubocop'
```
And then you'll need to make sure you run Vim from the right directory, either with an `autocmd`, or by setting `autochdir`.

Or, as noted in the FAQ, you could write a shell script that takes care of all relevant details, and point syntastic to it.

> I thought it would be nice if Syntastic could handle that by itself.

Syntastic is a generic framework that deals with 240+ checkers.  It largely doesn't care about the contents of your files.  Making exceptions for specific filetypes is not really something it can afford.  Running out of the box for all possible situations is neither possible nor desirable.  For this reason, you (i.e. the user) are supposed to be familiar with Vim scripting, and use that knowledge to configure Vim and syntastic  to run checkers in a way that makes sense for your projects.  Perhaps you can find some Ruby-specific plugin than can run `rubocop` the right way without user intervention; syntastic doesn't aim to go there.

**Comment by lloeki** [comment]
> Please feel free to suggest a better phasing, that doesn't remotely ressemble the answer for Python, and makes complete sense for Ruby.

OK I'll do this in a PR.

> Syntastic is a generic framework that deals with 240+ checkers. It largely doesn't care about the contents of your files. Making exceptions for specific filetypes is not really something it can afford. Running out of the box for all possible situations is neither possible nor desirable. For this reason, you (i.e. the user) are supposed to be familiar with Vim scripting, and use that knowledge to configure Vim and syntastic to run checkers in a way that makes sense for your projects. 

A sensible approach. What do you think about adding the very statement you made to `README.md` (with possibly some light changes to adjust it to the context), which would establish the scope of the project in an unambiguous way?

**Comment by lloeki** [comment]
PR is at #2052.
