### ISSUE TITLE
Issues with eslint checker for json files.

### ISSUE THREAD

**Issue by jasonkarns** [vim-syntastic/syntastic#2053]
Firstly, thanks for syntastic. Secondly, thanks for your patience as I'm aware that you've dealt with these issues forever (re: eslint and pathing).

I've gone through virtually every eslint related issue already on github, to no avail. Also know that I have eslint configured and working successfully in a nearly identical fashion for _javascript_ files. My issue is solely with json files.

configuration:

```
au VimEnter * let g:syntastic_json_eslint_exe = "npx --no-install eslint"
au VimEnter * let g:syntastic_javascript_eslint_exe = "npx --no-install eslint"

au VimEnter * let g:syntastic_json_checkers = [ 'eslint' ]

au VimEnter * let g:syntastic_javascript_checkers = [ 'eslint' ]
```

:SyntasticInfo
```
Syntastic version: 3.8.0-63 (Vim 800, Darwin)
Info for filetype: json                                                                                                                     
Global mode: active
Filetype json is active
The current file will be checked automatically
Available checker: jsonlint
Currently enabled checkers: -
syntastic: 3.220182: &shell = '/usr/local/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shell
temp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
```

debug output from running SyntasticCheck in a json file:
```
syntastic: 76.129021: g:syntastic_version = '3.8.0-63 (Vim 800, Darwin)'
syntastic: 76.129197: &shell = '/usr/local/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shel
ltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 76.129599: UpdateErrors: default checkers
syntastic: 76.129986: CacheErrors: default checkers
syntastic: 76.130775: g:syntastic_aggregate_errors = 0
syntastic: 76.131123: $TERM = 'xterm-256color'
syntastic: 76.131274: $TMPDIR = '/var/folders/sv/3941ksds4v18r9y1kyptw1jw0000gn/T/'
syntastic: 76.131449: $PATH = '/usr/local/var/rbenv/shims:/usr/local/var/nodenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt
/X11/bin:/usr/local/MacGPG2/bin:/usr/local/share/git-core/contrib/workdir'
syntastic: 76.131703: getcwd() = '/Users/jasonkarns/Projects/shutterstock/analytics-schema'
syntastic: 76.132489: CacheErrors: no checkers available for json
```

**Comment by jasonkarns** [comment]
closing since (as discovered in other threads) i'm probably just going to switch to ALE. (not intending this as a diss to @lcd047 but just an FYI for anyone wondering why i closed this so quickly)

**Comment by lcd047** [comment]
There is no `eslint` checker for `json` in syntastic.  However, with recent versions of syntastic you can run `eslint` for `javascript` against any file, like this:
```vim
:SyntasticCheck javascript/eslint
```
You can also add that to `json_checkers`:
```vim
let g:syntastic_json_checkers = ['javascript/eslint']
```
This is described in the manual (cf. `:h :SyntasticCheck`).

The options that apply are also those from `javascript`, so you probably also want something like this:
```vim
let g:syntastic_json_eslint_exe = 'npx --no-install eslint'
```
On a side note: you really should avoid `autocmd`s whenever you can, for many reasons.  Something like `au VimEnter * let ...` is harmless (other `autocmd`s aren't), but pointless.

**Comment by lcd047** [comment]
> i'm probably just going to switch to ALE

Of course, that works even better.

**Comment by jasonkarns** [comment]
> On a side note: you really should avoid autocmds whenever you can, for many reasons.

Yeah, though my configuration posted above is set in project-local .vimrc files, not the global one. And I needed those variable settings to override the ones that were set by global "/after/plugin" configs. But since the project-specific configs run before the global /after/plugin configs, they were getting overwritten. :(

Anyway, thanks for the tips. I'll at least have a way to use eslint for json when I'm on non vim8 machines!

Thanks again.
