### ISSUE TITLE
[BUG] Error line number missing for golang syntastic check

### ISSUE THREAD

**Issue by arthurkiller** [vim-syntastic/syntastic#2056]
#### environment
- branch master
- vim: 8.0
- OS: mac os
- Have you reproduced with a minimal vimrc: Y
- What is your airline configuration: 
```
" vim-airline settings
"""""""""""""""""""
set laststatus=2
nmap <tab> :bn<CR>
nmap <leader>x :bdelete<CR>
let g:airline_theme="luna"
let g:airline_powerline_fonts=1
let g:airline#extensions#syntastic#enabled=1
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tagbar#enabled=1
let g:airline#extensions#ycm#enabled=1
let g:airline#extensions#capslock#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode=1
nmap <leader>1 <Plug>AirlineSelectTab1
nmap <leader>2 <Plug>AirlineSelectTab2
nmap <leader>3 <Plug>AirlineSelectTab3
nmap <leader>4 <Plug>AirlineSelectTab4
nmap <leader>5 <Plug>AirlineSelectTab5
nmap <leader>6 <Plug>AirlineSelectTab6
nmap <leader>7 <Plug>AirlineSelectTab7
nmap <leader>8 <Plug>AirlineSelectTab8
nmap <leader>9 <Plug>AirlineSelectTab9
nmap <leader>0 <Plug>AirlineSelectTab0
"""""""""""""""""""
```
if you are using terminal:
- terminal: iterm2
- $TERM variable: xterm-256color
- color configuration (:set t_Co?): 256

#### actual behavior

dosen't show the Error line number , only get `E:X`

but it act correctly on tag v0.8

**Comment by lcd047** [comment]
> Error line number missing for golang syntastic check

Syntastic have several checkers for the `go` filetype.  None of them is named `golang`.

> dosen't show the Error line number , only get `E:X`

Who / what "doesn't show the Error line number"?

> but it act correctly on tag v0.8

What is "tag v0.8"?  Of what?  Syntastic never had a tag named "v0.8".

You have given a lot of information in your post that has nothing to do with syntastic, but you failed to explain what you're complaining about.  So please back up a few steps, and explain in full English sentences:

1. What did you do
2. What did you expect to happen
3. What happened instead
4. Why do you think the differencve between what you want and what happened comes from syntastic.

**Comment by arthurkiller** [comment]
@lcd047  Hi dude , thx for reply

Golang is go language. 

I using syntastic with vim-airline for go develope.

Yesterday I pulled the lasted syntastic code on master branch. But it doesn't show the error line number which always shown on the left corner of vim.

U know , if there get something wrong in my code ,and syntastic will show me the error line number on the corner just like this 
> [Syntax: line:49 (1)]

But master show this
>  E:1

**Comment by arthurkiller** [comment]
I'm not sure this is syntastic bug or vim-airline bug. I just put up an issue

**Comment by lcd047** [comment]
This has nothing to do with syntastic, and everything to do with airline.  As far as I can tell, commit 2e30555 basically stops relying on syntastic to format errors and replaces it with unconfigurable `E:1` and `W:1`. _shrug_
