### ISSUE TITLE
clang_check let g:syntastic_c_check_header=0 seems not work

### ISSUE THREAD

**Issue by wuzangsama** [vim-syntastic/syntastic#2057]
hi there, when i open a header file(*.h) in cpp project, it always tell me that it can not find <string> or any other cpp std headers, but when I open the cpp file, it's ok. how can I disable the loclist when i open the header file?

here is the SyntasticInfo when i open the header file:
Syntastic version: 3.8.0-65 (Vim 800, Linux)                                                                                                                                                                      
Info for filetype: cpp                                                                                                                                                                                            
Global mode: active                                                                                                                                                                                               
Filetype cpp is active                                                                                                                                                                                            
The current file will be checked automatically                                                                                                                                                                    
Available checkers: clang_check gcc                                                                                                                                                                               
Currently enabled checker: clang_check

**Comment by lcd047** [comment]
1. `g:syntastic_c_check_header` takes effect for C files.  You're checking C++ files (filetype `cpp`), you need to set `g:syntastic_cpp_check_header` instead.
2. `g:syntastic_cpp_check_header` takes effect only to the `gcc` checker.  You have only the `clang_check` checker enabled.
3. `clang_check` can use a compilation database,.  Read the manual: `:h syntastic-cpp-clang_check`.
4. You can skip checking files with `syntastic_ignore_files` (cf. `:h 'syntastic_ignore_files'`):
```vim
let g:syntastic_ignore_files = ['\m\c\.h$']
```

**Comment by wuzangsama** [comment]
@lcd047 thank you for your advice, i still have a question here

why syntastic knows it's cpp headers, it checks as c headers? when i change *.h to *.hpp, there is no error at all.

**Comment by lcd047** [comment]
It's Vim that detects filetypes, not syntastic.  For header files it's likely to guesses wrong, but you can help it by adding a modeline (see `:h modeline`).

**Comment by wuzangsama** [comment]
thanks a lot~
