### ISSUE TITLE
flake8 doesn't run

### ISSUE THREAD

**Issue by jdavid2** [vim-syntastic/syntastic#2058]
Hi

I have a problem to run flake8 checker with syntastic.
```
which flake8 -->/home/data/hpmd_design/users/davidj/UTILS/FLK/bin/flake8
```
.vimrc setup
```vim
execute pathogen#infect()
" syntastic setup
let g:syntastic_python_checkers = ['flake8']
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 2
let g:syntastic_loc_list_height = 5
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
```
`SyntasticInfo` command gives
```
Syntastic version: 3.8.0-64 (Vim 704, Linux, GUI)
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
Available checkers: flake8 pep8 pycodestyle pyflakes pylint python
Currently enabled checker: flake8
```
`SyntasticCheck flake8` gives nothing

when I call `flake8` as
```
echo system('/home/data/hpmd_design/users/davidj/UTILS/FLK/bin/flake8 /home/data/hpmd_design/common/pkg/dfs_pkg-current/source/dfs_pnrcut.py')
```
I get
```
/home/data/hpmd_design/common/pkg/dfs_pkg-current/source/dfs_pnrcut.py:42:17: E999 SyntaxError: invalid syntax

/home/data/hpmd_design/common/pkg/dfs_pkg-current/source/dfs_pnrcut.py:54:80: E501 line too long (118 > 79 characters)
/home/data/hpmd_design/common/pkg/dfs_pkg-current/source/dfs_pnrcut.py:56:10: E111 indentation is not a multiple of four
/home/data/hpmd_design/common/pkg/dfs_pkg-current/source/dfs_pnrcut.py:56:10: E113 unexpected indentation
/home/data/hpmd_design/common/pkg/dfs_pkg-current/source/dfs_pnrcut.py:59:80: E501 line too long (116 > 79 characters)
/home/data/hpmd_design/common/pkg/dfs_pkg-current/source/dfs_pnrcut.py:63:80: E501 line too long (128 > 79 characters)
/home/data/hpmd_design/common/pkg/dfs_pkg-current/source/dfs_pnrcut.py:79:80: E501 line too long (95 > 79 characters)
/home/data/hpmd_design/common/pkg/dfs_pkg-current/source/dfs_pnrcut.py:105:80: E501 line too long (91 > 79 characters)
/home/data/hpmd_design/common/pkg/dfs_pkg-current/source/dfs_pnrcut.py:137:80: E501 line too long (89 > 79 characters)
/home/data/hpmd_design/common/pkg/dfs_pkg-current/source/dfs_pnrcut.py:141:80: E501 line too long (81 > 79 characters)
```
Thanks for your help

Jean

**Comment by jdavid2** [comment]
Hi Again

Something strange with syntastic, here is commands I used
1st case:  working fine, I have all errors in window
cd ~
gvim <complete_path_to_python_script>/my_script.py

2nd case: don't working, no errors in window
cd <complete_path_to_python_script>/my_script.py
gvim my_script.py

It seems the tasks to check syntax are done as
cd <path_to_flake8_bin>
flake8 my_script.py  (in this case my_script.py is not in <path_to_flake8_bin>

regards
Jean

**Comment by lcd047** [comment]
This shall solve the problem:
```vim
let g:syntastic_python_flake8_exec = '/home/data/hpmd_design/users/davidj/UTILS/FLK/bin/flake8'
```
If you actually want to find out why it doesn't work by default please undo the change above, open your test file (from the location that fails), set `g:syntastic_debug` to 3, run `:SyntasticCheck flake8`, run `:mes`, and post the output.

**Comment by jdavid2** [comment]
Hi, Thanks for you quick answer.
I add let g:syntastic_python_flake8_exec = '/home/data/hpmd_design/users/davidj/UTILS/FLK/bin/flake8' in my .vimrc and I have the same problem.
Here is the output of mess after remove "let.."
"dfs_pnrcut.py" 152L, 6814C
syntastic: 29.786504: g:syntastic_version = '3.8.0-64 (Vim 704, Linux, GUI)'
syntastic: 29.787023: &shell = '/bin/tcsh', &shellcmdflag = '-c', &shellpipe = '|& tee', &shellquote = '', &sh
ellredir = '>&', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 29.788656: UpdateErrors: flake8
syntastic: 29.789322: CacheErrors: flake8
syntastic: 29.790749: g:syntastic_aggregate_errors = 1
syntastic: 29.791224: getcwd() = '/home/data/hpmd_design/common/pkg/dfs_pkg-current/source'
syntastic: 29.791864: CacheErrors: Invoking checker: python/flake8
syntastic: 29.792647: SyntasticMake: called with options: {'cwd': '/home/data/hpmd_design/common/pkg/dfs_pkg-c
urrent/source', 'errorformat': '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %t%n %m,%A%f:%l: %t%n %m,%-G%.%#
', 'makeprg': 'flake8 dfs_pnrcut.py', 'env': {'TERM': 'dumb'}}
syntastic: 30.600885: system: command run in 0.807015s
syntastic: 30.601543: checker output: ['']
syntastic: 30.602206: raw loclist: []
syntastic: 30.603593: getLocList: checker python/flake8 returned 0
syntastic: 30.603963: python/flake8 raw: []
syntastic: 30.604309: quiet_messages filter: {}
syntastic: 30.604899: getLocList: checker python/flake8 run in 0.812696s
syntastic: 30.605392: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
syntastic: 30.606005: sorted: {'_sorted': 1, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}

I also tried to add in .vimrc
**let g:syntastic_python_flake8_fname = expand('%:p')**
but if I have several tab in gvim I don't know how to get current tab  filename

**Comment by lcd047** [comment]
`syntastic: 29.787023: &shell = '/bin/tcsh'`

This is your problem.  Please read `:h syntastic-csh`.

> I also tried to add in .vimrc `let g:syntastic_python_flake8_fname = expand('%:p')`

This is not relevant to your problem, please leave it unset.

**Comment by jdavid2** [comment]
Hi

I add let g:syntastic_shell = "/bin/sh" in my .vimrc and it is ok now.
Thanks a lot for your help
regards

Jean
