### ISSUE TITLE
python3 checks seems wrong on re.search

### ISSUE THREAD

**Issue by 3xp10it** [vim-syntastic/syntastic#2059]
after I set:
`let g:syntastic_python_python_exec = 'python3'`
in .vimrc,when I open a python file as below:
<img src="https://camo.githubusercontent.com/ecd4cbba16fa9fbc19608c1380a5c32b379e6534/687474703a2f2f636875616e74752e62697a2f74362f332f3135303237303236313478323732383330393436302e706e67">
it tells me line24's below code has invalid syntax
`if re.search(r"server is vulnerable",a,re.I):`
but in python3 it's ok to use as upon's re.search,is this a bug?

**Comment by lcd047** [comment]
> after I set: `let g:syntastic_python_python_exec = 'python3'`

Please read [item 4.11](https://github.com/vim-syntastic/syntastic#faqpython) in the FAQ.

> it tells me line24's below code has invalid syntax

Which checker tells you that?  You're aware that syntastic itself doesn't care about the contents of your files, right?

**Comment by 3xp10it** [comment]
I set flake8 as my python chekcer.

**Comment by lcd047** [comment]
Please feel free to re-open this if my answer above doesn't set you on the right path.
