### ISSUE TITLE
Python 3 syntax checker doesn't work

### ISSUE THREAD

**Issue by horseinthesky** [vim-syntastic/syntastic#2060]
Hello. I'm new with Vim and Vim Plugins and i don't know when but python3 checker just stoped working one day,

This is my Syntastic config:
```vim
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_loc_list_height=1

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_python_checkers = [ 'pylint', 'flake8', 'pep8', 'pyflakes', 'python3' ]
let g:syntastic_yaml_checkers = ['jsyaml']                                       
```
`SyntasticInfo` output (no matter Vim or NeoVim):
```
Syntastic version: 3.8.0-65 (Vim 704, Neovim, Linux)
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
Available checker: python
Currently enabled checkers: -
```
Could someone pls tell me what am i doing wrong?

**Comment by lcd047** [comment]
> Could someone pls tell me what am i doing wrong?

Please read the [first entry][FAQ1] in the FAQ.  Reading the manual might not be a bad idea, either.

> `let g:syntastic_python_checkers = [ 'pylint', 'flake8', 'pep8', 'pyflakes', 'python3' ]`

There is no checker named `python3`.  Please read [entry 4.11][FAQ11] in the FAQ.

[FAQ1]: https://github.com/vim-syntastic/syntastic#faqinfo
[FAQ11]: https://github.com/vim-syntastic/syntastic#faqpython

**Comment by horseinthesky** [comment]
Thank you. I've read FAQ but didn't find python checker list so just took it from someones .vimrc.
It does check python 2.x code with `python` in the list perfectly fine.

So is it possible to check python3 code?

**Comment by lcd047** [comment]
> I've read FAQ but didn't find python checker list so just took it from someones .vimrc.

`:h syntastic-checkers-python`

> So is it possible to check python3 code?

It is.

**Comment by horseinthesky** [comment]
I'm sorry but i still can't find out how?

**Comment by lcd047** [comment]
> I'm sorry but i still can't find out how?

It's mentioned in my first answer above?
