### ISSUE TITLE
can syntastic check cpp file use cmake or makefile  as checker configure 

### ISSUE THREAD

**Issue by viohex** [vim-syntastic/syntastic#2063]
can syntastic check cpp file use cmake or makefile  as checker configure ,
Or i have to configure gcc compile parameters for every project.

**Comment by lcd047** [comment]
> can syntastic check cpp file use cmake or makefile as checker configure ,

Most build systems today use Turing-complete languages.  Expecting a Vim script to parse something like a `Makefile` and do something sensible with the result is naive.

However, some syntastic checkers can use Clang-style compilation databases.  See `:h syntastic-cpp-clang_check`, `:h syntastic-cpp-clang_tidy`, and `:h syntastic-cpp-oclint`.
