### ISSUE TITLE
perlcritic: adjust severity tuning when calling perlcritic

### ISSUE THREAD

**Issue by sebmillet** [vim-syntastic/syntastic#2065]
Hello

the variable
g:syntastic_perl_perlcritic_thres
(default: 5)
seems not be taken into account in perlcritic invocation.
As a result, only level 5 (or, as tuned in .perlcriticrc) is displayed by default.

I attached the diff to update it thus, and have g:syntastic_perl_perlcritic_thres be taken into account.

important
The update also adds %p before %m so that the module that triggered the warning or error is displayed.

Regards, Sébastien Millet, milletseb@laposte.net

**Comment by lcd047** [comment]
The variable `g:syntastic_perl_perlcritic_thres` affects what syntastic sees as error vs. what it sees as warning.  It has nothing to do with what `perlcritic`'s cutoff level.  The cutoff level (and many other things) are configured in `.perlcritic`, and in turn have nothing to do with syntastic.  Different knobs for different things.
