### ISSUE TITLE
g:syntastic_ruby_exec is ignored when first file is opened

### ISSUE THREAD

**Issue by t0il3ts0ap** [vim-syntastic/syntastic#2068]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 26 2016 16:09:22)
Syntastic version: 3.8.0-65 (Vim 704, Darwin, GUI)

I am writing code in **jruby**, but because of its slow loading time I wanted to use **mri ruby** for syntax checking. 

```
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_ruby_exec = "/Users/someuser/.rbenv/versions/2.3.1/bin/ruby"
let g:syntastic_ruby_checkers = ['mri']
```
After putting above in **.vimrc**, syntastic uses **mri ruby** as checker except when the file is opened for the first time.

After debugging for hours I found out the issue is in `syntastic/syntax_checkers/ruby/mri.vim`

I changed this part 
```
call g:SyntasticRegistry.CreateAndRegisterChecker({
    \ 'filetype': 'ruby',
    \ 'name': 'mri',
    \ 'exec': 'ruby'})
```
to
```
call g:SyntasticRegistry.CreateAndRegisterChecker({
    \ 'filetype': 'ruby',
    \ 'name': 'mri',
    \ 'exec': g:syntastic_ruby_exec})
```
and startup time improved  by factor of 6.
I would have submitted a pull request but I don't know If this the correct way to fix.

**Comment by lcd047** [comment]
Your patch shouldn't make any difference on startup time.  Are you using a plugin manager that does lazy loading?  Do you have multiple copies of syntastic installed?  Please post a profile trace (cf. `:h syntastic-profiling`).

**Comment by t0il3ts0ap** [comment]
I am using Vundle. 
You can see the most time consuming function in the attached file at line number 4368.
This is without the patch.

[syntastic.txt](https://github.com/vim-syntastic/syntastic/files/1263313/syntastic.txt)

**Comment by t0il3ts0ap** [comment]
I have fixed the attached file. Please check.

**Comment by lcd047** [comment]
Does it help if you move the line `g:syntastic_ruby_exec` before Vundle gets initialised?

**Comment by t0il3ts0ap** [comment]
Nope it doesn't

**Comment by lcd047** [comment]
Then does anything change if you set `g:syntastic_check_on_open` to 0?

**Comment by t0il3ts0ap** [comment]
Yes then it opens instantaneously.

**Comment by lcd047** [comment]
How are you opening the file?

**Comment by t0il3ts0ap** [comment]
directly `vim filename` or  **ctrl-P** plugin. 
Both have the same results.

**Comment by lcd047** [comment]
The Ctrl-P case doesn't make sense.  Can you reproduce the problem with all plugins disabled except syntastic and Vundle?

**Comment by t0il3ts0ap** [comment]
I commented out all plugins except Vundle and Syntastic. Still same results.
If its of any help you can checkout my vimrc at https://github.com/t0il3ts0ap/dotfiles/blob/master/.vimrc

**Comment by lcd047** [comment]
Ah, sorry, I'm blind.  Try changing `g:syntastic_ruby_exec` to `g:syntastic_ruby_mri_exec`.

**Comment by t0il3ts0ap** [comment]
omg .. yup that worked. But I would have tried that if there was not this piece of code sitting around in mri.vim. Shouldn't it take care of this?

```
function! SyntaxCheckers_ruby_mri_IsAvailable() dict
    if !exists('g:syntastic_ruby_mri_exec') && exists('g:syntastic_ruby_exec')
        let g:syntastic_ruby_mri_exec = g:syntastic_ruby_exec
        call self.log('g:syntastic_ruby_exec =', g:syntastic_ruby_exec)
    endif
    return executable(self.getExec())
endfunction
```

**Comment by lcd047** [comment]
It's more complicated than that.  `g:syntastic_ruby_exec` is a legacy variable which has no real reason to exist other than backward compatibility.  It's taken into account too late, and there's no god way to fix that.  It should probably be removed, along with other similar junk.

**Comment by t0il3ts0ap** [comment]
Okay problem solved. Thanks for the help !
I give you honors of closing the issue.
