### ISSUE TITLE
SyntasticCheck doesn't display python OpenStack/hacking style guide errors

### ISSUE THREAD

**Issue by paulgeringer** [vim-syntastic/syntastic#2070]
Take the below code as an example:

```python
"""Example."""
try:
    print('hi')
except:
    pass
```

If I run `flake8` against this from the command line (no arguments/configurations set), I receive the following message:

`except.py:4:7: H201: no 'except:' at least use 'except Exception:'`

In vim, when I run `:SyntasticCheck` against the same file, no errors are displayed. The output of `:mes` at debug 3 is:

```
"except.py" 5L, 53C
syntastic: 3.656908: g:syntastic_version = '3.8.0-63 (Vim 800, Darwin)'
syntastic: 3.657109: &shell = '/usr/local/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote
 = '', &autochdir = 0, &shellxescape = ''
syntastic: 3.657693: UpdateErrors: default checkers
syntastic: 3.658050: CacheErrors: default checkers
syntastic: 3.658811: g:syntastic_aggregate_errors = 0
syntastic: 3.659066: getcwd() = '/Users/pgeringer/Development/scratch'
syntastic: 3.669817: CacheErrors: Invoking checker: python/flake8
syntastic: 3.670559: SyntasticMake: called with options: {'errorformat': '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %t%n %m,%A%f:%l: %t%n %m,%-G%.%#', 'makeprg': 'flake8
 except.py', 'env': {'TERM': 'dumb'}}
syntastic: 4.109235: system: command run in 0.438274s
syntastic: 4.109411: checker output: ['']
syntastic: 4.109766: raw loclist: []
syntastic: 4.109948: getLocList: checker python/flake8 returned 0
syntastic: 4.110055: python/flake8 raw: []
syntastic: 4.110189: quiet_messages filter: {}
syntastic: 4.110346: getLocList: checker python/flake8 run in 0.440408s
syntastic: 4.110583: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
```

Is there some extra configuration I need to force syntastic to display OpenStack/hacking style guide errors, or is this unsupported currently?

**Comment by lcd047** [comment]
Apparently running `flake8` from your Vim produces different results than running it it in your terminal:

> `syntastic: 4.109411: checker output: ['']`

What is the output of:
```vim
:echo syntastic#util#system('flake8 except.py')
```

**Comment by paulgeringer** [comment]
Here is the output:

`except.py:4:7: H201: no 'except:' at least use 'except Exception:'`

Also, its returning with an exit code of 1, compared to the 0 reported in the `:mes` output.

**Comment by lcd047** [comment]
Then what is the output of:
```vim
:echo string(syntastic#util#system('TERM=dumb flake8 except.py'))
```

**Comment by paulgeringer** [comment]
```
'except.py:4:7: H201: no ''except:'' at least use ''except Exception:''
'
```
There is an extra newline in this output, before the last `'` mark.

**Comment by lcd047** [comment]
Well, for some reasons syntastic doesn't het to see that.  Please set `verbose` to 15 (cf. `:h 'verbose'`), set `verbosefile` to a filename, run the checker, upload the resulting file somewhere, and post the link. _shrug_

**Comment by paulgeringer** [comment]
I'm pretty confused now. I re-ran it now and I see:

```
syntastic: 3.827589: g:syntastic_version = '3.8.0-63 (Vim 800, Darwin)'
syntastic: 3.827877: &shell = '/usr/local/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote
 = '', &autochdir = 0, &shellxescape = ''
syntastic: 3.828664: UpdateErrors: default checkers
syntastic: 3.829092: CacheErrors: default checkers
syntastic: 3.829822: g:syntastic_aggregate_errors = 0
syntastic: 3.830046: getcwd() = '/Users/pgeringer/Development/scratch'
syntastic: 3.841462: CacheErrors: Invoking checker: python/flake8
syntastic: 3.842120: SyntasticMake: called with options: {'errorformat': '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %t%n %m,%A%f:%l: %t%n %m,%-G%.%#', 'makeprg': 'flake8
 except.py', 'env': {'TERM': 'dumb'}}
syntastic: 4.638844: system: command run in 0.796326s
syntastic: 4.639058: checker output: ['except.py:4:7: H201: no ''except:'' at least use ''except Exception:''', '']
syntastic: 4.639519: raw loclist: []
syntastic: 4.639733: getLocList: checker python/flake8 returned 1
syntastic: 4.639862: python/flake8 raw: []
syntastic: 4.640024: quiet_messages filter: {}
syntastic: 4.640160: getLocList: checker python/flake8 run in 0.798556s
syntastic: 4.640440: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
```

in `:mes`, but it still doesn't display anything in Vim. I'll do a bit more local debugging and see if I can get some more concrete information on whats going on. I'm betting I have some environment setting thats killing flake8 in some magical way =/.

**Comment by lcd047** [comment]
Killing `flake8` should produce a different exit code.

My first guess would be that either you have a broken installation (multiple versions of syntastic installed in different locations etc.), or some other plugin is "stealing" the results (which is unfortunately possible and easy with recent versions of Vim).  Do you have a plugin manager that does lazy loading?  Can you reproduce the problem with all other plugins disabled?

**Comment by paulgeringer** [comment]
Using Vundle currently, I commented out all other plugins except Vundle and Syntastic, I unfortunately see the same output as my most recent comment (with actual `checker output`), but no syntastic output in the buffer.

I'll see if I can clean up my `.vim` to confirm that there's no errant second copy of syntastic too.

**Comment by lcd047** [comment]
You can run `:scriptnames` and look for duplicates.  You can also redirect the output from `:scriptnames` to a file (see `:h :redir`).

On a side note: not all plugins have "visible traces" in `~/.vim`, `~/.vimrc`, etc.  Eclim is the first example that comes to mind, but it's certainly not the only one.

**Comment by paulgeringer** [comment]
`:scriptnames` output has no duplicates. I have output from `verbose`, I'll try to get this uploaded somewhere if it'll be helpful.

Thanks so much for taking the time to help me debug this, I really really appreciate it!

**Comment by lcd047** [comment]
Please keep all other plugins disabled before running with `verbose`.

**Comment by paulgeringer** [comment]
[Verbose 15 output](https://gist.github.com/paulgeringer/b0c9357cf93d8556a8c42ce59b9e292c).

**Comment by lcd047** [comment]
Your trace doesn't cover the case where `flake8` doesn't return anything.

There is however a problem with your `flake8`'s output, namely `H201:`.  Syntastic expects a code without the colon, `H201`; this breaks parsing.  That's why you get no output in syntastic.

Also, `H` is not a standard code, syntastic only knows about `E`, `F`, `C`, and `N`.  But that only means the message would be marked as a warning.

**Comment by paulgeringer** [comment]
Not sure what's missing the trace, ran it the same way against the same set of files.

Understood, so since the error comes up with a `:` and the fact that it's this weird `H` prefixed value effectively makes it so that syntastic skips right past it.

If this is expected behavior, you can close this out, though it would be nice if this could be an additional feature at some point. The `H` prefix code is for the [OpenStack](https://github.com/openstack-dev/hacking) set of styleguides, which have some very useful lint rules.

**Comment by lcd047** [comment]
Adding exceptions for `H201:` is pretty much trivial, commit f1a9b153.  However, as I said, this has nothing to do with the reason why `flake8` returns an empty string. _shrug_

**Comment by paulgeringer** [comment]
Doing a force uninstall/reinstall of python & flake8 appears to have gotten stuff into a better state. I was able to pull down the updated syntastic version and was able to see the error reported properly.

Awesome. Thanks much!
