### ISSUE TITLE
Support for .vue files

### ISSUE THREAD

**Issue by pixelastic** [vim-syntastic/syntastic#2071]
Hello,

[Vue.js](https://vuejs.org/) default file extensions is `.vue` and usually looks something like that:

```vue
<template language="pug">
<!-- HTML/Pug content goes here -->
</template>

<script>
// Javascript content goes here
</script>

<style language="scss">
/* (S)CSS content goes here */
</style>
```

In addition to that, one can change the value of `language` to chose a specific flavor of HTML/JS/CSS.

I have syntastic set up to work with each filetype individually (`.pug`, `.js` and `.scss`) but fail to understand how to make it work with a file that contains several languages.

I tried to `set ft=pug.javascript.css`, but `pug-lint` tries to parse the whole file and throw errors from the JS part (`eslint` seems to behave better and only report issues from the JS part). Is there a way in syntastic to define delimiters to lint only parts of a file?

I found [pug-lint-vue](https://www.npmjs.com/package/pug-lint-vue) that correctly only output pug errors coming from the `template` part. The output is similar to `eslint` so should be easy to parse, but I don't understand how I should define it.

I'm willing to work on a PR, but I would need some pointers as the best way to organize it :)

**Comment by lcd047** [comment]
> I have syntastic set up to work with each filetype individually (`.pug`, `.js` and `.scss`) but fail to understand how to make it work with a file that contains several languages.

You don't.  This is the famous template problem, and to this day it still doesn't have any reasonable solution (or at least I'm not aware of one).  Many other template checkers would benefit from solving this generically, but that seems remote at best.

In the mean time syntastic doesn't care about the contents of your files, it just runs linters.  So if you can find a linter that can only look at each section individually, you're done.  From your description `pug-lint-vue` seems to do that but only for `vue`.  For the other languages you have to either bear with useless error messages from the unspecialised linters, or check each section by saving it to a separate file (and perhaps use `make` to re-assemble sections back).

What _doesn't_ work is use something like `sed` to isolate sections for a given language and check the results with the unspecialised linters.  You do get back a list of errors, but you can't map them back to the original file. _shrug_

**Comment by pixelastic** [comment]
Thanks for the detailed and quick answer,

So I have `pug-lint-vue` and `eslint` that are able to output only relevant errors from a `.vue` input. For CSS, seems like there's a PR for `stylelint` [on the way](https://github.com/stylelint/stylelint/pull/2596) so I'll deal with that later.

Moving forward, how should I proceed? 

Should I `set ft=pug.javascript` for `.vue` files and `let b:syntastic_checkers = ['pug-lint-vue', 'eslint']`? That would require submitting a PR to add `pug-lint-vue` as a `pug` linter. Or should I `set ft=vue` and add `pug-lint-vue` and `eslint` as linters for `vue`?

I'm confused as what the "filetype" of `.vue` files should be, from syntastic's perspective.

**Comment by lcd047** [comment]
Set `filetype` to  `vue`, since the file is not valid as anything else, then add `pug-lint-vue` as a checker for `vue`.  As for `eslint` you can either add it as a checker for `vue`, or just run it `:SyntasticCheck javascript/eslint`.  Recent versions of syntastic allows you to run `javascript/eslint` from any file, add it to `*_checkers` etc.
