### ISSUE TITLE
ECMAScript 6 

### ISSUE THREAD

**Issue by aidylewis** [vim-syntastic/syntastic#2074]
Not sure the best set-up for syntastic and ES6 and whether the older issues are out of date?

**Comment by lcd047** [comment]
> Not sure the best set-up for syntastic and ES6

At the time of this writing syntastic is a one-man show.  As such, it doesn't offer recipes for the various languages, much less advise of the "best of" kind.  Please read the manual and make sure you're running the checkers you want, with the options you want.  When you're done write a blog post about your setup if you have time to spare.

> whether the older issues are out of date

If you find an issue with the current master HEAD please feel free to report it.  Make sure to explain what did you do, what did you expect to happen, and what happened instead.

**Comment by aidylewis** [comment]
JSHInt and 
```
{
  "esversion": 6
}
```

in ~/.jshintrc seems to work and is suggested on stackoverflow.
