### ISSUE TITLE
Exception with chktex when editing .tex files

### ISSUE THREAD

**Issue by bgrassy** [vim-syntastic/syntastic#2080]
Hello,

I've been attempting to set up syntastic to work with .tex files. However, whenever I save the file to check for errors, I receive the following error message:

`syntastic: error: exception running system('chktex -q -f "%k:%n:%f:%l:%c:%m\^@" "$FILE_NAME"'): Vim(let):E484: Can't open file C:\Users\Brock\AppData\Local\Temp\VIoC65e.tmp`

This happens every time I save. If there are errors in the file, they do show up after dismissing the message; however, it is rather pesky to have this message display every time I attempt to modify or compile the file.

My gVim version is `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  6 2017 20:28:45)`, 64-bit GUI.
My syntastic version is `3.8.0-84 (Vim 800, Windows, GUI)`

Thanks for your help.

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 3, run `:SyntasticCheck chktex`, run `:mes`, and post the output.

**Comment by bgrassy** [comment]
Okay, I ran those commands and got this result:

`NERDTree: CWD is now: C:\Users\Brock\College`
`"~\College\2017-18\CSE 311\hw1.tex" [unix] 211L, 8625C`
`"2017-18\CSE 311\hw1.tex" [unix] 211L, 8624C written`
`syntastic: 35.858225: g:syntastic_version = '3.8.0-84 (Vim 800, Windows, GUI)'`
`syntastic: 35.863080: &shell = 'C:\WINDOWS\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '(', &autochdir = 0, &shellslash = 0, &shellxescape = '"&|<>()@^'`
`syntastic: 35.904144: UpdateErrors (auto): default checkers`
`syntastic: 35.925080: CacheErrors: default checkers`
`syntastic: 35.946065: g:syntastic_aggregate_errors = 0`
`syntastic: 35.964304: getcwd() = 'C:\Users\Brock\College'`
`syntastic: 36.042704: CacheErrors: Checker tex/lacheck is not available`
`syntastic: 36.045616: CacheErrors: Invoking checker: tex/chktex`
`syntastic: 36.059541: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%EError:%n:%f:%l:%v:%m,%WWarning:%n:%f:%l:%v:%m,%WMessage:%n:%f:%l:%v:%m,%Z%p^,%-G%.%#', 'makeprg': 'chktex -q -f "%k:%n:%f:%l:%c:%m\^@" "2017-18\CSE 311\hw1.tex"'}`
`syntastic: error: exception running system('chktex -q -f "%k:%n:%f:%l:%c:%m\^@" "2017-18\CSE 311\hw1.tex"'): Vim(let):E484: Can't open file C:\Users\Brock\AppData\Local\Temp\VIoF7EC.tmp`
`syntastic: 36.174791: $PATH = 'MY_PATH'`
`syntastic: 57.236622: getcwd() = 'C:\Users\Brock\College'`
`syntastic: 57.252644: &shell = 'C:\WINDOWS\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '(', &autochdir = 0, &shellslash = 0, &shellxescape = '"&|<>()@^'`
`syntastic: 57.285513: checker output: ['']`
`syntastic: 57.301410: raw loclist: []`
`syntastic: 57.314585: getLocList: checker tex/chktex returned 1`
`syntastic: 57.326263: tex/chktex raw: []`
`syntastic: 57.338960: quiet_messages filter: {}`
`syntastic: 57.351703: getLocList: checker tex/chktex run in 21.292553s`
`syntastic: 57.364799: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}`

`1 change; before #2  2 seconds ago`
`1 change; before #1  32 seconds ago`
`syntastic: 77.757500: g:syntastic_version = '3.8.0-84 (Vim 800, Windows, GUI)'`
`syntastic: 77.760601: &shell = 'C:\WINDOWS\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '(', &autochdir = 0, &shellslash = 0, &shellxescape = '"&|<>()@^'`
`syntastic: 77.789191: UpdateErrors: chkte`
`syntastic: 77.810654: CacheErrors: chkte`
`syntastic: 77.830252: g:syntastic_aggregate_errors = 0`
`syntastic: 77.863253: getcwd() = 'C:\Users\Brock\College'`
`syntastic: warning: checker chkte is not available`
`syntastic: 77.898996: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}`
`syntastic: 87.442890: g:syntastic_version = '3.8.0-84 (Vim 800, Windows, GUI)'`
`syntastic: 87.445838: &shell = 'C:\WINDOWS\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '(', &autochdir = 0, &shellslash = 0, &shellxescape = '"&|<>()@^'`
`syntastic: 87.473050: UpdateErrors: chktex`
`syntastic: 87.494420: CacheErrors: chktex`
`syntastic: 87.519321: g:syntastic_aggregate_errors = 0`
`syntastic: 87.529619: getcwd() = 'C:\Users\Brock\College'`
`syntastic: 87.546477: CacheErrors: Invoking checker: tex/chktex`
`syntastic: 87.563579: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%EError:%n:%f:%l:%v:%m,%WWarning:%n:%f:%l:%v:%m,%WMessage:%n:%f:%l:%v:%m,%Z%p^,%-G%.%#', 'makeprg': 'chktex -q -f "%k:%n:%f:%l:%c:%m\^@" "2017-18\CSE 311\hw1.tex"'}`
`syntastic: error: exception running system('chktex -q -f "%k:%n:%f:%l:%c:%m\^@" "2017-18\CSE 311\hw1.tex"'): Vim(let):E484: Can't open file C:\Users\Brock\AppData\Local\Temp\VIoC119.tmp`
`syntastic: 87.687137: $PATH = 'MY_PATH'`
`syntastic: 97.142843: g:syntastic_version = '3.8.0-84 (Vim 800, Windows, GUI)'`
`syntastic: 97.143608: &shell = 'C:\WINDOWS\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '(', &autochdir = 0, &shellslash = 0, &shellxescape = '"&|<>()@^'`
`syntastic: 97.162349: UpdateErrors: chktex`
`syntastic: 97.180103: CacheErrors: chktex`
`syntastic: 97.197405: g:syntastic_aggregate_errors = 0`
`syntastic: 97.214188: getcwd() = 'C:\Users\Brock\College'`
`syntastic: 97.230109: CacheErrors: Invoking checker: tex/chktex`
`syntastic: 97.246390: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%EError:%n:%f:%l:%v:%m,%WWarning:%n:%f:%l:%v:%m,%WMessage:%n:%f:%l:%v:%m,%Z%p^,%-G%.%#', 'makeprg': 'chktex -q -f "%k:%n:%f:%l:%c:%m\^@" "2017-18\CSE 311\hw1.tex"'}`
`syntastic: error: exception running system('chktex -q -f "%k:%n:%f:%l:%c:%m\^@" "2017-18\CSE 311\hw1.tex"'): Vim(let):E484: Can't open file C:\Users\Brock\AppData\Local\Temp\VIoE6F2.tmp`
`syntastic: 97.361105: $PATH = 'MY_PATH'`
`syntastic: 103.108106: getcwd() = 'C:\Users\Brock\College'`
`syntastic: 103.303814: &shell = 'C:\WINDOWS\system32\cmd.exe', &shellcmdflag = '/c', &shellpipe = '>%s 2>&1', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '(', &autochdir = 0, &shellslash = 0, &shellxescape = '"&|<>()@^'`
`syntastic: 103.680288: checker output: ['']`
`syntastic: 103.860800: raw loclist: []`
`syntastic: 104.300972: getLocList: checker tex/chktex returned 1`
`syntastic: 104.502612: tex/chktex raw: []`
`syntastic: 104.683897: quiet_messages filter: {}`
`syntastic: 104.842681: getLocList: checker tex/chktex run in 7.596649s`
`syntastic: 104.996352: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}`


My full path was printed three times within there, so I simply changed it to "MY_PATH" for the sake of brevity as it is extremely long; if you need to see specifics of the path, I could definitely send them.

**Comment by lcd047** [comment]
Ok, now please post the output of:
```vim
:echo system('chktex -q -f "%k:%n:%f:%l:%c:%m\^@" "2017-18\CSE 311\hw1.tex"')
```

**Comment by bgrassy** [comment]
`Warning:1:2017-18\CSE 311\hw1.tex:22:23:Command terminated with space.\^@Warning:1:2017-18\CSE 311\hw1.tex:78:8:Command terminated with space.\^@Warning:1:2017-18\CSE 311\hw1.tex:93:39:Command terminated with space.\^@Warning:1:2017-18\CSE 311\hw1.tex:93:46:Command terminated with space.\^@Warning:1:2017-18\CSE 311\hw1.tex:109:38:Command terminated with space.\^@Warning:1:2017-18\CSE 311\hw1.tex:109:48:Command terminated with space.\^@Warning:1:2017-18\CSE 311\hw1.tex:109:55:Command terminated with space.\^@Warning:1:2017-18\CSE 311\hw1.tex:109:60:Command terminated with space.\^@Warning:1:2017-18\CSE 311\hw1.tex:126:55:Command terminated with space.\^@Warning:1:2017-18\CSE 311\hw1.tex:147:67:Command terminated with space.\^@Warning:1:2017-18\CSE 311\hw1.tex:159:58:Command terminated with space.\^@Warning:44:2017-18\CSE 311\hw1.tex:167:17:User Regex: -2:Vertical rules in tables are ugly.\^@Warning:44:2017-18\CSE 311\hw1.tex:168:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\^@Warning:44:2017-18\CSE 311\hw1.tex:170:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\^@Warning:44:2017-18\CSE 311\hw1.tex:171:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\^@Warning:44:2017-18\CSE 311\hw1.tex:173:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\^@Warning:44:2017-18\CSE 311\hw1.tex:175:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\^@Warning:44:2017-18\CSE 311\hw1.tex:177:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\^@Warning:44:2017-18\CSE 311\hw1.tex:179:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\^@Warning:44:2017-18\CSE 311\hw1.tex:181:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\^@Warning:44:2017-18\CSE 311\hw1.tex:183:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\^@Warning:44:2017-18\CSE 311\hw1.tex:185:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\^@Warning:44:2017-18\CSE 311\hw1.tex:187:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\^@Warning:45:2017-18\CSE 311\hw1.tex:191:9:Use \[ ... \] instead of $$ ... $$.\^@Warning:45:2017-18\CSE 311\hw1.tex:193:9:Use \[ ... \] instead of $$ ... $$.\^@Warning:45:2017-18\CSE 311\hw1.tex:196:9:Use \[ ... \] instead of $$ ... $$.\^@chktex: WARNING -- ChkTeX does not handle lines over 509 bytes correctly.  Some errors and line numbers may be wrong in this file.
chktex: WARNING -- ChkTeX could not fully expand tabs because the resulting line would be more than 512 bytes.  Some errors and line numbers may be wrong in this file.`

This seems to be a list of all the stylistic errors within the file. I attempted the same process with a file with less errors, and it came up with the same original error and general format.

**Comment by lcd047** [comment]
Please post the output of:
```vim
:echo syntastic#util#system('chktex -q -f "%k:%n:%f:%l:%c:%m\n" "2017-18\CSE 311\hw1.tex"')
```

**Comment by bgrassy** [comment]
`syntastic: 287.891643: system: command run in 0.438290s
Warning:1:2017-18\CSE 311\hw1.tex:22:23:Command terminated with space.\nWarning:1:2017-18\CSE 311\hw1.tex:78:8:Command terminated with space.\nWarning:1:2017-18\CSE 311\hw1.tex:93:39:Command terminated with space.\nWarning:1:2017-18\CSE 311\hw1.tex:93:46:Command terminated with space.\nWarning:1:2017-18\CSE 311\hw1.tex:109:38:Command terminated with space.\nWarning:1:2017-18\CSE 311\hw1.tex:109:48:Command terminated with space.\nWarning:1:2017-18\CSE 311\hw1.tex:109:55:Command terminated with space.\nWarning:1:2017-18\CSE 311\hw1.tex:109:60:Command terminated with space.\nWarning:1:2017-18\CSE 311\hw1.tex:126:55:Command terminated with space.\nWarning:1:2017-18\CSE 311\hw1.tex:147:67:Command terminated with space.\nWarning:1:2017-18\CSE 311\hw1.tex:159:58:Command terminated with space.\nWarning:44:2017-18\CSE 311\hw1.tex:167:17:User Regex: -2:Vertical rules in tables are ugly.\nWarning:44:2017-18\CSE 311\hw1.tex:168:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\nWarning:44:2017-18\CSE 311\hw1.tex:170:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\nWarning:44:2017-18\CSE 311\hw1.tex:171:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\nWarning:44:2017-18\CSE 311\hw1.tex:173:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\nWarning:44:2017-18\CSE 311\hw1.tex:175:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\nWarning:44:2017-18\CSE 311\hw1.tex:177:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\nWarning:44:2017-18\CSE 311\hw1.tex:179:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\nWarning:44:2017-18\CSE 311\hw1.tex:181:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\nWarning:44:2017-18\CSE 311\hw1.tex:183:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\nWarning:44:2017-18\CSE 311\hw1.tex:185:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\nWarning:44:2017-18\CSE 311\hw1.tex:187:25:User Regex: -2:Use \toprule, midrule, or \bottomrule from booktabs.\nWarning:45:2017-18\CSE 311\hw1.tex:191:9:Use \[ ... \] instead of $$ ... $$.\nWarning:45:2017-18\CSE 311\hw1.tex:193:9:Use \[ ... \] instead of $$ ... $$.\nWarning:45:2017-18\CSE 311\hw1.tex:196:9:Use \[ ... \] instead of $$ ... $$.\nchktex: WARNING -- ChkTeX does not handle lines over 509 bytes correctly.  Some errors and line numbers may be wrong in this file.
chktex: WARNING -- ChkTeX could not fully expand tabs because the resulting line would be more than 512 bytes.  Some errors and line numbers may be wrong in this file.`

**Comment by lcd047** [comment]
Well, I'm afraid I have no idea how to reproduce the exception you're seeing, and `E484` is also too general to provide any useful hint.  What version of Vim are you running?

**Comment by bgrassy** [comment]
I am running gVim 8.0 with patch 1-596.

**Comment by lcd047** [comment]
After some head scratching, I believe the problem you're seeing comes from #2069, and is specific to the `tex/chktex` checker, when running under `cmd.exe` on Windows.

`chktex` doesn't separate errors by newlines when overriding the output format with `-f`, and the only way to add newlines is to pass raw control characters to `-f`.  In turn, Vim doesn't properly quote control characters when running under `cmd.exe`, and since quoting rules for `cmd.exe` are not properly documented this can't be fixed.  So basically we need to fallback to pre-#2069 when running under `cmd.exe` (meaning you lose column information).  Please try cd871da.

On an unrelated note: the way to quote several lines in markdown is to enclose them in \`\`\`...\`\`\`.

**Comment by bitsandscraps** [comment]
I had the same E484 error, but it disappeared when I changed `"%k:%n:%f:%l:%c:%m\n"` of the `chktex.vim`  to `'"%k:%n:%f:%l:%c:%m\n"'`.  Now the problem is that the errors that chktex found are not passed on to vim.

```syntastic: 22.919309: raw loclist: []
syntastic: 22.923441: getLocList: checker tex/chktex returned 1
syntastic: 22.929469: tex/chktex raw: []
syntastic: 22.934804: quiet_messages filter: {}
syntastic: 22.939857: getLocList: checker tex/chktex run in 2.531439s
syntastic: 22.946114: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}```

**Comment by lcd047** [comment]
@bitsandscraps You break it, you get to keep both parts.  Please refrain from suggesting patches if you don't understand how things are supposed to work, thank you.

**Comment by bgrassy** [comment]
That fixed the problem. Thank you!
