### ISSUE TITLE
[C++] Syntastic somehow doesn't display some g++ erorrs

### ISSUE THREAD

**Issue by cosimone64** [vim-syntastic/syntastic#2083]
I noticed that on my machine some errors aren't displayed by Syntastic in Vim, most notably missing template parameters, yet they are clearly apparent when compiling the program using g++.
As an example, the following code:
``` cpp
#include <vector>

int main()
{
        std::vector v {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        return 0;
}
```
has a clear error (missing template parameters) on the first line, but this isn't displayed. Other errors such as undeclared variables seem to work properly.
Is something wrong with my g++ configuration?

**Comment by lcd047** [comment]
Please open your test file, set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output.

**Comment by cosimone64** [comment]
Here is the output:
`"arr.cpp" 7L, 93C
syntastic: 21.372329: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &sh
ellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &s
hellxescape = ''
syntastic: 21.373201: UpdateErrors: default checkers
syntastic: 21.374251: CacheErrors: default checkers
syntastic: 21.376632: g:syntastic_aggregate_errors = 0
syntastic: 21.377162: getcwd() = /home/cosimone
syntastic: 21.377447: CacheErrors: Invoking checker: cpp/gcc
syntastic: 21.378088: SyntasticMake: called with options: {'postprocess': [], 'errorformat': '%
-G%f:%s:,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tar
ning: %m,%f:%l: %m', 'makeprg': '''g++'' -x c++ -fsyntax-only -std=c++17 -Wall -Wextra -Wpedant
ic -I. -I.. -Iinclude -Iincludes -I../include -I../includes   arr.cpp'}
syntastic: 21.475346: checker output: ['']
syntastic: 21.475654: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'n
r': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 21.475851: getLocList: checker cpp/gcc returned 0
syntastic: 21.475954: cpp/gcc raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'n
r': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 21.476131: quiet_messages filter: {}
syntastic: 21.476359: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_raw
Loclist': []}`

**Comment by lcd047** [comment]
What version of syntastic are you running?

**Comment by cosimone64** [comment]
3.6.0, haven't updated it in a while now that you mention it. I'll try installing the latest version and see what happens.

**Comment by lcd047** [comment]
Please upgrade to the current master HEAD.  If you still have the same problem please post the new debug trace.

**Comment by cosimone64** [comment]
I upgraded to 3.8.0, but the problem still persists. The new output is (checking the same test file, of course):

`"arr.cpp" 7L, 93C
"arr.cpp" 7L, 93C written
syntastic: 14.439788: g:syntastic_version = '3.8.0-87 (Vim 800, Linux)'
syntastic: 14.440388: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &sh
ellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &sh
ellxescape = ''
syntastic: 14.442166: UpdateErrors: default checkers
syntastic: 14.442983: CacheErrors: default checkers
syntastic: 14.444529: g:syntastic_aggregate_errors = 0
syntastic: 14.444744: getcwd() = '/home/cosimone'
syntastic: 14.445301: CacheErrors: Invoking checker: cpp/gcc
syntastic: 14.446130: SyntasticMake: called with options: {'postprocess': [], 'errorformat': '%
-G%f:%s:,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tar
ning: %m,%f:%l: %m', 'makeprg': '''g++'' -x c++ -fsyntax-only -std=c++17 -Wall -Wextra -Wpedant
ic -I. -I.. -Iinclude -Iincludes -I../include -I../includes   arr.cpp'}
syntastic: 14.543242: system: command run in 0.096789s
syntastic: 14.543367: checker output: ['']
syntastic: 14.543595: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'n
r': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 14.543758: getLocList: checker cpp/gcc returned 0
syntastic: 14.543856: cpp/gcc raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'n
r': -1, 'type': '', 'pattern': '', 'text': ''}]
syntastic: 14.544004: quiet_messages filter: {}
syntastic: 14.544103: getLocList: checker cpp/gcc run in 0.098676s
syntastic: 14.544335: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_raw
Loclist': []}`

**Comment by lcd047** [comment]
This seems to be between your Vim and `gcc`.  Please open Vim and post the output of:
```vim
:echo system('g++ -x c++ -fsyntax-only -std=c++17 -Wall -Wextra -Wpedantic -I. -I.. -Iinclude -Iincludes -I../include -I../includes arr.cpp')
```

**Comment by cosimone64** [comment]
The output is... nothing. Nothing at all. By the way, after upgrading a new, stranger issue appeared, I'll probably open a separate thread for it.

After opening the same test file, some arcane symbols appear after opening pretty much any .c or .cpp file I've tried it with. I'll post a screenshot, since I'm unable to copy and paste, as if they weren't there: https://imgur.com/a/bX3kr

I've even tried backing up my whole .vim folder, creating a new one from scratch and reinstalling Syntastic, 
but it still didn't work. But again, this is a separate issue, it's better to discuss it in another thread.

**Comment by lcd047** [comment]
> The output is... nothing. Nothing at all.

Yup, that's what syntastic sees.  Fix this, and syntastic should start working.

As for the phantom characters don't bother opening a new thread.  The problem has nothing to do with syntastic, please see #822 for an explanation.
