### ISSUE TITLE
Syntastic weird behaviour

### ISSUE THREAD

**Issue by Blaze349** [vim-syntastic/syntastic#2084]
First syntastic shows me an incorrect error.
I then had to delete the file.
Once I deleted the file and recreated it exactly the same way (very few lines of code) the error disappeared. Is there a way for me to clear the errors without deleting the files?

**Comment by lcd047** [comment]
I can't really parse what you're saying, but perhaps this could help: `:h :SyntasticReset`.

**Comment by Blaze349** [comment]
I stand corrected. Syntastic is still showing this error
<img width="578" alt="screen shot 2017-10-04 at 11 01 43 pm" src="https://user-images.githubusercontent.com/16263611/31175805-071b2122-a958-11e7-8a49-84ceb3fd4595.png">

<img width="529" alt="screen shot 2017-10-04 at 11 02 17 pm" src="https://user-images.githubusercontent.com/16263611/31175820-15e3f8aa-a958-11e7-8034-9b4b74947fdf.png">

**Comment by lcd047** [comment]
You do understand that syntastic doesn't know anything about C++ and just runs third-party linters, right?

**Comment by Blaze349** [comment]
Hmm, so these linters don't scan through header files?

**Comment by lcd047** [comment]
It's up to you to configure them how to run to avoid useless error messages.  It's all described in the manual.

**Comment by Blaze349** [comment]
I'm confused because I didn't have to do any of this before and I don't usually do this.

**Comment by lcd047** [comment]
I'm equally confused: do you expect me to guess what you did in the past, what you're doing now, and why the two differ? :smile:

**Comment by Blaze349** [comment]
Sorry but I do have another thing to futher muddle this issue.
<img width="628" alt="screen shot 2017-10-05 at 12 50 00 am" src="https://user-images.githubusercontent.com/16263611/31180846-3a9382ec-a967-11e7-8652-346332698419.png">
<img width="273" alt="screen shot 2017-10-05 at 12 50 17 am" src="https://user-images.githubusercontent.com/16263611/31180848-3c487a70-a967-11e7-8e9f-61e344dbe240.png">

No error here.

**Comment by Blaze349** [comment]
Why does Syntastic report an error there but not here?

**Comment by lcd047** [comment]
Syntastic doesn't, one of the linters does.  It may not even be the same linter.  Enable debugging to find out what's going on (see `:h syntastic-config-makeprg` and `:h syntastic-debug`).  Then it will become clear what each linter does, and you'll be able to reproduce the same results by running said linters in a terminal.  Then I'll be able to tell you to ask the developers of those linters why they produce the results you're seeing. :smile:

**Comment by Blaze349** [comment]
```
syntastic: 3.335576: g:syntastic_version = '3.8.0-84 (Vim 800, Darwin)'
syntastic: 3.335699: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autoc
hdir = 0, &shellxescape = ''
syntastic: 3.336104: UpdateErrors (auto): default checkers
syntastic: 3.336414: CacheErrors: default checkers
syntastic: 3.337095: g:syntastic_aggregate_errors = 0
syntastic: 3.337298: getcwd() = '/Users/Me/Programming/Pokemon-Clone'
syntastic: 3.337678: CacheErrors: no checkers available for cpp
syntastic: 3.337771: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
```

**Comment by lcd047** [comment]
> `syntastic: 3.337678: CacheErrors: no checkers available for cpp`

Which means syntastic didn't even get to run.  You have some other plugin (perhaps YCM?) that produces the errors you're accusing.

**Comment by Blaze349** [comment]
Hmm. I looked at another thread and it followed :SyntasticInfo and this was my output
```
Syntastic version: 3.8.0-84 (Vim 800, Darwin)
Info for filetype: cpp
Global mode: active
Filetype cpp is active
The current file will be checked automatically
Available checker: gcc
Currently enabled checkers: -
Checkers for filetype cpp possibly disabled by YouCompleteMe
```

**Comment by lcd047** [comment]
> `Checkers for filetype cpp possibly disabled by YouCompleteMe`

Well then, this was quick.

**Comment by Blaze349** [comment]
Yep, to fix this I disabled the diagnostic UI for YouCompleteMe. Everything is now functional, I think.

**Comment by lcd047** [comment]
I believe even that is covered in the manual: `:h syntastic-ycm`.
