### ISSUE TITLE
Checkstyle not an available checker for Java

### ISSUE THREAD

**Issue by stensjoberg** [vim-syntastic/syntastic#2087]
:SyntasticInfo output:

> Syntastic version: 3.8.0-87 (Vim 704, Darwin)                                                                                            
> Info for filetype: java
> Global mode: active
> Filetype java is active
> The current file will be checked automatically
> Available checker: javac
> Currently enabled checkers: -

.vimrc:

> let g:syntastic_always_populate_loc_list = 1
> let g:syntastic_auto_loc_list = 1
> let g:syntastic_check_on_open = 1
> let g:syntastic_check_on_wq = 0
> let g:syntastic_check_on_w = 1
> let g:syntastic_java_checkers = ['checkstyle']
>   
> let g:syntastic_java_checkstyle_classpath = "/Users/<username>/Documents/COS126/checkstyle-8.3-all.jar"
> let g:syntastic_java_checkstyle_conf_file = "/Users/<username>/Documents/COS126/checkstyle.xml"

Only when I enable javac as well do I get displayed errors...

**Comment by lcd047** [comment]
You also need to have `java` in your `$PATH`.

**Comment by stensjoberg** [comment]
Thank you @lcd047 but could you explain a bit more? I don't quite follow

**Comment by cgrindel** [comment]
I am seeing the same issue. I believe that I have found the issue. However, I do not have a fix, yet.

First, I enabled Syntastic and ran the check.

    :let g:syntastic_debug = 1
    :SyntasticCheck
    :mes

The output is below:

    "~/code/bazel-examples/examples/java-tutorial/src/main/java/com/example/ProjectRunner.java" 11L, 295C
    syntastic: 20.287045: g:syntastic_version = '3.8.0-87 (Vim 704, Linux)'
    syntastic: 20.287192: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
    syntastic: 20.287612: UpdateErrors: default checkers
    syntastic: 20.288182: CacheErrors: default checkers
    syntastic: 20.288898: g:syntastic_aggregate_errors = 0
    syntastic: 20.289270: getcwd() = '/home/ubuntu/code/bazel-examples/examples/java-tutorial'
    syntastic: 20.291537: CacheErrors: Invoking checker: java/checkstyle
    syntastic: 20.292443: SyntasticMake: called with options: {'subtype': 'Style', 'preprocess': 'checkstyle', 'errorformat': '%f:%t:%l:%c:%m', 'makeprg': 'java -cp /usr/share/java/checkstyle.jar com.puppycrawl.tools.checkstyle.Main -c /usr/share/checkstyle/google_checks.xml -f xml /home/ubuntu/code/bazel-examples/examples/java-tutorial/src/main/java/com/example/ProjectRunner.java'}
    syntastic: 20.415067: system:  command run in 0.122033s
    syntastic: 20.416940: getLocList: checker java/checkstyle returned 1
    syntastic: 20.417353: getLocList: checker java/checkstyle run in 0.125529s

I ran the java command.

    java -cp /usr/share/java/checkstyle.jar com.puppycrawl.tools.checkstyle.Main -c /usr/share/checkstyle/google_checks.xml -f xml /home/ubuntu/code/bazel-examples/examples/java-tutorial/src/main/java/com/example/ProjectRunner.java

Output from the java command.

    Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
    	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.<clinit>(ConfigurationLoader.java:57)
    	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:258)
    	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
    Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	... 3 more

BTW, I installed checkstyle using `sudo apt-get checkstyle`. Interestingly, when I run checkstyle directly, it works fine. Based upon the error it looks like the jar that is installed is not a deploy jar with all of its deps. I'll try to circle back to this, later today.

**Comment by lcd047** [comment]
> `syntastic: 20.291537: CacheErrors: Invoking checker: java/checkstyle`

The checker runs fine.  However:

> `Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory`

your `checkstyle` crashes.  This has nothing to do with syntastic.  Fix this, and syntastic should start working. _shrug_
