### ISSUE TITLE
Erlang Syntax checking disabled when parse transform is in any file

### ISSUE THREAD

**Issue by PiedPieper** [vim-syntastic/syntastic#2089]
Hello all,

Currently, there is bug when using syntastic that causes erlang code to not be checked when there is the string {parse_transform} anywhere in the project directory. 

There was an issue posted a few years ago https://github.com/vim-syntastic/syntastic/pull/380 but the fix does not work - when I put the string: `let g:syntastic_erlc_attrs="-pa ~/workspace/libs/elang/*/ebin"` into my .vimrc, this does not change anything. If this has to be a specific directory, can you please clarify which directory it must be? I tried let `g:syntastic_erlc_attrs="-pa ~/repos/server/ebin"` but that does not do the trick either.

Is there any update on this or am I doing something incorrectly?

Thanks

**Comment by lcd047** [comment]
The issue you mention is actually a pull request merged 5 years ago.  You have three options:

* downgrade syntastic to the version from 5 years ago that fixes your problem, and use that;
* read the manual, find out how to change checker command line options, and figure it out yourself; or
* explain to me the problem and the supposed solution, and wait for me to fix it.

Please keep in mind I know essentially nothing about Erlang.

**Comment by PiedPieper** [comment]
@lcd047 Thanks for the quick response. Maybe it will help if I explain it a bit better - there is a compile flag called {parse_transform, _} where _ is the custom transform to apply to the file. What the custom transform does is in this context is change function names in the file pre-compilation. This is useful for error logging, a popular error logging erlang program called "lager" will allow you to specify unique logging levels based on severity. 

So, the problem seems to be that when the syntax checker sees "-compile({parse_transform, _}) it just doesn't run, or the parse transform interrupts it running. Is it possible to add an ignore anywhere in the syntax checker to ignore any line that starts with "-compile" or any line that contains "parse_transform"?

**Comment by lcd047** [comment]
What checker are you running?

**Comment by PiedPieper** [comment]
@lcd047 syntastic

**Comment by lcd047** [comment]
What syntastic checker are you using?

**Comment by PiedPieper** [comment]
The output from :SyntasticInfo is : 

Syntastic version: 3.8.0-63 (Vim 704, Linux)
Info for filetype: erlang
Global mode: active
Filetype erlang is active
The current file will be checked automatically
Available checker: escript
Currently enabled checker: escript

**Comment by PiedPieper** [comment]
@lcd047 I created a workaround for this that is probably a lot faster than making you change code, and it doesn't seem like this issue has been posted in years. 

What I did was created a separate project called "mylogger" and use that as a wrapper for the lager calls. So now all of my meaningful files I can do syntax checking on, and I just use mylogger as a dependency.

**Comment by lcd047** [comment]
Unless I'm missing something, you could also have solved your problem by adding the relevant options to `g:syntastic_erlang_erlang_args`. _shrug_
