### ISSUE TITLE
xml error start tag expected, '<' not found

### ISSUE THREAD

**Issue by IWFML** [vim-syntastic/syntastic#2090]
Hi, man. Recently I wanna try to move my project back to vim. I am kind of dependent on the syntax check. Obviously, the plugin will do help me a lot. 
However, when I tried to use some dependencies on pom.xml, I found I was telling the error above, that is "pom.xml | 2 error | Start tag expected '<' not found". And that is quite annoying for me.
because I just write something like this:
`<? xml version="1.0" encoding="UTF-8” ?>`

![error](https://user-images.githubusercontent.com/29864461/31570540-4f7d6c5c-b0b7-11e7-9d7c-adc0cb1b67b8.png)

Hope you guys can give me a hand. Thx

**Comment by lcd047** [comment]
Don't shoot the messenger.  Syntastic doesn't care about the contents of your files, it just runt external linters.  In this case `xmllint` complains about your file, not syntastic.  If you disagree with that behaviour you can either report it to `xmllint` developers, or stop running the checker until the file is actually ready for being checked (i.e. read the manual, and make `xml` filetype passive).
