### ISSUE TITLE
Warnings hide the first char at the respective lines

### ISSUE THREAD

**Issue by Paludan** [vim-syntastic/syntastic#2091]
**steps to reproduce the bug;**
":w" to save and display warnings
**the version of Vim you are using (run :ver to find out);**
NVIM 0.1.7
**the version of syntastic you are using (see :SyntasticInfo).**
3.8.0.88

![screenshot from 2017-10-16 16-18-37](https://user-images.githubusercontent.com/9047148/31616868-2ad7c978-b28e-11e7-9c71-b1b9b40ebba5.png)
![screenshot from 2017-10-16 16-18-23](https://user-images.githubusercontent.com/9047148/31616872-2f6073e6-b28e-11e7-8594-1fd9da0c47a0.png)

As you can see when the warnings load the first character on each line of warnings are hidden (not removed, only hidden). This is a bit confusing.

**Comment by lcd047** [comment]
This has nothing to do with syntastic, even though it might have been _triggered_ by it.  Please see #822 for an explanation.  My first guess would be a bug in Neovim, so please consider reporting it there.

**Comment by Paludan** [comment]
Manually calling redraw doesn't do anything here. I'll try and post this issue in neovim. Thanks :)
