### ISSUE TITLE
Possible bug: location list leaves buffer trying to write to stdin

### ISSUE THREAD

**Issue by decibel** [vim-syntastic/syntastic#2092]
Occasionally I end up with a buffer that is trying to write to "-stdin-", which results in E212. This only happens when syntastic has opened an error list, I've moved to the error list and hit return to go to the location of an error. After fixing the error and attempting to `:w`, I get an error.

It's possible this isn't syntastic, and I [opened a StackOverflow](https://stackoverflow.com/q/46780696/) before I realized the possible connection with syntastic. I'm wondering if this is somehow related to some of the other issues with error lists.

Any suggestions on how to debug this?

**Comment by decibel** [comment]
If I `:w temp` I can then do a `:w` once (if there's still errors).

I did a `:w temp.go`, `:w`, `:rm temp.go`, fixed the remaining errors, `:w` and now things are back to normal.

**Comment by lcd047** [comment]
This is unlikely to have anything to do with syntastic, but then weirder things have happened.

First make sure you're using syntastic, as opposed to, say, [vim-go][vim-go].  Syntastic doesn't have any checker for `go` enabled by default.

If you're sure what you're seeing is a syntastic window, please set `g:syntastic_debug` to 1, reproduce the problem, run `:mes`, and post the output.  Please also explain what did you do.  Don't assume I can read your mind to understand what you're trying to do, nor that I can't look over your shoulder to see what you're actually doing.

[vim-go]: https://github.com/fatih/vim-go

**Comment by lcd047** [comment]
> the window indicated it was syntastic.

Sadly this doesn't necessarily mean the window was, acttually, created by syntastic.  If you use vim-go together with syntastic and you don't explicitly tell vim-go not to mess with loclists you _can_ get this effect.

**Comment by decibel** [comment]
I've got a window that's doing it again...

```
syntastic: 939588.106261: g:syntastic_version = '3.8.0-87 (Vim 800, Darwin, GUI)'
syntastic: 939588.106430: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 1 (!), &shellxescape = ''
syntastic: 939588.107117: UpdateErrors (auto): default checkers
syntastic: 939588.107829: CacheErrors: default checkers
syntastic: 939588.109010: g:syntastic_aggregate_errors = 0
syntastic: 939588.109218: getcwd() = '/Users/jimnasby/dev2/src/<github repo>/delta'
syntastic: 939588.109738: CacheErrors: Invoking checker: go/go
syntastic: 939588.110371: SyntasticMake: called with options: {'errorformat': '%f:%l:%c: %m,%-G%.%#', 'defaults': {'type': 'e'}, 'makeprg': 'gofmt -l instance.go > /dev/null'}
syntastic: 939588.167125: system: command run in 0.056388s
syntastic: 939588.184598: SyntasticMake: called with options: {'cwd': '/Users/jimnasby/dev2/src/<github repo>/instance', 'errorformat': '%W%f:%l: warning: %m,%E%f:%l:%c:%m,%E%f:%l:%m,%C%\s%\+%m,%+Ecan''t load package: %m,%+Einternal error: %m,%-G#%.%#', 'defaults': {'type': 'e'}, 'makeprg': 'go build -buildmode=arch
ive', 'env': {'GOGC': 'off'}}
syntastic: 939589.477406: system: command run in 1.291849s
syntastic: 939589.495832: getLocList: checker go/go returned 2
syntastic: 939589.496071: getLocList: checker go/go run in 1.386221s 
```

**Comment by lcd047** [comment]
Please explain in detail what did you do.   Can you reproduce the problem with `autochdir` unset?  What `vim-go` configuration are you using?  Can you reproduce it with all other plugins disabled?  What version of Vim are you using?

Also `go` returned with code 2.  Please post the debug log for `g:syntastic_debug` set to 3.

**Comment by lcd047** [comment]
No feedback, no cry.

**Comment by decibel** [comment]
Unfortunately, I have no way to make this trigger on demand. It hasn't happened since the last time I posted.

**Comment by decibel** [comment]
Had another occurrence. gvim isn't letting me copy the debug output before it clears it, but I can tell that the stdin error is *before* any syntastic output. So at this point, I don't think it's related.

Thanks for the debug help!
