### ISSUE TITLE
Syntastic not working on local machine

### ISSUE THREAD

**Issue by hardianlawi** [vim-syntastic/syntastic#2094]
I am currently facing this error whenever I type `:SyntasticInfo` on any python file. The file is `not readable / not local` even though it is in my local machine.

```
Syntastic version: 3.8.0-63 (Vim 800, Linux, GUI)
Info for filetype: python
Global mode: passive
Filetype python is passive
The current file will not be checked automatically
Available checkers: flake8 pep8 pycodestyle pyflakes python
Currently enabled checker: flake8
The current file will not be checked (file not readable / not local)
```

This is the output when I ran `:echo syntastic#util#system('echo "$PATH"')`
```
/home/hardianlawi/bin:/home/hardianlawi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/hardianlawi/D
esktop/DataGrip-2017.1.5/bin:/home/hardianlawi/DataGrip-2017.1.5/bin:/home/hardianlawi/pycharm-2017.2.3/bin
```

Any suggestion?

**Comment by lcd047** [comment]
What file are you trying to check?  Is it actually readable by the current user?  Is it inside an archive?

**Comment by hardianlawi** [comment]
Hi, sorry. It seems that I won't be able to check it if I haven't saved the file yet, which is what the problem was. But then, how do I enable auto checking everytime I open a python script?

**Comment by lcd047** [comment]
It's all in the manual: `:h 'syntastic_check_on_open'`.

**Comment by hardianlawi** [comment]
Okay thanks!
