### ISSUE TITLE
"Cannot find checker" notifications?

### ISSUE THREAD

**Issue by iselind** [vim-syntastic/syntastic#2097]
Is there a way by which i can get notified when a configured checker cannot be found in $PATH?

I was struck by this after upgrading my OS, my installed Python packages had been removed for some reason. Why is another discussion.

While editing my code, there was nothing complaining. I would have like to think this meant everything was OK, until i found that the checker wasn't installed. Once i installed it, it complained quite a lot.

I found this quite annoying. Is there something i can configure to get these kinds of notifications?

I run Syntastic v3.8.0 installed through pathogen in Vim v8.0 on a Debian Stretch machine.
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)
Included patches: 1-197, 322, 377-378, 550, 703, 706-707
```

**Comment by lcd047** [comment]
Sadly there is no reasonable way to do that.  Syntastic is stateless, which means it would have to look for all checkers at every run.  And since validating checkers involves more than just looking for the corresponding executables, that would have a major impact on performance, for very little gain.

Write a function to look for the relevant executables and call it from your `vimrc` if you think it actually solves a problem.  I won't forcefully inflict that penalty to unsuspecting users. :smile:

**Comment by iselind** [comment]
So you're saying that notifying the user that some of the binaries 'registered' in for example `syntastic_python_checkers` cannot be found would be difficult because Syntastic is stateless? These are the notifications i'm asking for.

I fail to see how Syntastic being stateless makes any difference here?

**Comment by lcd047** [comment]
> So you're saying that notifying the user that some of the binaries 'registered' in for example `syntastic_python_checkers` cannot be found would be difficult because Syntastic is stateless?

No, I'm saying that what you ask would be slow, and annoying at best.  I'm also saying that so far the people who need this kind of validation seem to be in a minority of one.

> I fail to see how Syntastic being stateless makes any difference here?

Stateful validation:

* First run:
  - see if `pylint`, `pylama`, and `frosted` are installed
  - check `program --version`
  - save locations, `mtime`s, and sizes of the binaries
* Subsequent runs:
  - check if binaries with the given `mtime`s and sizes can still be found at the given locations.

Stateless validation:

* At every run:
  - see if `pylint`, `pylama`, and `frosted` are installed
  - check `program --version`

Running `program --version` is slow.  Reportedly `rubocop --version` can take up to 5 seconds on Mac OSX.  I'm simplifying, there are also some other forms of caching involved above, but they don't change the final outcome.

**Comment by iselind** [comment]
Your suggested way seem overcomplicated to me. I see no reason why you should need to call `program --version` or any version there of to check if the binary is there.

After you try to execute a checker listed in `syntastic_python_checkers` you probably check the return value to see if there is anything to report or not. This error code could probably be something useful when the checker wasn't found. If that be the case, just report that checker X wasn't found, similar to if a checker found an issue.

This would probably work regardless of Syntastic being stateless or not. It's more like augmenting the interpretation of the exit code.

Not having this reported would introduce a false sense of 'security' in that you expect the checkers to be running. If Syntastic silently hides that they are not checking your documents, then the user would risk checking in things that no longer adhere to the style guide.

The need for this validation is most likely far from a minority of one. It's probably more due to people expecting Syntastic to actually check stuff. If it cannot for some reason, they like me would expect the tool to notify me.
