### ISSUE TITLE
Not recognising ~ while importing using webpack sass-loader showing " File to import not found or unreadable" error

### ISSUE THREAD

**Issue by anoopd** [vim-syntastic/syntastic#2098]
From [webpack sass-loader](https://github.com/webpack-contrib/sass-loader)

## Imports

webpack provides an advanced mechanism to resolve files. The sass-loader uses node-sass' custom importer feature to pass all queries to the webpack resolving engine. Thus you can import your Sass modules from node_modules. Just prepend them with a ~ to tell webpack that this is not a relative import:

@import "~bootstrap/dist/css/bootstrap";
It's important to only prepend it with ~, because ~/ resolves to the home directory. webpack needs to distinguish between bootstrap and ~bootstrap because CSS and Sass files have no special syntax for importing relative files. Writing @import "file" is the same as @import "./file";

but doing so is detected as " File to import not found or unreadable  "  .

**Comment by lcd047** [comment]
Please see #1799.
