### ISSUE TITLE
extra comment after disable directive

### ISSUE THREAD

**Issue by brianjmurrell** [vim-syntastic/syntastic#2100]
It would be nice to be able to add extra comment after a _disable_ directive such as:

```
# shellcheck disable=SC2034 variable FOO is used in other files that import this one
```
to remind oneself and others what is being ignored.

**Comment by lcd047** [comment]
I'm afraid I'm not following what you're saying here.  Where do you want to add a comment, and what does that have to do with syntastic?

**Comment by brianjmurrell** [comment]
The example directive in the original comment is invalid.  Syntastic won't actually disable the SC2034 check for the line following that line, presumably because there is text trailing the directive.

I'm proposing that if there is text trailing a directive line, that it be ignored rather than invalidating the directive.  That text is there to explain to future readers why the directive has been put there, for example.

**Comment by lcd047** [comment]
I'm afraid I still don't follow.  What directive?  Please explain in enough detail to be accessible to my tiny brain: what did you do, what did you expect to happen, and what happened instead?

**Comment by brianjmurrell** [comment]
Never mind.  I had the wrong project open.
