### ISSUE TITLE
SDL should be sdl2

### ISSUE THREAD

**Issue by mrkite** [vim-syntastic/syntastic#2108]
in c.vim, you call registerHandler SDL with sdl.. I'd say it should be sdl2 since that's what most people use these days.

**Comment by lcd047** [comment]
It's a change that breaks backwards compatibility.  Also this kind of library autodetection is not that useful in practice, the vast majority of time you end up writing a config file with everything anyway.  I'm actually considering removing this autodetection altogether.

That said, there are a other defaults that no longer make sense today.  I'll probably update them all in the next release.
