### ISSUE TITLE
Moving a split to a new tab orphans the location list

### ISSUE THREAD

**Issue by trosh** [vim-syntastic/syntastic#2111]
When editing a buffer, if you open a new buffer in a split (for example `:vsplit <name-of-file>`) it opens with a corresponding location list. If you then move that split to a new tab (on the split, type `<C-w><S-t>`), it is moved correspondingly, and a new location list is created in that tab, but the original one is left, orphaned, in the original tab.

**Comment by trosh** [comment]
This seems similar, but different, to issue #400

**Comment by lcd047** [comment]
I'm not sure I understand exactly what you're doing, but I'm not able to reproduce this.  But either way, why do you expect syntastic to be able to fix this?  As far as I can tell syntastic can't even detect this situation, let alone do something about it.  Does this behaviour differ from plain Vim handling of loclists, without syntastic?

**Comment by trosh** [comment]
Well I mentioned moving a split to a new tab, but really any movement of a buffer seems to unlink it from its Location List. (After checking, it seems that it's also the case with other similar objects, like vim-fugitive's Gblame linked splits.) It seems annoying to me because LLs appear anytime a buffer is opened/moved/saved, so it feels subpar that they are only weakly linked to their corresponding buffer.

I guess I should find out how to disable/enable Syntastic with a hotkey to update the state of LLs instead of expecting strong correlation of splits, but that seems imperfect as well.

**Comment by lcd047** [comment]
As I said, there is no way for syntastic to detect this situation, let alone do something about it.  For a long time there has been no reliable way to tell, from a Vim script, that a given window was actually a loclist window, let alone find its owner.  Then things have improved somewhat, thanks to a number of recent patches.  But even with the new features, there are many, many things missing to make it possible to do what you want.  If you expect perfect behaviour from Vim you're going to be sourly disappointed.  In Vim just about any non-trivial problem is solved to 95%.  If you happen to run into the remaining 5%, well, you lose.

Back to syntastic, see `:h :SyntasticToggleMode`.  You can bind that to a key.  Also relevant: `:h 'syntastic_auto_loc_list'`, `:h 'b:syntastic_mode'`.
