### ISSUE TITLE
Error highlight always appearing in cyan color so that we can't see the message

### ISSUE THREAD

**Issue by arthurfaccioly** [vim-syntastic/syntastic#2112]
Hi, I researched everywhere but couldn't find a solution. 

This is what I did:
1. Followed the instructions of this page to install all the packages at once:
[vim-bootstrap](https://github.com/avelino/vim-bootstrap)
2. After installing everything, I made a small test and could see the following error:
<img width="625" alt="screen shot 2017-11-15 at 3 38 29 pm" src="https://user-images.githubusercontent.com/19752629/32859092-7d2431c2-ca1b-11e7-842d-ec38dc07a7e0.png">

As you can see, it's almost impossible to see the message with a cyan color background.
3. After that, I tried to change the [vim-airline-themes](https://github.com/vim-airline/vim-airline-themes) like: :AirlineTheme simple or :AirlineTheme badwolf, etc. but didn't work. 

Can somebody help me here? Thank you a lot.

**Comment by lcd047** [comment]
This has nothing to do with syntastic.  Syntastic doesn't know (nor cares) about highlighting in the error window.  That's up to the theme you're using (not the Airline theme).

**Comment by arthurfaccioly** [comment]
Thanks for the tip. In the end I couldn't change the cyan color, but got in a better state using the onehalflight theme that I've found [here.](https://github.com/sonph/onehalf#installation-&-usage)

<img width="619" alt="screen shot 2017-11-15 at 4 56 52 pm" src="https://user-images.githubusercontent.com/19752629/32862404-045ae6ae-ca26-11e7-87e8-ff54858fb500.png">

**Comment by lcd047** [comment]
With recent versions of Vim highlighting of the current line in error windows is controlled by the `QuickFixLine` group.  With older versions it's the `Search` group.
