### ISSUE TITLE
cnext and cprevious always report no errors

### ISSUE THREAD

**Issue by NikosEfthias** [vim-syntastic/syntastic#2113]
when i try to navigate through the errors using :cnext and :cprev they always report no errors while there are errors market by syntactic on the page

**Comment by lcd047** [comment]
Please read section [Recommended settings](https://github.com/vim-syntastic/syntastic#settings) in the FAQ, and act accordingly.  Feel free to reopen this if you still have problems after that.

**Comment by NikosEfthias** [comment]
I actually did all these 

Can you please reopen the issue?
Best Regards
Νικος Ευθειας

**Comment by NikosEfthias** [comment]
the email didnt have the image for some reason here it is ![](https://i.imgur.com/X83tWoN.png)

**Comment by NikosEfthias** [comment]
And here is the error obviously linter is marking but cnext reports no errors
![](https://i.imgur.com/e5QAPHU.png)

**Comment by NikosEfthias** [comment]
@lcd047

**Comment by lcd047** [comment]
1. Syntastic is using loclists, not quickfix lists.  You need to run `:lnext` and `:lprevious`, not `:cnext` and `:cprevious`.
2. There is a single error in your list, `:lnext` and `:lprevious` are pointless.

**Comment by NikosEfthias** [comment]
I see is there anyway syntactic can use the fix option of the linter if available ? 
eslint can fix for example the small errors like the one i created now

**Comment by lcd047** [comment]
No, syntastic never changes your files.
