### ISSUE TITLE
Does it support remote editing? (scp)

### ISSUE THREAD

**Issue by dhilst** [vim-syntastic/syntastic#2115]
I'm editing some python files at remote server. The editing goes through default vim `scp://user@host//path/to/file` feature. I can't get the syntax working with this. Any clue? I'm trying with python.

How can I debug?

Regards,

**Comment by lcd047** [comment]
Syntastic has nothing to do with syntax highlighting.  Also, according to `:h syntastic-netrw`, syntastic doesn't support checking files over network.

**Comment by dhilst** [comment]
By syntax I mean syntax checking. Thanks for the feedback!

**Comment by dhilst** [comment]
As workaround I'm using `sshfs`. It's easy to install and you don't have to configure nfs on server. The checker is working just fine!!!
