### ISSUE TITLE
I keep getting 'unexpected token kEND (Using Ruby 2.1 parser; configure using `TargetRubyVersion` parameter, under `AllCops`

### ISSUE THREAD

**Issue by ojbucao** [vim-syntastic/syntastic#2119]
My project is using ruby 2.3 and I have a .rubocop.yml with 2.3 as the target set.
For some reason, I keep getting this error when it comes to the new safe reference navigator syntax.
It seems like it's looking at some other yml file and doesn't see the one with the 2.3 target.

How do I check which yml file it's trying to use and how do i tell it to use the right one? #

**Comment by lcd047** [comment]
Please read the [FAQ](https://github.com/vim-syntastic/syntastic#faqruby).

**Comment by ojbucao** [comment]
Hi. I did but I'm still not able to resolve my issue.

**Comment by ojbucao** [comment]
I switched to using rbenv, activated the correct ruby version, installed rubocop in it and i'm still getting the same issue. When I run rubocop outside of vim against the file, it's fine.

**Comment by lcd047** [comment]
What happens when you run `:echo system('rubocop file.rb')` from Vim?
