### ISSUE TITLE
eslint the current edit(active) file, nor all project files

### ISSUE THREAD

**Issue by 15915940450** [vim-syntastic/syntastic#2120]
my vimrc:

Plugin 'vim-syntastic/syntastic'
  set statusline+=%#warningmsg#
  set statusline+=%{SyntasticStatuslineFlag()}
  set statusline+=%*

  let g:syntastic_always_populate_loc_list = 1
  let g:syntastic_auto_loc_list = 1
  let g:syntastic_check_on_open = 1
  let g:syntastic_check_on_wq = 0
  let g:syntastic_javascript_checkers = ['eslint']
  let g:syntastic_javascript_eslint_args=['--cache']
  let g:syntastic_javascript_eslint_exe = 'npm run lint --'

  "scripts": {
    "lint":"eslint .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack-dev-server --open",
    "build": "webpack"
  },

for example, when I edit foo.js and save, syntastic warn me that the file bar.js has some error. but I just want to see the only error about foo.js.

**Comment by lcd047** [comment]
> "lint":"eslint .",

"Doctor, it hurts when I do this".

**Comment by 15915940450** [comment]
but it lint all files, not the curent file that i am editing.

**Comment by lcd047** [comment]
Hence my comment above.  What do you think `eslint .` does?  Just drop the dot, syntastic adds the filename on its own.  You can save a lot of time by reading the manuals instead of pasting other people's configs from random blog posts.

**Comment by 15915940450** [comment]
so how should i config ? i know that "lint":"eslint ." is not my expectation, please.

**Comment by lcd047** [comment]
> Just drop the dot, syntastic adds the filename on its own.

**Comment by 15915940450** [comment]
well done! THANKS very much.

##### my vimrc
Plugin 'vim-syntastic/syntastic'
  set statusline+=%#warningmsg#
  set statusline+=%{SyntasticStatuslineFlag()}
  set statusline+=%*

  let g:syntastic_always_populate_loc_list = 1
  let g:syntastic_auto_loc_list = 1
  let g:syntastic_check_on_open = 1
  let g:syntastic_check_on_wq = 0

  "let g:syntastic_<filetype>_checkers = ['<checker-name>']

  "HTMLHint.................|syntastic-html-htmlhint|
  let g:syntastic_html_checkers = ['htmlhint']
  "ESLint...................|syntastic-javascript-eslint|
  let g:syntastic_javascript_checkers = ['eslint']
" }}}

I should read the manuals at the beginning time. Thanks.
