### ISSUE TITLE
ansible/ansible_lint can't parse version string

### ISSUE THREAD

**Issue by paxri01** [vim-syntastic/syntastic#2121]
I seem to be having an issue with Syntastic and ansible-lint.  Can you please advise how to resolve?

Thanks for the great code!

  **syntastic: error: checker ansible/ansible_lint: can't parse version string (abnormal termination?)**

**~/.vim/bundle/syntastic/syntax_checkers/ansible/ansible_lint.vim**
function! SyntaxCheckers_ansible_ansible_lint_IsAvailable() dict
    if !executable(self.getExec())
        return 0
    endif
    return syntastic#util#versionIsAtLeast(self.getVersion(), [2, 0, 4])
endfunction

**> ansible --version**
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

**Comment by lcd047** [comment]
> `ansible --version`

This checker tries to get the version of `ansible-lint`, not `ansible`.
