### ISSUE TITLE
ESLint check locks up vim for 2 seconds

### ISSUE THREAD

**Issue by ericandrewlewis** [vim-syntastic/syntastic#2122]
I've enabled ESLint, and notice it takes ~2 seconds to run on a 140 line file and locks Vim until it completes.

When I run it separately the ESLint run takes ~1.2 seconds.

Is it possible to not lock Vim while running a checker?

Thanks for the plugin btw, it is awesome 😄

**Comment by lcd047** [comment]
You can enable profiling (cf. `:h syntastic-profiling`), and find out most of the time is spent in ESLint and in Vim internals.  Or you can use a non-blocking plugin such as [ALE][ALE] instead of syntastic.

[ALE]: https://github.com/w0rp/ale
