### ISSUE TITLE
Environment variables in compiler flag configuration file.

### ISSUE THREAD

**Issue by namark** [vim-syntastic/syntastic#2127]
I'm using syntastic for c++, and I wanted to specify include paths in .syntastic_cpp_config based on my home directory, something like:
```-I$HOME/dev/library/includes```
but it won't work, and there are two problems I've found in syntastic#c#ReadConfig:
1. The path is shell-escaped preventing any further expansion of the variables, by shell or the compiler (not sure where that usually happens).
2. There is some regex based absolute/relative path handling (according to a comment, I myself can't read regex) which detects the example above as a relative path I guess, and prepends the filepath to it.
 
I've fixed this on my fork (https://github.com/namark/syntastic/commit/f2e87314fd488c2dc421f253b51cec7e7848b47c), by using shexpand and completely removing the absolute/relative path handling, since I put configuration files in the project root and both relative absolute paths work just fine, but  that would probably break some other use cases.

**Comment by lcd047** [comment]
Syntastic config files are deliberately simple: they have exactly one feature, which is documented in `:h syntastic-config-format`.  The point of having such a thing in syntastic in the first place is to avoid users the trouble of dealing with multi-layered quoting in `autocmd`s.

So basically you can set compiler options with `autocmd`s, or you can use config files.  Using `autocmd`s is the Vim way of doing things.  It allows you to use any valid Vim expressions, including environment variables, but you're responsible for making sure it gets passed unmolested to the linter.  Alternatively, config files take care of quoting, but they're dumb.  Neither approach is particularly fit to be used with C++, but they're mostly fine for other languages. _shrug_

**Comment by namark** [comment]
Well, arguably, my changes made things even more dumb and simple, and now it's perfectly suited for C++. _shrug_  

Are there any concrete usage examples where that relative path handling is necessary? All of the default options syntastic uses ```-I. -I.. -Iinclude -Iincludes -I../include -I../includes``` don't seem to care.  

Regarding quoting/escaping I just used ```shexpand``` which is right next to previously used ```shescape``` in utils.
 
The way I see it, the feature is there to allow per project configuration. What is the alternative of that using autocmd? 
 
clang_complete (even mentioned on top of the function in question) handles this properly, and it makes sense to reuse the same config file for both plugins. Also the file format being so simple makes it really easy to integrate with other tools (make in my case).

**Comment by lcd047** [comment]
> Well, arguably, my changes made things even more dumb and simple

And broken.  Now options starting with `#`, `%`, and `<` are expanded by Vim. :smile:

> Are there any concrete usage examples where that relative path handling is necessary?

Of course.  A simple example is a project with third-party modules, where each module needs to be compiled with its own includes.

> The way I see it, the feature is there to allow per project configuration.

Oh, thank you so much!  It's always an enriching experience to have somebody enlighten me about what my real intentions were when I added a feature. :smile:

**Comment by namark** [comment]
Sorry, didn't mean to question your authority. I just knew I broke something and wanted to know what exactly. Thanks for taking the time to answer my questions!
