### ISSUE TITLE
hlint unable to load .hs file inside Cygwin

### ISSUE THREAD

**Issue by chekkal** [vim-syntastic/syntastic#2130]
Haskell: hlint unable to load .hs file inside Cygwin
hlint.exe doesn't understand the unix file path in Cygwin it need to be converted into windows path.
This prevent syntastic from displaying warning for Haskell files

**Comment by lcd047** [comment]
Please explain what did you do, what did you expect to happen, and what happened instead.

**Comment by chekkal** [comment]
Inside  Cygwin the plugin does display warnings for .hs files using hlint.exe

**Comment by lcd047** [comment]
Please read `:h syntastic-shellslash`.  If that doesn't lead to a solution please actually explain what did you do, what did you expect to happen, and what happened instead.  Don't assume I can just look over your shoulder to see what you're doing.

**Comment by chekkal** [comment]
Inside Cygwin enviromnent with the following config in .vimrc

> _map <Leader>s :SyntasticToggleMode<CR>
> 
> set statusline+=%#warningmsg#
> set statusline+=%{SyntasticStatuslineFlag()}
> set statusline+=%*
> 
> let g:syntastic_always_populate_loc_list = 1
> let g:syntastic_auto_loc_list = 0
> let g:syntastic_check_on_open = 0
> let g:syntastic_check_on_wq = 0_

Open a .hs file having some warnings. Execute :SyntasticCheck
Error: No errors are displayed for this file
Expected: The lines with error need to be highlited

**Comment by chekkal** [comment]
> "file.hs" 1L, 6C
> syntastic: 10.926937: g:syntastic_version = '3.8.0-100 (Vim 800, CYGWIN_NT-6.3)'
> syntastic: 10.927183: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &she
> llxescape = ''
> syntastic: 10.927949: UpdateErrors: hlint
> syntastic: 10.928541: CacheErrors: hlint
> syntastic: 10.929565: g:syntastic_aggregate_errors = 0
> syntastic: 10.929973: getcwd() = '/cygdrive/s/training/cardano/cardano-sl'
> syntastic: 10.939242: CacheErrors: Invoking checker: haskell/hlint
> syntastic: 10.940180: SyntasticMake: called with options: {'postprocess': ['compressWhitespace'], 'errorformat': '%E%f:%l:%v: Error while reading hint file\, %m,%E%f:%l:%v: Error: %m,%W%f:%l
> :%v: Warning: %m,%W%f:%l:%v: Suggestion: %m,%C%m', 'defaults': {'vcol': 1}, 'makeprg': 'hlint /cygdrive/s/training/cardano/cardano-sl/file.hs'}
> syntastic: 11.009698: system: command run in 0.069086s
> syntastic: 11.009894: checker output: ['hlint.exe: Couldn''t find file: /cygdrive/s/training/cardano/cardano-sl/file.hs', '']
> syntastic: 11.010432: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'hlint.exe: Couldn''t find file: /cygdrive/s/trainin
> g/cardano/cardano-sl/file.hs'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
> syntastic: 11.012366: postprocess: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 1, 'nr': -1, 'type': '', 'pattern': '', 'text': 'hlint.exe: Couldn''t find file: /cygdrive/s/trainin
> g/cardano/cardano-sl/file.hs'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 1, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
> syntastic: 11.012626: getLocList: checker haskell/hlint returned 1
> syntastic: 11.012801: haskell/hlint raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 1, 'nr': -1, 'type': '', 'pattern': '', 'text': 'hlint.exe: Couldn''t find file: /cygdrive/s/t
> raining/cardano/cardano-sl/file.hs'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 1, 'nr': -1, 'type': '', 'pattern': '', 'text': ''}]
> syntastic: 11.013107: quiet_messages filter: {}
> syntastic: 11.013280: getLocList: checker haskell/hlint run in 0.073862s
> syntastic: 11.013605: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
> P

**Comment by lcd047** [comment]
This looks like a problem with `hlint`, not syntastic.  You need a Cygwin-aware version of `hlint`, if such a thing exists.  If it doesn't, well, syntastic won't add a workaound for it.  Dealing with Haskell is enough of a pain even without caring about interactions with Cygwin.  Sorry about that.
