### ISSUE TITLE
Vimlint not enabled when checking a vimscript

### ISSUE THREAD

**Issue by Braber01** [vim-syntastic/syntastic#2134]
I've been trying to for the past week to figure out how to get syntastic to enable vimlint could someone please help me

**Comment by lcd047** [comment]
Getting the obvious out of the way first: did you install the [`vim-vimlint`][vimlint] and [`vim-vimlparser`][vimlparser] plugins?

[vimlint]: https://github.com/syngan/vim-vimlint/
[vimlparser]: https://github.com/ynkdir/vim-vimlparser/

**Comment by Braber01** [comment]
I can't figure out how ot install vim-vimlparser but I do have vim-vimlint installed

**Comment by lcd047** [comment]
You can install `vim-vimlparser` the same way as `vim-vimlint`.  The `vimlint` checker in syntastic won't work without it.

**Comment by Braber01** [comment]
thanks I think I'm about to figure it out
