### ISSUE TITLE
Solidity syntax checker solc not working

### ISSUE THREAD

**Issue by mtodescato** [vim-syntastic/syntastic#2141]
The solidity checker is not visible to syntastic even if sol is setted as default for solidity files, and the solc.vim is in the right folder.
The :SyntasticInfo produces this:
```
Syntastic version: 3.8.0-101 (Vim 800, Linux)
Info for filetype: solidity
Global mode: active
Filetype solidity is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
```

**Comment by lcd047** [comment]
Not sure what you mean by "sol is [set] as default for solidity files", or by "solc.vim is in the right folder".  According to the [FAQ][FAQ] syntastic only cares about `solc` being in your `$PATH`, as seen by Vim.

[FAQ]: https://github.com/vim-syntastic/syntastic#faqinfo

**Comment by mtodescato** [comment]
For set i mean that it shoud be active becuse in the registry.vim is set as default for solidity files, for the right folder is my bad, i meant it is where all the other checkers are in .vim/bundle/syntastic/syntax_checkers and the other checkers are working

**Comment by lcd047** [comment]
You should set `syntastic_solidity_checkers` instead of relying on the registry.  Your problem is elsewhere anyway, since no checker is seen as __available__.

**Comment by mtodescato** [comment]
Apparently the solidity compiler from npm is unable to work with solc.vim, becuase with some little changes i can make him see it but it doesn't work

**Comment by lcd047** [comment]
According to the manual (`:h syntastic-solidity-solc`), the `solc` supported by syntastic is [written in C][solc].

[solc]: https://github.com/ethereum/solidity

**Comment by mtodescato** [comment]
sorry didn't noticed that npm solc was only a subset of the c++ solc, in fact while installing it they had the same name

**Comment by lcd047** [comment]
A few other checkers are prone to similar name conflicts, which is why you should always check the list of supported checkers in the manual (`:h syntastic-checkers`). _shrug_
