### ISSUE TITLE
some weird text appears if g:syntastic_check_on_open = 1 in vim

### ISSUE THREAD

**Issue by rpolasek** [vim-syntastic/syntastic#2142]
see an enclosed screen-shot 
![vim_weird](https://user-images.githubusercontent.com/1434826/35963373-cf09dc90-0cb4-11e8-92e8-53e34dd7beae.jpg)

it disappears when i comment "g:syntastic_check_on_open = 1" in my .vimrc

note: using gentoo, xterm-331 and vim-8.0.1428 but i've tried many other versions to check if it helps or not. the only one work-around afaik is to comment mentioned line above.

**Comment by lcd047** [comment]
Please see #822.
