### ISSUE TITLE
C++17

### ISSUE THREAD

**Issue by Debabrata557** [vim-syntastic/syntastic#2144]
What should i do to make syntastic  work for c++17?

**Comment by lcd047** [comment]
You should start by reading the manual.  First `:h syntastic`, then `:h syntastic-cpp-gcc`.

**Comment by Debabrata557** [comment]
I have read that.I changed in my vimrc let g:syntastic_cpp_compiler_options = ' -std=c++17x'.
But to no good.

**Comment by lcd047** [comment]
According to the manual:

> You can see the final outcome of setting these variables in the debug logs (cf. `syntastic-config-debug`).

**Comment by offa** [comment]
@Debabrata557 

> let g:syntastic_cpp_compiler_options = ' -std=c++17x'.

The flag is either `-std=c++17` or `-std=c++1z`.
