### ISSUE TITLE
feature request: ignore absence of .h file

### ISSUE THREAD

**Issue by 93a** [vim-syntastic/syntastic#2146]
I'm currently writing a CUDA project which is supposed to be executed at a remote server because i don't have CUDA library locally.

I've read here in some issue that absence of header file is critical error and gcc just stops further parsing, but i wonder if there any chance of implementing a tricky feature that would allow not to check presence of manually marked libraries?

**Comment by lcd047** [comment]
That isn't possible, sorry.  Syntastic doesn't know about C syntax, include files, and the like.  Syntastic doesn't even care about the contents of your files, all it does is delegate the work to external linters, and parse back the results.  So your options are to either convince `gcc` not to bail out abruptly when it can't find a header, create dummy header files (something along the lines of `touch /path/to/foo.h`), or use some other compiler.
