### ISSUE TITLE
compile_commands.json Support

### ISSUE THREAD

**Issue by umitkablan** [vim-syntastic/syntastic#2147]
Hi,

Is compile_commands.json parsing for compile arguments supported? If not, would it be easy to support it / have utilities for it? I guess you already know but, briefly, you can get cmake to populate build_commands.json file under its build directory which will have command line of each file's compilation. This will save us from the burden of defining include paths - would be very helpful for large projects.

Best,

**Comment by lcd047** [comment]
> Is compile_commands.json parsing for compile arguments supported?

Parsing `compile_commands.json` by syntastic is not supported.

Some of the C/C++ checkers (namely `clang_check`, `clang_tidy`, and `oclint`) can use compilation databases.  Read the manual (`:h syntastic-cpp-clang_check` etc.) to find out how.

Adding support for compilation databases to other checkers that don't support that natively is neither planned, nor feasible.

**Comment by umitkablan** [comment]
Thanks for your response!
Actually I searched your repo for 'compile_commands.json' - I believe it's the wrong keyword that it didn't hit anything..

I couldn't understand clearly, is it enough only clearing the *_post_args variable(s)? Where does it search for that file? What if it's under some build/Debug?

**Comment by lcd047** [comment]
> I couldn't understand clearly, is it enough only clearing the *_post_args variable(s)?

As I said, syntastic itself doesn't care, it's the linters themselves that implement that functionality, and they insist on a particular incantation for that.  So you can read the manuals for `clang_check`, `clang_tidy`, and `oclint`, find out that incantation, and reproduce it within syntastic (see `:h syntastic-debug`), or you can read the entries in syntastic's manual for the corresponding checkers and use the recipes provided there.  Either way, it's about keeping the linters happy, not about syntastic.

> Where does it search for that file? What if it's under some build/Debug?

You'll have to read the manuals of the linters mentioned above to find out the details.  Syntastic itself doesn't pay attention to that file.
