### ISSUE TITLE
`g:syntastic_<filetype>_<checker-name>_exe` not working as expected

### ISSUE THREAD

**Issue by JamyGolden** [vim-syntastic/syntastic#2151]
This is a more a question and a possible request: When setting an `_exe` variable `g:syntastic_<filetype>_<checker-name>_exe`, it seems that a global bin is still required. In the case of eslint and javascript:
```
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exe = 'npm run lint --'
```
If I don't have `eslint` installed globally, it doesn't appear under Syntastic's Available checkers. If I do have it installed, it works correctly and Syntastic executes `npm run lint--` as expected.

It seems to me that a global install of `eslint` is not required once `g:syntastic_javascript_eslint_exe` is set. Is there a way around having to have `eslint` globally installed to in order to add `eslint` to Syntastic's available checkers?

**Comment by lcd047** [comment]
Please see #1692.  Refer to the [guide][guide] for the difference between `exe` and `exec` (a _brilliant_ choice of names, isn't it).

[guide]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide

**Comment by JamyGolden** [comment]
Thanks very much!
