### ISSUE TITLE
Using tslint for javascript

### ISSUE THREAD

**Issue by mMontu** [vim-syntastic/syntastic#2157]
I'm new to Syntastic, and I'm trying to use it along tslint to analyze javascript files (which is possible through the [`jsRules`](https://palantir.github.io/tslint/usage/configuration/) and works fine when called directly in the shell).

I've tried the following, with no luck:

    let g:syntastic_javascript_checkers = ['tslint']

As Syntastic + tslint are working fine for typescript files, and the filetype is correctly set, I guess it is missing the template for javascript + tslint (in special because tslint isn't present at `:help syntastic-checkers-javascript`).
If this is the case, is there any documentation explaining how to do it?

**Comment by lcd047** [comment]
According to `:h :SyntasticCheck`:
> You can also run checkers for filetypes different from the current filetype by qualifying their names with their respective filetypes, like this: `<filetype>/<checker>`.

Consequently, try:
```vim
let g:syntastic_javascript_checkers = ['typescript/tslint']
```
Writing checkers is documented in the [wiki][guide].

[guide]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide

**Comment by mMontu** [comment]
Indeed, I've read both help files but somehow missed this bit.
Including the filetype prefix makes it work.

Thanks for the lighting fast response!
