### ISSUE TITLE
mandoc

### ISSUE THREAD

**Issue by grylem** [vim-syntastic/syntastic#2159]
mandoc don't report any warning or errors
mandoc v 1.4.3
vim 7.4 macOS.

**Comment by lcd047** [comment]
Your `mandoc` is probably not the `mandoc` syntastic expects.  Please open your test file, set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output.

**Comment by grylem** [comment]
which version i should use?
[debug.txt](https://github.com/vim-syntastic/syntastic/files/1845491/debug.txt)

**Comment by lcd047** [comment]
Your logs show syntastic working fine.

**Comment by grylem** [comment]
In debug mode syntastic show for me one error(only text string, no symbols) for man page only after run vim. If i scroll down(return) this message lost and no any errors/warning messages.
If i select checker igor - all fine.

**Comment by lcd047** [comment]
Like I said: your logs show `mandoc` finding many errors and warnings, and syntastic recognizing them.  If you have trouble browsing them consider using the recommended settings (`:h syntastic-recommended`).  If you did use the recommended settings then you have some other plugin interfering with syntastic.
