### ISSUE TITLE
How to prevent Syntastic looking into /node_modules?

### ISSUE THREAD

**Issue by stevensgarcia** [vim-syntastic/syntastic#2160]
Hi,

After I save a file in vim, I can't do anything for 2-3 minutes because syntastic is analizing that file. Once the loc window comes, it brings errors in current file, but also at the entire node_modules modules.

**Could you please address me on how to do Syntastic only looking on files I'm editing?**

![alt text](https://i.imgur.com/P7U1fAy.png  ":Errors")

FYI: I'm working in typescript, angular5 project created with angular-cli generator, and also have eslint installed globally with this config:

**eslint.json**
```
{
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "node": true
  },
  "parser": "typescript-eslint-parser",
  "extends": "eslint:recommended",
  "parserOptions": {
    "sourceType": "module"
  },
  "rules": {
    "indent": [
      "error",
            2
    ],
    "linebreak-style": [
      "error",
      "unix"
    ],
    "quotes": [
      "error",
      "single"
    ],
    "no-console": 0
  },
  "globals": {
    "angular": true,
    "describe": true,
    "beforeEach": true,
    "before": true,
    "afterEach": true,
    "after": true,
    "it": true,
    "expect": true,
    "$": true,
    "browser": true,
    "by": true,
    "element": true,
    "jasmine": true,
    "inject": true
  }
}
```

**:SyntasticInfo**
```
Syntastic version: 3.7.0-31 (Vim 800, Darwin)
Info for filetype: typescript
Global mode: active
Filetype typescript is active
The current file will be checked automatically
Available checker: tsc
Currently enabled checker: tsc
```

**.vimrc**
```
" Syntastic populate location list with errors
let g:syntastic_always_populate_loc_list = 1
nnoremap <leader>ss :SyntasticToggle<CR>

let g:syntastic_auto_loc_list = 0
let g:syntastic_loc_list_height = 4

let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

let g:syntastic_aggregate_errors = 1
let g:syntastic_id_checkers = 1

let g:syntastic_error_symbol = "✗"
let g:syntastic_warning_symbol = "⚠"

let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_typescript_checkers = ['tsc']
let g:syntastic_html_checkers = ['jshint'] 
let g:syntastic_css_checkers = ['csslint']
```

Thanks in advanced =)

**Comment by lcd047** [comment]
> I can't do anything for 2-3 minutes because syntastic is analizing that file.

You might consider using an async plugin instead of syntastic, such as [ALE](https://github.com/w0rp/ale).

> Once the loc window comes, it brings errors in current file, but also at the entire node_modules modules.

Don't shoot the messenger, syntastic just shows the errors produced by your linters.  If you don't care to see some of these errors either configure said linters not to produce them in the first place, or use `syntastic_quiet_messages` to tell syntastic to remove them.  See `:h 'syntastic_quiet_messages'`.

> `let g:syntastic_typescript_checkers = ['tsc']`

Checker `tsc` has been removed from syntastic a while ago (not that that has anything to do with your question; just noting `tsc` is not supported).

**Comment by IanEdington** [comment]
You could also try (tsuquyomi)[https://github.com/Quramy/tsuquyomi]. It supports tsc style errors but filters them on a per file basis. Also integrates well with syntastic.

**Comment by stevensgarcia** [comment]
@lcd047 Thanks for your support. Your answers addressed me to do a research base on those, and I fixed perfomance issue doing the following:

> You might consider using an async plugin instead of syntastic, such as ALE.

I found **Neomake** pretty useful and installed in conjuntion with Syntastic instead ALE

> If  you don't care to see some of these errors either configure said linters not to produce them in the first place, or use syntastic_quiet_messages

Went to the manual and found `let g:syntastic_quiet_messages = { filters..}` was quite useful.

@IanEdington thanks for your suggestion. I installed **tsuquyomi** keeping **tsc** and **Neomake** and now my **VIM terminal** behaves like a ferrari.

Thanks guys!
