### ISSUE TITLE
scalastyle errorformat is incomplete

### ISSUE THREAD

**Issue by fmv1992** [vim-syntastic/syntastic#2162]
First and foremost thanks for the plugin!

The `errorformat` for scalastyle is incomplete:

    $ cat a.scala
    package constants
    object Const {

    }

    val xxx: Int = 1.0

    $ scalastyle -jar scalastyle_2.12-1.0.0-batch.jar -c scalastyle_config.xml a.scala
    error file=/tmp/a.scala message=expected class or object definition
    Processed 1 file(s)
    Found 1 errors
    Found 0 warnings
    Finished in 357 ms

From within the file:

    syntastic: 1.634872: CacheErrors: Invoking checker: scala/scalastyle
    syntastic: 1.635354: SyntasticMake: called with options: {'subtype': 'Style', 'errorformat': '%trror file=%f message=%m line=%l column=%c,%trror file=%f message=%m line=%l,
    %tarning file=%f message=%m line=%l column=%c,%tarning file=%f message=%m line=%l', 'makeprg': 'scalastyle -jar scalastyle_2.12-1.0.0-batch.jar -c scalastyle_config.xml a.scala', 'returns': [0, 1]}
    syntastic: 2.187599: system: command run in 0.551897s
    syntastic: 2.188784: getLocList: checker scala/scalastyle returned 0
    syntastic: 2.189224: getLocList: checker scala/scalastyle run in 0.554239s

And I get zero errors/warninigs. See that 'errorformat' does not have:

        '%trror file=%f message=%m'

I have tried setting `g:syntastic_scala_errorformat` but it didn't work. Any workarounds until this issue is solved?

**Comment by lcd047** [comment]
> I get zero errors/warninigs.

Sadly, messages without line numbers are not that useful to syntastic.

**Comment by fmv1992** [comment]
I agree but maybe for completeness they should be included because they are still useful. An idea would be to assign them the line 1 or line zero (if possible) since they are probably module wide.

**Comment by lcd047** [comment]
Messages without line numbers produce conflicts with the cursor notifier (the thing that shows messages on the last line when you move around the file), which eventually leads to Vim crashing.  This is a limitation of syntastic's design, and it has no easy fix. _shrug_

**Comment by fmv1992** [comment]
well no problem

thanks for the fast support
