### ISSUE TITLE
Elm

### ISSUE THREAD

**Issue by ShalokShalom** [vim-syntastic/syntastic#2167]
There is Elm support, you may want to add it: https://github.com/ElmCast/elm-vim

**Comment by lcd047** [comment]
There is no point in moving it to syntastic.  It should work out of the box once you install both syntastic and `elm-vim`, and external checkers are [encouraged][external].  Also the checker itself is tied to `elm-vim`, it doesn't work stand-alone.

[external]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide#external

**Comment by ShalokShalom** [comment]
I mean in the documentation

**Comment by lcd047** [comment]
I'm not trying to collect links for _all_ external checkers (among other reasons, the quality of these things varies greatly).  I expect whoever cares about about ELM and Vim will find `elm-vim` soon enough.

**Comment by ShalokShalom** [comment]
Ok, fair enough. Let your documentation lack essential things for no reason. Good to know, how to work :slightly_smiling_face:
