### ISSUE TITLE
Disabling unwanted space error in LaTeX

### ISSUE THREAD

**Issue by SethGower** [vim-syntastic/syntastic#2169]
I have been looking at other issues, but can't seem to find a fix to this one. I am getting an error in latex where syntastic shows me an error saying `HW12.tex | 10 error | possible unwanted space at '{'` when I have an open curly brace. It doesn't highlight a certain character, so I don't know where the space is. 

Here is the output when I run `:SyntasticInfo`

```
Syntastic version: 3.8.0-110 (Vim 800, Neovim, Linux)
Info for filetype: tex
Global mode: active
Filetype tex is active
The current file will be checked automatically
Available checkers: chktex lacheck
Currently enabled checkers: lacheck chktex
```
Is there anyway to disable this specific error, since it doesn't prevent the compiler from working?

**Comment by lcd047** [comment]
`possible unwanted space at '{'` is a `lacheck` message, and there doesn't seem to be any way to disable it on `lacheck`'s side.  You can kill it on syntastic's side with `quiet_messages`:
```vim
let g:syntastic_tex_lacheck_quiet_messages = { 'regex': '\Vpossible unwanted space at' }
```
Sadly, useful linters for LaTeX are still missing.

**Comment by SethGower** [comment]
Ok, thanks. That worked.
