### ISSUE TITLE
Process hanged when :w in Win-Gvim for .sh file.

### ISSUE THREAD

**Issue by azarashichop** [vim-syntastic/syntastic#2171]
I use Windows Gvim.
I wrote linux shell script file, and when writing buffer to file, background process hanged.
![image](https://user-images.githubusercontent.com/8552118/38912276-51b01cf0-430f-11e8-8864-a8a9864e3967.png)

After closing cmd window, I can use vim normally.

1. So far, issue occur only shell-script file.
2. When removing shebang, issue disappear.
(#!/bin/bash)

**Comment by lcd047** [comment]
1. Syntastic doesn't run background processes.  It always runs linters in foreground.
2. You aren't supposed to run syntastic with the defaults.  Syntastic can't (and doesn't attempt to) check that what you're trying to do makes sense.  It's up to you to understand what you're doing and make it's actually useful.  In your case running `bash` under `cmd` isn't useful. _shrug_

**Comment by azarashichop** [comment]
Hi lcd047
Thanks for your reply.
I tested bash command on CMD.
And there was guide to installation of WSL-bash.
I removed WSL on my PC, and issue is clear!
