### ISSUE TITLE
Unable to load files in location window (wrong path calculated) - Rust Cargo workspace

### ISSUE THREAD

**Issue by MarkSwanson** [vim-syntastic/syntastic#2176]
My Rust project has:
Cargo.toml
--> src/lib.rs
--> projectB
----> Cargo.toml
----> src/bin/a.rs
----> src/bin/b.rs <-- the b.rs file has errors

If I'm at the root of the project and do: vi projectB/src/bin/a.rs then the errors in the location list work as expected - I just select one and the correct file (projectB/src/bin/b.rs) opens. Great!

Instead, if I do this:
$ cd projectB/src/bin
$ vi a.rs

Then the location list will have incorrect paths - they incorrectly have: projectB/src/bin/b.rs
This isn't correct because my Current Working Dir is .../projectB/src/bin/
(results in ENOTFOUND: .../projectB/src/bin/projectB/src/bin/b.rs)

I suspect the Current Working Dir isn't being taken into consideration...

Solution: merge the location list path with the current working dir.
Or, perhaps create the location list correctly (taking CWD into account).

**Comment by lcd047** [comment]
Core syntastic has no checker for either Rust or Cargo.  You probably want the [rust.vim project][rust].

[rust]: https://github.com/rust-lang/rust.vim
