### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by kyla963** [vim-syntastic/syntastic#2178]
I don't remember ever installing syntastic, the first I heard of it was when I tried to install ale, when I got a notification saying they interfere with one another. This does not appear on my plug list. I don't know where it's stored. I'm sure it's a great program, but how do I get rid of it?

**Comment by lcd047** [comment]
> I don't remember ever installing syntastic

That makes two of us, I don't remember installing it on your machine, either. :smile: What makes you think you have it installed in the first place?
