### ISSUE TITLE
Configuration file look up doesn't work since commit 6d7c0b3

### ISSUE THREAD

**Issue by betonniere** [vim-syntastic/syntastic#2179]
Since commit 6d7c0b3 _Security: clear defaults for config file names (cf. #2170)._  **syntastic_<file_type>_config** files (syntastic_cpp_config in my case) are ignored.

**Comment by lcd047** [comment]
Please explain what did you do, what did you expect to happen, and what happened instead.

**Comment by betonniere** [comment]
In this [tarball](https://github.com/vim-syntastic/syntastic/files/2038259/Bug2179.tar.gz) you can find a **main.cpp** file including **b.hpp** (#include "b.hpp") located in a different folder. To instruct syntastic where to find included files, I've dropped a configuration file (**.syntastic_cpp_config**) with a **-Ib** directive in the root folder:

Bug2179
├── a
│   └── **main.cpp**
├── b
│   └── **b.hpp**
└── **.syntastic_cpp_config**

From commit 6d7c0b3, syntastic gets confused and display a syntax error in the Vim's location list:
**_fatal error: b.hpp: No such file or directory_** while this false alert isn't raised prior to this commit.

**Comment by lcd047** [comment]
After the commit you mentioned in your first post you need to set `syntastic_cpp_config_file` explicitly to the name of the configuration file.  To avoid the security problem you are strongly advised to use a different name than `.syntastic_cpp_config`.

**Comment by betonniere** [comment]
Ok, got it. Your suggestion works.
Sorry for the inconvenience.
