### ISSUE TITLE
systastic stopped working on Vim 8.1

### ISSUE THREAD

**Issue by fcomida** [vim-syntastic/syntastic#2184]
I updated to Vim 8.1.35 on Fedora 28 and syntastic isn't working anymore.
I set "let g:syntastic_debug = 1" and I get:

syntastic: 2.102276: g:syntastic_version = '3.9.0-6 (Vim 801, Linux)'                                                                                                   
syntastic: 2.102667: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '',
 &autochdir = 0, &shellxescape = ''                                                                                                                                     
syntastic: 2.103801: UpdateErrors (auto): default checkers                                                                                                              
syntastic: 2.104427: _skip_file: skipping checks

**Comment by lcd047** [comment]
What file were you trying to check?  What is the output of `:SyntasticInfo` for that file?  Please explain exactly what did you do.

**Comment by fcomida** [comment]
@lcd047 I commented this out in .vimrc and it's working now: let g:syntastic_ignore_files = ['\m\c\ui_*.*', '\m\c\config.h$', '\m\c\global*.*$']
They are c++ files.

**Comment by lcd047** [comment]
Well, if you aren't going to answer my questions then you're on your own. _shrug_

**Comment by fcomida** [comment]
Syntastic version: 3.9.0-6 (Vim 801, Linux, GUI)                                                                                                                        
Info for filetype: cpp                                                                                                                                                  
Global mode: active                                                                                                                                                     
Filetype cpp is active                                                                                                                                                  
The current file will be checked automatically                                                                                                                          
Available checkers: avrgcc clang_check clang_tidy cppcheck flawfinder gcc                                                                                               
Currently enabled checker: gcc  

Again with g:syntastic_ignore_files active all files are skipped.
I want to ignore those files that are auto generated by the compiler, I have #include "global.h" #include "config.h" and many #include "ui_XXXXX.h".
My configuration for ignore_files worked with Vim 8.01 though.

**Comment by fcomida** [comment]
The build system generates config.h, global.h and ui_XXXXX.h files which are included by other .cpp files.
If those files haven't been yet generated,  Syntastic will rightly tell they are missing. I was trying to tell it to just ignore them and the regexes I came out with were working before for some reason.
I'll try better regexes, thank you very much.

**Comment by lcd047** [comment]
`g:syntastic_ignore_files` uses __regular expressions__, not shell patterns.  That's the same syntax you use in Vim's `s/.../.../`.

**Comment by fcomida** [comment]
@lcd047 yeah I know. My problem is try matching #include "<A_DIRECTORY>/ui_<A_NAME>.h"
Those ui_XXXXX.h files are generated inside different directories.
Back to study regexes :)

**Comment by lcd047** [comment]
Not tested:
```vim
let g:syntastic_ignore_files = ['\m\c\<ui_[^/]*\.h$', '\m\c\<config\.h$', '\m\c\<global[^/]*$']
```

**Comment by fcomida** [comment]
@lcd047 That seems to work. Thanks again for your help :+1: wonderful
