### ISSUE TITLE
Syntastic doesn't detect specified checkers for Jenkinsfile filetype

### ISSUE THREAD

**Issue by hoylemd** [vim-syntastic/syntastic#2189]
I have a script that does Jenkinsfile linting against a local jenkins container, and I'm trying to integrate it with Syntastic.

I did

`let g:syntastic_Jenkinsfile_checkers = ['path_to_script']` (since 'Jenkinsfile' is the result of `set ft` when the current buffer contains a Jenkinsfile), but when I do `:SyntasticInfo`, I get

```
Syntastic version: 3.8.0-94 (Vim 704, Darwin)
Info for filetype: Jenkinsfile
Global mode: active
Filetype Jenkinsfile is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
```

Do I need to do something else to make syntastic aware of the checker?  I tried to figure it out from the docs, but I couldn't.

**Comment by lcd047** [comment]
There is a [guide][guide] for writing syntastic checkers.  Beyond that, I can answer a few punctual questions.  But I won't attempt to guess what you did and why it doesn't work.  First of all are you sure you want to write a syntastic checker and not a Vim compiler plugin (cf. `:h compiler-select`)?

[guide]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide

**Comment by hoylemd** [comment]
I don't know what you mean by a vim compiler plugin.  I'm using syntastic to do auto-linting, so I figured the most straightforward way to do that is to integrate with the tools that I know best (even if that isn't very good).

I'll look at that guide. Thanks.

**Comment by lcd047** [comment]
> I don't know what you mean by a vim compiler plugin.

It's a Vim concept described in Vim's manual (specifically at `:h compiler-select`).

**Comment by hoylemd** [comment]
Turns out I was vastly underestimating how easy it is to add new checkers.  I'll just have to do it manually.
