### ISSUE TITLE
how to reset error_symbol & warning_symbol in .vimrc.local file

### ISSUE THREAD

**Issue by csxvzzzi** [vim-syntastic/syntastic#2196]
I add this code to .vimrc.local file
```
let g:_SYNTASTIC_DEFAULTS = {
        \ 'error_symbol':             '•',
   \ 'warning_symbol':           '•'
    \ }
```
but didn't work

**Comment by lcd047** [comment]
Why did you expect this to work?

Setting error and warning symbols is documented in the manual: `:h 'syntastic_error_symbol'`.

**Comment by csxvzzzi** [comment]
@lcd047 Thany you!
