### ISSUE TITLE
GCC standard

### ISSUE THREAD

**Issue by EvanCarroll** [vim-syntastic/syntastic#2198]
From the docs,
```

'g:syntastic_c_compiler_options'
Type: string
Default: "-std=gnu99"
```

Should this be gnu99? This is not the standard in GCC. Though perhaps at one time this would take it out of gnu89, now it's holding it back from gnu11, from `man gcc`

       gnu11
       gnu1x
           GNU dialect of ISO C11.  This is the default for C code.  The name gnu1x is deprecated.

**Comment by lcd047** [comment]
You aren't supposed to use syntastic with the defaults. _shrug_
