### ISSUE TITLE
syntastic_check_on_open outputs garbage to the terminal before loading

### ISSUE THREAD

**Issue by MrHuds0n** [vim-syntastic/syntastic#2205]
This sounds like something that may have been resolved already but I couldn't find it here.

When I open a file with `syntastic_check_on_open` enabled, something like this outputs to the terminal. If the first line of the file I'm editing is not long enough to cover this, this random garbage stays there until I redraw the terminal.

![2018-08-05-190036_954x1045_scrot](https://user-images.githubusercontent.com/1941971/43688162-39661804-98e4-11e8-991c-09b4b1eed520.png)

Do you know of any solutions to this?

**Comment by lcd047** [comment]
> Do you know of any solutions to this?

Not really.  The problem is not syntastic, please see #822.

A few similar problems have been fixed recently in Vim.  I don't know if these fixes are relevant for syntastic, but it's worth a try.  So perhaps consider trying the latest version of Vim.
