### ISSUE TITLE
Segfault when using option g:syntastic_auto_loc_list

### ISSUE THREAD

**Issue by rsaill** [vim-syntastic/syntastic#2207]
Vim crashes (segfault) when I do the following:
 - open a file such that all errors reported by the checker are in another file.
 - :SyntasticCheck (this opens a loc list)
 - move on the first line of the loc list
 - press enter

If I comment the line 'let g:syntastic_auto_loc_list = 1' in my .vimrc and use :Errors to open the loc list the problem does not occur.

Remark: I am using a custom checker.

**Comment by lcd047** [comment]
This looks like the bug described at #1127.  It's a bug in Vim, not in syntastic.  I'm no longer following Vim development that closely these days, but I think there has been some work done recently in the  quickfix code that might be relevant here.  So you might try installing the latest version of Vim, and, if the problem persists, post a stack trace to `vim_dev`.

**Comment by rsaill** [comment]
I get the same pb with vim 8.1.0279.
I also tried neovim and got the error 'E926 Current location list was changed' instead of the crash.

Anyway thanks for your answer. I'll read the thread you mentioned and see if I report an issue to vim.
