### ISSUE TITLE
Missing ERROR

### ISSUE THREAD

**Issue by HaogeL** [vim-syntastic/syntastic#2217]
Hi,
I am using vlog to check systemverilog syntax. The issue I found is that Syntactic misses ERROR.
Here is the reported Warning in VIM:
![image](https://user-images.githubusercontent.com/44329058/47261316-d82c5100-d4cc-11e8-8b21-183d456b9eb6.png)
Here is the result by running checker in CMD:
![image](https://user-images.githubusercontent.com/44329058/47261323-0ca00d00-d4cd-11e8-9f12-646d9f3ea0d4.png)
Obviously, Syntactic hits the first **Warning**, but misses the second **Error (suppressible)**.
It can detect errors, but not for this one. Is it because word **Error** followed by (suppressible)?
Thank you in advance.

**Comment by lcd047** [comment]
> It can detect errors, but not for this one. Is it because word **Error** followed by (suppressible)?

That would be my first guess, yes.  However, you're using a checker named `vlog`, which is not part of syntastic.  So please direct your report to the maintainers of whatever plugin provides the `vlog` checker.
