### ISSUE TITLE
eslint warnings are confusing the IsAvailable check

### ISSUE THREAD

**Issue by ccraciun** [vim-syntastic/syntastic#2219]
For certain configurations eslint now emits warnings which confuse the version check:
```
Syntastic version: 3.8.0-51 (Vim 801, Darwin, GUI)
Info for filetype: javascript.jsx
Global mode: active
Passive filetypes: go python
Filetype javascript.jsx is active
The current file will be checked automatically
syntastic: error: checker output:
(node:64056) ExperimentalWarning: The ESM module loader is experimental.
v4.10.0
syntastic: error: checker javascript/eslint: can't parse version string (abnormal termination?)
Available checker: flow
Currently enabled checkers: -
Press ENTER or type command to continue
```

**Comment by lcd047** [comment]
Sorry, working with non-release versions of linters is not supported.  Experimental features can print junk messages for three weeks, then go back to being silent, while workarounds in syntastic would stay forever.  I don't want to go there.  _You_ don't want me to go there, either.

It's up to you to make sure linters don't print junk messages.  You could uninstall the offending module, or you could write a wrapper around `eslint` that just kills the message.  Sorry for being an asshole. _shrug_
