### ISSUE TITLE
Kuniwak/vint linter suddenly quit working 

### ISSUE THREAD

**Issue by Cbhihe** [vim-syntastic/syntastic#2221]
[Vim 8.0.1 / Syntastic 3.9.0-19 / Vundle 0.5 / vint 0.3.19 on Arch Linux]

`Kuniwak/vint`my vim linter of choice seems to be broken and I don't quite understand why.
It's been working fine in its present configuration, until this morning.

I tried replacing it with 'syngan/vim-vimlint', cloing the Github repo, and declaring the plugin in the Vundle section inside `~/.vimrc`  and the substitute works poorly, but normally. This however barely qualifies as a stop-gap.  I want to return to 'Kuniwak/vint' if at all possible. 

The rest of this post concerns ***'Kuniwak/vint'*** 

I get the following error message, when I write any buffer identified
as 'vim' filetype to disk:

    `syntastic: warning: checker vim/vint: unrecognized error format (crashed checker?)`

It is also the content of `:messages` in buffer.  See below for pasted full content.

"Startpage"-ing it returned zero relevant result.

The pertinent `~/.vimrc` section ...
```
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'Valloric/YouCompleteMe.git'
Plugin 'Townk/vim-autoclose' 
Plugin 'dougireton/vim-chef'
Plugin 'jimhester/lintr'
Plugin 'vim-scripts/LaTeX-Suite-aka-Vim-LaTeX'
Plugin 'Kuniwak/vint'
call vundle#end()
filetype plugin indent on
let g:syntastic_vim_checkers = ['vint']
let g:no_vim_maps = 0
```
The vint executable is located at `/usr/bin/vint`.
Issuing ex cmd `:SyntasticInfo [vim]` does yield "vint" and the correct filetype, "vim".

Syntastic is aware of $USER $PATH:
```
      :echo syntastic#util#system('echo "$PATH"')
      /usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/bin:/opt/scripts
```
The runtime path includes Vundle:
```
:set runtimepath?
runtimepath=~/.vim,~/.vim/bundle/Vundle.vim,~/.vim/bundle/syntastic,~/.vim/bundle/YouCompleteMe,~/.vim/bundle/vim-autoclose,~/.vim/bundle/vim-chef,~/.vim/bundle/lintr,~/.vim/bundle/LaTeX-Suite-aka-Vim-LaTeX,~/.vim/bundle/vint,/usr/share/vim/vimfiles,/usr/share/vim/vim81,/usr/share/vim/vim81/pack/dist/opt/matchit,/usr/share/vim/vimfiles/after,~/.vim/after,~.vim/bundle/Vundle.vim,~/.vim/bundle/Vundle.vim/after,~/.vim/bundle/syntastic/after,~/.vim/bundle/YouCompleteMe/after,~/.vim/bundle/vim-autoclose/after,~/.vim/bundle/vim-chef/after,~/.vim/bundle/lintr/after,~/.vim/bundle/LaTeX-Suite-aka-Vim-LaTeX/after,~/.vim/bundle/vint/after
```
The cloned git repo in `~/.vim/bundle/Vundle.vim` is up to date. 
My complete ~/.vimrc is [here](https://www.github.com/Cbhihe/vim).
           
The content of `:messages`  is:

> syntastic: 40.151881: g:syntastic_version = '3.9.0-19 (Vim 801, Linux, GUI)'                                           
> syntastic: 40.152412: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellred
> ir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = '', u:shell = '/usr/bin/bash' (!)  
> syntastic: 40.154047: UpdateErrors (auto): default checkers                                                            
> syntastic: 40.155360: CacheErrors: default checkers                                                                    
> syntastic: 40.157333: g:syntastic_aggregate_errors = 0                                                                 
> syntastic: 40.157572: getcwd() = '/home/ckb/.vim/bundle'                                                               
> syntastic: 40.157909: CacheErrors: Invoking checker: vim/vint                                                          
> syntastic: 40.158280: SyntasticMake: called with options: {'preprocess': 'vint', 'errorformat': '%f:%l:%c:%t: %m', 'mak
> eprg': 'vint /home/ckb/.vimrc --json', 'returns': [0, 1]}                                                              
> syntastic: 40.357113: system: command run in 0.198583s                                                                 
> syntastic: 40.357309: checker output: ['Traceback (most recent call last):', '  File "/usr/bin/vint", line 11, in <modu
> le>', '    load_entry_point(''vim-vint==0.3.19'', ''console_scripts'', ''vint'')()', '  File "/usr/lib/python3.7/site-p
> ackages/vint/__init__.py", line 11, in main', '    init_cli()', '  File "/usr/lib/python3.7/site-packages/vint/bootstra
> p.py", line 22, in init_cli', '    cli.start()', '  File "/usr/lib/python3.7/site-packages/vint/linting/cli.py", line 2
> 7, in start', '    violations = self._lint_all(env, config_dict)', '  File "/usr/lib/python3.7/site-packages/vint/linti
> ng/cli.py", line 124, in _lint_all', '    violations += linter.lint_file(file_path)', '  File "/usr/lib/python3.7/site-
> packages/vint/linting/linter.py", line 107, in lint_file', '    root_ast = self._parser.parse_file(path)', '  File "/us
> r/lib/python3.7/site-packages/vint/ast/parsing.py", line 37, in parse_file', '    decoded = decoder.read(file_path)', '
>   File "/usr/lib/python3.7/site-packages/vint/encodings/decoder.py", line 30, in read', '    string = self.strategy.dec
> ode(hunk, debug_hint=debug_hint_for_the_loc)', '  File "/usr/lib/python3.7/site-packages/vint/encodings/decoding_strate
> gy.py", line 45, in decode', '    string_candidate = strategy.decode(bytes_seq, debug_hint)', '  File "/usr/lib/python3
> .7/site-packages/vint/encodings/decoding_strategy.py", line 77, in decode', '    return bytes_seq.decode(encoding=encod
> ing_part.decode(encoding=''ascii''))', 'UnicodeDecodeError: ''ascii'' codec can''t decode byte 0xc2 in position 33: ord
> inal not in range(128)', '']                                                                                           
> syntastic: warning: checker vim/vint: unrecognized error format (crashed checker?)                                     
> syntastic: 40.358470: preprocess: []                                                                                   
> syntastic: 40.358617: raw loclist: []                                                                                  
> syntastic: 40.358769: getLocList: checker vim/vint returned 1                                                          
> syntastic: 40.358923: vim/vint raw: []                                                                                 
> syntastic: 40.359072: quiet_messages filter: {}                                                                        
> syntastic: 40.359191: getLocList: checker vim/vint run in 0.201145s                                                    
> syntastic: 40.359409: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}

**Comment by lcd047** [comment]
> `syntastic: 40.357309: checker output: ['Traceback (most recent call last):', ' File "/usr/bin/vint", line 11, in ',  ...`

There's your problem: `vint` crashes when run from Vim.  This has nothing to do with syntastic, it's all between `vint` and your Vim.  You should be able to reproduce it by running something like this:
```vim
:echo system('vint /home/ckb/.vimrc --json')
```

**Comment by Cbhihe** [comment]
Indeed !

```
:echo system('vint /home/ckb/.vimrc --json')

Traceback (most recent call last):                                                                     
  File "/usr/bin/vint", line 10, in <module>                                                           
    sys.exit(main())                                                                                   
  File "/usr/lib/python3.7/site-packages/vint/__init__.py", line 11, in main                           
    init_cli()                                                                                         
  File "/usr/lib/python3.7/site-packages/vint/bootstrap.py", line 22, in init_cli                      
    cli.start()                                                                                        
  File "/usr/lib/python3.7/site-packages/vint/linting/cli.py", line 27, in start                       
    violations = self._lint_all(env, config_dict)                                                      
  File "/usr/lib/python3.7/site-packages/vint/linting/cli.py", line 124, in _lint_all                  
    violations += linter.lint_file(file_path)                                                          
  File "/usr/lib/python3.7/site-packages/vint/linting/linter.py", line 107, in lint_file               
    root_ast = self._parser.parse_file(path)                                                           
  File "/usr/lib/python3.7/site-packages/vint/ast/parsing.py", line 37, in parse_file                  
    decoded = decoder.read(file_path)                                                                  
  File "/usr/lib/python3.7/site-packages/vint/encodings/decoder.py", line 30, in read                  
    string = self.strategy.decode(hunk, debug_hint=debug_hint_for_the_loc)                             
  File "/usr/lib/python3.7/site-packages/vint/encodings/decoding_strategy.py", line 45, in decode      
    string_candidate = strategy.decode(bytes_seq, debug_hint)                                          
  File "/usr/lib/python3.7/site-packages/vint/encodings/decoding_strategy.py", line 77, in decode      
    return bytes_seq.decode(encoding=encoding_part.decode(encoding='ascii'))                           
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 33: ordinal not in range(128) 
```
The question being, how do I get to correct the the non-ASCII character (outside the 128 range) decoding problem.

Should I close issue this here ?  - tx

**Comment by lcd047** [comment]
Do you get the same error when you run `vint` in a terminal?  If you do, your `vint` installation is broken and you should contact the maintainers of `vint` package (or whatever it is you installed `vint` from).  If you don't, then your Vim doesn't provide a proper `python3` environment and you should contact the maintainers of your Vim package.

Either way, the problem has nothing to do with syntastic, and there are too many moving parts in the picture for me to take an educated guess. _shrug_

**Comment by Cbhihe** [comment]
Yes, same exact thing with `$ vint ~/.vimrc` from terminal. 

Everything points to `vint`, you're right, and you're right again in saying that there are many moving parts in this issue. 

I will take this to `Kuniwak/vint` issue tracker and will report on vi.stackexchange (and drop you a comment on there) when I have it solved... if ever...

Thank you for taking the time. 

--closed.
