### ISSUE TITLE
wiki for syntax checkers v3.7 doesn't render

### ISSUE THREAD

**Issue by pak11273** [vim-syntastic/syntastic#2224]
url:
https://github.com/vim-syntastic/syntastic/wiki/%28v3.7.0%29---Syntax-Checkers

result:

![image](https://user-images.githubusercontent.com/2309184/47622810-7628a880-dad7-11e8-8882-ba84738cf38e.png)

**Comment by lcd047** [comment]
Please see #1729.  It's nostalgic to witness GitHub experiencing in 2018 under Microsoft the same problems it had in March 2016 on its own.

**Comment by pak11273** [comment]
OK. So the manual is the source of truth.  Got it.  Thanks!
