### ISSUE TITLE
Feature request: new linter for Javascript Lynt

### ISSUE THREAD

**Issue by fernandocanizo** [vim-syntastic/syntastic#2228]
Hello, I tried this in my `~/.vimrc`:

```
let g:syntastic_javascript_checkers = ['lynt']
let g:syntastic_javascript_eslint_exe = 'npx lynt '
```

And I got these Syntastic debug lines:
```
syntastic: 0.048884: UpdateErrors (auto): default checkers
syntastic: 0.049071: CacheErrors: default checkers
syntastic: 0.049507: g:syntastic_aggregate_errors = 0
syntastic: 0.049618: getcwd() = /some/path/not/relevant/to/the/issue
syntastic: 0.051473: CacheErrors: no checkers available for javascript
```
Then came here and realized there needs to be a `https://github.com/vim-syntastic/syntastic/tree/master/syntax_checkers/javascript` file for the specific linter.

I'm guessing it's a parser for the output of the linter.

Is there a tutorial on how to make a new linter to work with Syntastic?

This is the one I'd like to use: https://github.com/saadq/lynt

**Comment by lcd047** [comment]
There is a [guide][guide] for adding checkers, but some features are not covered (relevant here is dealing with JSON).

Anyway, I added a checker for `lynt`, please try it.  Commit c04603e1.

[guide]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide
