### ISSUE TITLE
Multi location windows is opened.

### ISSUE THREAD

**Issue by zoumi** [vim-syntastic/syntastic#2230]
I'm using rust.vim.
The step:
1,edit file1 with syntax error.
2,edit file2 with syntax error.
3,write all pre files  :wa
the result:
![image](https://user-images.githubusercontent.com/5162901/48296677-cd197f00-e4d4-11e8-8500-e088e1d3356d.png)

Software & Platform: gVim8 at Windows7 64bit.

**Comment by lcd047** [comment]
> I'm using rust.vim.

The `rust` checker is part of the `rust.vim` plugin, not syntastic.  Please direct your report there.
