### ISSUE TITLE
Any edit hides my location list with an empty one

### ISSUE THREAD

**Issue by faurehu** [vim-syntastic/syntastic#2232]
Hello,

If my location list shows any amount of items and I edit my buffer - even on irrelevant lines - my location list is replaced by an empty one.

The new location list seems to be populated by an empty `:setlocationlist()` and I don't know how to trace its caller.

Here's my relevant settings:

```
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_jump = 3
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_loc_list_height = 4
let g:syntastic_ruby_checkers = ['rubocop']
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_typescript_checkers = ['tslint']

```

Because the current location list is empty, commands such as `:lnext` or `:lfirst` don't direct anywhere.

**Comment by lcd047** [comment]
You probably have another plugin interfering with loclists.  Syntastic changes loclists only after running checks, and that never happens when you just edit the buffer.

**Comment by faurehu** [comment]
@lcd047 you are right, it works alright when I disable YCM
