### ISSUE TITLE
checker inside docker container (path issue)

### ISSUE THREAD

**Issue by sandrodz** [vim-syntastic/syntastic#2233]
I'm using a dockerized phpcs.
```
#!/bin/bash
sudo docker run -i --rm -v "$(pwd)":/app phpcs phpcs --basepath=/app/ "$@"
```

I use vim+syntastic setup in the following way
```
let g:syntastic_php_checkers = ['php', 'phpcs']
let g:syntastic_php_phpcs_exec = '/usr/local/bin/phpcs'
```
I used to have:
`let g:syntastic_php_phpcs_args = '--standard=PSR2'`
and would often change this global option per project. I'd like to move away from this and have a file inside project root so I don't have to edit `.vimrc` every time I jump from project to project with different standards.

If I don't define `--standard` phpcs reads from the root .phpcs.xml file. But it works only for the root files, if I navigate to some other folder and open php files in sub directories, .phpcs.xml is not being found - this is expected because of the container setup, phpcs container doesn't know of any parent directories and files in them. Syntastic always runs checker from current dir.

Is there a way to make Syntastic run checker from project root? and have all file path relative to it?

**Comment by lcd047** [comment]
Please see the [FAQ][FAQ].

[FAQ]: https://github.com/vim-syntastic/syntastic#faqconfig

**Comment by sandrodz** [comment]
You mean **4.9 My favourite checker needs to load a configuration file from the project's root rather than the current directory...** right?

That would still not work, because actual file .phpcs.xml is not inside the docker container. So passing full path from host OS to guest Container will result in file not found inside guest phpcs container.

Just to clarify this. We have following structure:

> .phpcs.xml
> file.php
> dir/file.php

```
$phpcs dir/file.php (works!)
$phpcs file.php (works!)
```

`$cd dir && phpcs file.php (doesn't work!)`

This is because when I `cd` into `dir`, phpcs container is run from that directory and it has no knowledge of ../.phpcs.xml, this file simply doesn't exist inside.

**Comment by sandrodz** [comment]
Same works for vim.

```
$vi dir/file.php (works!)
$cd dir && vi file.php (doesn't work!)
```
 `'makeprg': '/usr/local/bin/phpcs --report=csv dir/file.php'` works
cd into directory and and open with vim
 `'makeprg': '/usr/local/bin/phpcs --report=csv file.php'` doesn't work

What I need is for Syntastic or vim whichever handles this part to always start checker from specific root directory of the project.

**Comment by lcd047** [comment]
No.  The point is you can read the file in Vim, and form the command line for `phpcs` accordingly.  It's a bit of a pain but that's what Vim offers. _shrug_

Anyway, this is all general Vim-fu that has nothing specific to syntastic.  Perhaps ask on a general Vim forum if you can't figure it out?
