### ISSUE TITLE
No available checkers

### ISSUE THREAD

**Issue by geosword** [vim-syntastic/syntastic#2234]
I have the same problem as https://github.com/vim-syntastic/syntastic/issues/1537 However my path is correct.

```
Syntastic version: 3.9.0-20 (Vim 704, Linux)
Info for filetype: conf
Global mode: active
Filetype conf is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
syntastic: 499.788360: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote
= '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
```

My path from within vim:

```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/puppetlabs/bin:/usr/local/go/bin

Press ENTER or type command to continue
```
```
$ which puppet-lint
/usr/local/sbin/puppet-lint
```

My config:
```
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_puppet_checkers= ['puppetlint']
```

The check is present on the filesystem
```
$ ls -l .vim/bundle/syntastic/syntax_checkers/puppet/puppetlint.vim 
-rw-rw-r-- 1 geosword geosword 1874 Nov 24 07:33 .vim/bundle/syntastic/syntax_checkers/puppet/puppetlint.vim
```

**Comment by lcd047** [comment]
Please do these steps (don't do anything else):
* set `g:syntastic_check_on_open` to 0 in your `vimrc`
* open a `puppet` file
* set `g:syntastic_debug` to 33
* run `:SyntasticInfo`
* run `:mes`
* post the output

Also, what version of `puppet-lint` are you running, and how did you determine the `PATH` from within Vim?

**Comment by geosword** [comment]
Thanks for taking the time to respond


```
:SyntasticInfo
Syntastic version: 3.9.0-20 (Vim 704, Linux)
Info for filetype: conf
Global mode: active
Filetype conf is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
syntastic: 9.805008: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
```

```
:mes
Messages maintainer: Mike Williams <mrw@eandem.co.uk>                                                                                                                                           
"svn/ca-infra/puppetlabs/manifests/nodes/ca.pp" 2110L, 56947C
Syntastic version: 3.9.0-20 (Vim 704, Linux)
Info for filetype: conf
Global mode: active
Filetype conf is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
syntastic: 35.156331: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
```
Vim Path aquired with:
```
:echo syntastic#util#system('echo "$PATH"')
```

```
$ puppet-lint -v
puppet-lint 2.3.6
```

I intend on getting it working with puppet parser validate also:

```
$ dpkg -l puppet-agent | grep puppet-agent
ii  puppet-agent   6.0.4-1xenial amd64        The Puppet Agent package contains all of the elements needed to run puppet, including ruby, facter, and hiera.
```

**Comment by lcd047** [comment]
What is the output of:
```vim
:echo executable('puppet-lint')
```

Does anything change if you give it the explicit path:
```vim
let g:syntastic_puppet_puppetlint_exec = '/usr/local/sbin/puppet-lint'
```

**Comment by geosword** [comment]
:echo executable('puppet-lint')

Outputs nothing. I didnt know if that was correct or not, so fired up vim without a config file. It does the same.

let g:syntastic_puppet_puppetlint_exec = '/usr/local/sbin/puppet-lint'

Not that I can see. Available checkers is still blank:
```
Syntastic version: 3.9.0-20 (Vim 704, Linux)
Info for filetype: conf
Global mode: active
Filetype conf is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
```

**Comment by geosword** [comment]
OK, I think I know what the culprit is. Thanks for taking the time to help.

**Comment by geosword** [comment]
Actually, I think its returning a 1, does that make sense?

**Comment by geosword** [comment]
Just for the removal of any doubt, I have spun up a vm of debian stretch. I get the same behavior (SyntasticInfo reports no Available checkers). I configured syntastic in the way I mentioned above, and the syntax checking still isn't run. I really don't understand what I'm doing wrong. I should also mentioned it DID work less than a week ago... anyways. I guess Ill do without automatic syntax checking until I can get some more time to figure this out

**Comment by lcd047** [comment]
> Just for the removal of any doubt, I have spun up a vm of debian stretch.

Debian is known to ship stripped down versions of Vim.  Syntastic tries to make sure at startup that Vim has all features it needs, but Vim is a moving target, and these days I no longer pay close attention to Vim.  There might be checks I missed.  So make sure you aren't running a crippled version of Vim.  Just checking.

> the syntax checking still isn't run.

"Isn't run" is not the same as "`:SyntasticInfo` doesn't see it as available".  Just checking, again.

> I should also mentioned it DID work less than a week ago...

Yeah, you probably should have mentioned it.  There are very few things syntastic needs to see `puppet-lint` as available: it needs to find it in `$PATH`, it needs it to be executable, and it needs to be able to run `puppet-lint --version`.  If you rule out these, you basically need to look for oddball explanations: broken Vim, broken package manager, other plugins interfering, things outside Vim interfering (such as SELinux), and so on.  As entertaining as this sounds, I'm afraid I don't have either the time or the resources to debug this remotely for you. _shrug_

**Comment by geosword** [comment]
> Debian is known to ship stripped down versions of Vim. Syntastic tries to make sure at startup that Vim has all features it needs, but Vim is a moving target, and these days I no longer pay close attention to Vim. There might be checks I missed. So make sure you aren't running a crippled version of Vim. Just checking.

Fair point, thanks for letting me know.

> As entertaining as this sounds, I'm afraid I don't have either the time or the resources to debug this remotely for you. shrug

I would never have assumed such a thing. Its great that you've taken the time to write Syntastic, and even respond to issues like this that don't seem to occur anywhere else. Its people like you that keep this whole opensource thing going, and for that, I'm eternally grateful. I wouldn't have my job without it! 

Anyways, For my own sanity I felt compelled to track down what was causing this. Eventually, I have.
I had rodjek/vim-puppet installed, when I remove
```
Plugin 'rodjek/vim-puppet'
```
SyntasticInfo shows no available checkers. 
The moment I put it back in, SyntasticInfo shows available checkers and starts working again.

perhaps this will help someone with a similar problem.

**Comment by lcd047** [comment]
> `Plugin 'rodjek/vim-puppet'`

Right, I would have probably caught this from the beginning if I had paid closer attention to what you wrote.  From your first message:
```
Syntastic version: 3.9.0-20 (Vim 704, Linux)
Info for filetype: conf
```
Syntastic works based on `filetype`s.  Without `vim-puppet` Vim sets the `filetype` for your test file to `conf`, and, of course, there are no syntastic checkers for `conf`.  So basically it's a `filetype` detection problem, unrelated to syntastic.  Sorry for not catching this from the very beginning.

**Comment by geosword** [comment]
If I'd version controlled my vim config like a sane person, I could have caught it too! Needless to say I'm now doing that!

>Syntastic works based on filetypes. Without vim-puppet Vim sets the filetype for your test file to conf

Ah! So simply:
```
set filetype=puppet
```
Fixes it, without having rodjek/vim-puppet installed (although it is a helpful plugin to have!)
