### ISSUE TITLE
Syntastic checks Python file which has file write mode code may be dangerous 

### ISSUE THREAD

**Issue by micuncang** [vim-syntastic/syntastic#2235]
`testFile = open("/tmp/test", "w")
testFile.close()`

Here is a simple sample. When I do the syntasticcheck, my test file is emptied

**Comment by lcd047** [comment]
Please describe what did you do, what did you expect to happen, and what happened instead.

**Comment by micuncang** [comment]
My config is as follows:
let g:syntastic_python_python_exe = 'python'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

My Python code is as follows:
testFile = open("/tmp/test", "w") 
testFile.close()

When I save my python file through :w in vim, my file '/tmp/test' is emptied. I am expecting to tell me that this code file is syntactically correct, without any file change.

**Comment by lcd047** [comment]
> `let g:syntastic_python_python_exe = 'python'`

Don't aim at your foot before calling the trigger. :smile: What problem are you trying to solve by setting the `exe` variable?

**Comment by micuncang** [comment]
Sorry, my mistake
