### ISSUE TITLE
"g:syntastic_cpp_remove_include_errors" no longer present in source code

### ISSUE THREAD

**Issue by dragos240** [vim-syntastic/syntastic#2236]
I've been trying to figure out why this option which is present in the documentation was not changing the checking behavior of syntastic. I did some searching around with grep to see if I could find the string `syntastic_cpp_remove_include_errors` in my local syntastic directory. The only instance of that string was present in `doc/syntastic-checkers.txt`.

**Comment by lcd047** [comment]
> I've been trying to figure out why this option which is present in the documentation was not changing the checking behavior of syntastic.

Please describe what did you do, what did you expect to happen, and what happened instead.

> The only instance of that string was present in `doc/syntastic-checkers.txt`.

This is expected, the string `syntastic_cpp_remove_include_errors` has been removed from the code since commit ea827bfa, in 2013.  The functionality is still present though.

**Comment by lcd047** [comment]
> I figured it would be less work to just disable the include checking.

That isn't what `syntastic_cpp_remove_include_errors` is supposed to do.  Missing include files are errors in the **current** file (that's how `gcc` sees them).  What `syntastic_cpp_remove_include_errors` does is hide errors in any file that is **different** from the current file (f.i. errors in header files).  In your example above it hides any error in `testgui.hpp`.

On a side note, missing include files is a fatal error for `gcc`.  That is, when `gcc` encounters a missing include file it aborts any further checks, which is probably not what you want.  This is how `gcc` works, and there isn't anything syntastic can do to change it.

On a side note 2: please avoid screenshots when possible.  Among other things they can't be indexed for searching.
