### ISSUE TITLE
Python checker returns syntax error on f string 

### ISSUE THREAD

**Issue by PROgram52bc** [vim-syntastic/syntastic#2242]
When there is an f-string in python, it displays an error. See image below:
![Python f-string syntax error](https://user-images.githubusercontent.com/18290763/51577922-99ba7f80-1e89-11e9-8146-83b99ced346c.png)

**Comment by lcd047** [comment]
You're checking a Python 3 script with a Python 2 checker.  Please see the [FAQ][faq].

[faq]: https://github.com/vim-syntastic/syntastic#faqpython

**Comment by vincentmader** [comment]
> For those who might be having the same error.
> run or put in .vimrc:
> :let g:syntastic_python_checker = ['<checker>']

This does not resolve the issue for me.

**Comment by PROgram52bc** [comment]
> > For those who might be having the same error.
> > run or put in .vimrc:
> > :let g:syntastic_python_checker = ['']
> 
> This does not resolve the issue for me.

My bad.
Try this?
```
let g:syntastic_python_checkers = ['python']
let g:syntastic_python_python_exec = 'python3'
```

**Comment by lcd047** [comment]
> Try this?
> 
> ```
> let g:syntastic_python_checkers = ['python']
> let g:syntastic_python_python_exec = 'python3'
> ```

This solves the problem for `python` checker.  It does nothing for other Python checkers such as `pyflakes` or `pylint`.  The easiest solution is still the one in the FAQ.
