### ISSUE TITLE
latex unnecessary error message for possible unwanted space at "{"

### ISSUE THREAD

**Issue by yujiangang** [vim-syntastic/syntastic#2247]
When I define the \newcommand,  I get 'error| possible unwanted space at "{" ' as long as the braces {} are not on the same line.  

e.g.

\newcommand{\includevid}[3]{
      \begin{center}
          \href{run:#3?autostart&loop{\includegraphics[width=#1\textwidth]{#2}}
      \end{center}
}

Sometimes, the newcommand is too long, I have to seperate the braces {} in different lines. It would be nice if the SyntasticCheck could avoid showing this error message.

**Comment by lcd047** [comment]
Syntastic doesn't care about the contents of your files.  What syntastic does is run third-party linters against your files and show you their output in a window.  Now, the two linters for `tex` known to syntastic are `chktex` and `lacheck`, and they're less than great.  If you can point to a better linter I'm open to suggestions.

That said, syntastic does have a general mechanism for removing unwanted messages.  It doesn't make the linters any better, but it's useful for removing junk.  Please see `h 'syntastic_quiet_messages'`.

**Comment by yujiangang** [comment]
@lcd047 Thank you very much! The 'syntastic_quiet_messages' is a great tool!

**Comment by arendtio** [comment]
For those who might stumble upon this in the future, a copy & paste solution was mentioned in another issue (using the technique described in this issue): https://github.com/vim-syntastic/syntastic/issues/2169#issuecomment-381673940

**Comment by lcd047** [comment]
Not particularly pointing at this issue, but...  For those who might stumble upon this in the future, they can save time by reading the (relevant section of) the manual and writing their own solution, rather than debugging possibly obsolete code written by somebody else. :smile:
