### ISSUE TITLE
Python 2.7 long type

### ISSUE THREAD

**Issue by hissssst** [vim-syntastic/syntastic#2251]
* OS: Linux Manjaro 18.0.3
* syntastic: 3.9.0
* Python: 2.7.15

Syntastic marked `0L` as an error but this stands for *long-type* 0

**Comment by lcd047** [comment]
Please explain what did you do, what did you expect to happen, and what happened instead.

**Comment by hissssst** [comment]
* What I did
```
def to_long(x):
    if x is None:
        return 0L
    return long(x)
```
* What happened
```
  def to_long(x):
      if x is None:
>>        return 0L
      return long(x)
```
with `L` marked red

* What expected
```
def to_long(x):
    if x is None:
        return 0L
    return long(x)
```

So syntastic marked this `0L` as a syntax error, but It's not an error

**Comment by lcd047** [comment]
Syntastic doesn't know, nor particularly cares, about Python syntax.  What syntastic does is it runs third-party linters against your files, and shows their output in a window.  Consequently, please find out what linter was run, then either (1) configure syntastic not to run it, or (2) configure said linter not to complain about your file, or (3) complain to the maintainers of said linter.  Or (4) configure syntastic to remove that particular error message.
