### ISSUE TITLE
Syntastic overrides ALE for shellcheck

### ISSUE THREAD

**Issue by howaboutsynergy** [vim-syntastic/syntastic#2254]
see https://github.com/w0rp/ale/issues/2439

Basically, on `vim`'s `:w` command, ALE executes `shellcheck -s bash -x -f gcc -` and then syntastic executes `shellcheck -s bash -f gcc`

Is there some way to choose either ALE or syntastic?

tested with ArchLinux's `local/vim-syntastic 3.9.0-1 (vim-plugins)`

**Comment by lcd047** [comment]
There is.  It's described in the manual.

**Comment by howaboutsynergy** [comment]
Thanks, this line in `~/.vimrc` did it for me:
`let g:syntastic_sh_checkers = [ ]                                               `
