### ISSUE TITLE
perl checker first ignores g:syntastic_perl_interpreter

### ISSUE THREAD

**Issue by allter** [vim-syntastic/syntastic#2255]
perl checker the very first check (while loading script) ignores g:syntastic_perl_interpreter.

I could wrestle this down with https://github.com/allter/syntastic/commit/f83e1a9586f83e748c4a76d770e54bf222db9d7a

I'm not familiar enough with syntastic internals to understand if it is a good solution...

**Comment by lcd047** [comment]
Please explain what did you do, what did you expect to happen, and what happened instead.  Post your configuration and (hopefully) minimal test files if relevant.

**Comment by lcd047** [comment]
No feedback, no cry.
