### ISSUE TITLE
Syntax Errors Not Being Contained

### ISSUE THREAD

**Issue by naftulikay** [vim-syntastic/syntastic#2256]
![Screenshot from 2019-05-02 14 04 07](https://user-images.githubusercontent.com/347571/57106804-2f647700-6ce3-11e9-85fb-f6ed392a4119.png)

Please [view this screen recording which shows what I'm seeing](https://imgur.com/j122wbJ)

---

I ran into [this memory leak issue](https://stackoverflow.com/a/53086754/128967) with the Tmux version shipped by Ubuntu 18.04, which is my desktop distribution. Tmux leaks memory like a sieve, so I had to compile Tmux 2.9 from source to use that instead of the Tmux 2.6 that Ubuntu 18.04 ships by default.

After I upgraded to Tmux 2.9, syntax errors stopped being hid properly and instead seem to display over everything, making it really hard to write code.

I'm using NeoVim 0.3.4:

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-jXFUbD/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-jXFUbD/neovim-0.3.4/build/config -I/build/neovim-jXFUbD/neovim-0.3.4/src -I/usr/include -I/build/neovim-jXFUbD/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-jXFUbD/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

I am using [vim-plug](https://github.com/junegunn/vim-plug) for managing Vim dependencies. Here are the relevant sections for Syntastic:

```
call plug#begin('~/.local/share/nvim/plugged')

; ...
Plug 'vim-syntastic/syntastic'
Plug 'rust-lang/rust.vim'
; ...

call plug#end()

let g:rust_clip_command = 'xclip -i -selection clipboard'
let g:rustfmt_autosave = 1
```

My configuration has not changed since I upgraded Tmux and was previously working without issue.

Here is my tmux configuration:

```
# default command key is "o"
set -g prefix C-o

# ------- HOTKEY CONFIGURATION -------
unbind %
unbind ,
# pipe splits horizontally in half
bind | split-window -h
# dash splits vertically in half
bind - split-window -v
# capital R reloads the config
bind R source-file ~/.tmux.conf
# lowercase r renames the window
bind-key -T prefix r command-prompt -p 'rename window:' -I '#W' "rename-window '%%'"
# ----- END HOTKEY CONFIGURATION -----

# vi keymaps for buffer navication
set-window-option -g mode-keys vi
# pipe selection to system clipboard
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard > /dev/null"

# enable 256 color
set-option -g default-terminal "screen-256color"

# workaround vim bug
set -g escape-time 10

# disallow rewriting window titles automatically
set-window-option -g allow-rename off

# renumber windows after closing them
set-option -g renumber-windows on

# store 8192 lines of history per window
set-option -g history-limit 8192

# source the powerline configs
source "/usr/share/powerline/bindings/tmux/powerline.conf"
```

I have just ran `:PlugUpdate` to update everything to latest and it still does not seem to fix the issue. I can't for the life of me think of why upgrading Tmux would break Syntastic.

Any ideas?

**Comment by naftulikay** [comment]
I have researched this further and determined that tmux is _not_ involved; Syntastic still behaves strangely without being run within tmux.

**Comment by lcd047** [comment]
Err... nice house of cards? :smile:

First of all syntastic doesn't support Rust.  Everything related to filetype `rust` is handled by the `rust-lang/rust.vim` plugin.  Second syntastic is not tested with NeoVim.  _Most_ features should work, but if it breaks you get to keep both pieces.  At this point you're probably better off using [ALE][ALE] instead of syntastic anyway, but I have no idea (and can't be bothered to check) whether `rust.vim` works with it.

However, from your description my guess would be your problem has nothing to do with syntastic, Rust, `rust.vim`, or tmux itself, but it _might_ have to do with NeoVim and the way it handles the terminfo entry provided by tmux.  I think there were recent changes in Vim related to that area, and an educated guess would be said changes were actually prompted by NeoVim.

Either way, this has nothing to do with syntastic, and there isn't anything syntastic can do to fix it.

[ALE]: https://github.com/w0rp/ale

**Comment by naftulikay** [comment]
My bad, I was super tired yesterday and this should have gotten caught by my outgoing filter. Apologies!
