### ISSUE TITLE
Feature request: WordPress linters in “wp-scripts”

### ISSUE THREAD

**Issue by davilera** [vim-syntastic/syntastic#2260]
WordPress now includes a custom script for (among other things) [linting JS and CSS code](https://github.com/WordPress/gutenberg/tree/master/packages/scripts):

* `wp-scripts lint-js` (which internally uses `eslint`)
* `wp-scripts lint-styles` (which internally uses `stylelint`)

I think it'd be great if Syntastic included these as two new checkers

* `let g:syntastic_javascript_checkers = ['wpscripts']`
* `let g:syntastic_css_checkers = ['wpscripts']` (or `scss` or `sass`...)

I tried to implement the checker myself, but I'm afraid I have no idea how to achieve this. If anyone could point me in the right direction, I'd be happy to give it a shot... but I don't know how to do it.

**Comment by lcd047** [comment]
There is a [guide][guide] for writing checkers in the wiki.

On a side note: WordPress linters seem too specialized for syntastic.  Perhaps they are best kept as [external checkers][external].

[guide]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide
[external]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide#external

**Comment by davilera** [comment]
> On a side note: WordPress linters seem too specialized for syntastic. Perhaps they are best kept as external checkers.

Maybe you're right; I don't have an strong opinion on this so... I'd be happy to create it as a external plugin.

> There is a guide for writing checkers in the wiki.

I tried to follow the guide with no success. This is what I did (as a quick test):

1. I duplicated `syntax_checkers/javascript/eslint.vim` into `syntax_checkers/javascript/wpscripts.vim`. I thought this would make things easier, as `wpscripts` uses `eslint` internally... so the output it generates and everything is equivalent to `eslint`'s.
2. I edited `wpscripts.vim` and changed all `eslint` strings into `wpscripts`. For example, `g:loaded_syntastic_javascript_eslint_checker` became `g:loaded_syntastic_javascript_wpscripts_checker`, `'name': 'eslint'` became `'name': 'wpscripts'`, etc.
3. If I'm not mistaken, Syntastic assumes the registered `name` is the name of the binary it has to execute. So in `self.makeprgBuild` I created this:

```
let makeprg = self.makeprgBuild({ 'exe': 'wp-scripts', 'args_before': (g:syntastic_javascript_wpscripts_generic ? 'lint-js' : 'lint-js -f compact') })
```

where I added the binary name (I assumed it was `exe`) and made sure it always included `lint-js` as part of its arguments.

Unfortunately, this didn't work. Any ideas?

**Comment by lcd047** [comment]
It might prove useful to actually read the guide before starting to write a checker. :smile:

**Comment by davilera** [comment]
I was finally able to implement an external Syntastic plugin that does the job. If anyone finds this issue and is interested in it, you can now use `wp-scripts` in Syntastic with [`syntastic-wp-scripts`](https://github.com/davilera/syntastic-wp-scripts).

It's still missing documentation... but, taking into account it's my first vim plugin ever, I'm pretty happy with it. Thanks for the help, @lcd047!

**Comment by lcd047** [comment]
@davilera You're close, but the `IsAvailable()` function is wrong.  To get it working you should remove the `exe` from `makeprgBuild()`, and add an `'exec': 'wp-scripts'` to `CreateAndRegisterChecker()`.  With that you can remove the `IsAvailable()` function altogether, because the default should do the right check.

**Comment by davilera** [comment]
Done, thanks!
