### ISSUE TITLE
Different behavior in checkbashisms in shell and in vim

### ISSUE THREAD

**Issue by idgserpro** [vim-syntastic/syntastic#2265]
If I create the following script:

```bash
#!/usr/bin/env bash
echo -e "\n testing"
```

And run in the terminal `checkbashisms test.sh` no error is found since the shebang is `bash`.

But if I use `checkbashisms` inside vim, even with `bash` shebang, I get:

```
 1 test.sh|2 warning| echo -e
```

Checking the source code of the syntax checker in

https://github.com/vim-syntastic/syntastic/blob/8393a3c7a2d13a20fa73f2a7f3cff3bcdf1fd54f/syntax_checkers/sh/checkbashisms.vim#L18

I see that you add two parameters, `-fx`. In the documentation there's information about ` How can I pass additional arguments to a checker?`, but not exactly about `changing` default arguments that are defined in each syntax checker definition: I would like to not use the default `-fx`. What should I do in this case?

**Comment by lcd047** [comment]
Setting `g:syntastic_sh_checkbashisms_args` overrides the default args.

**Comment by idgserpro** [comment]
Indeed. Should `How can I pass additional arguments to a checker?` be changed to `How can I pass/override additional arguments to a checker?` or something along those lines?

**Comment by lcd047** [comment]
It's actually more complicated, some options are necessary for syntastic being able to parse the output of the checker, and thus can't be overridden.  The mechanism itself is documented in the [checker guide][guide]; the default options and their roles for each checker are, sadly, not documented.

[guide]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide

**Comment by idgserpro** [comment]
At least in this case, I can override and if I change the shebang from `bash` to `sh`, `checkbashisms` is called. The discussion about all this architecture should be done in another issues. Thanks for answering.
