### ISSUE TITLE
Python3.7 Support

### ISSUE THREAD

**Issue by macskay** [vim-syntastic/syntastic#2268]
Python3.7 does not seem to be supported. I get errors when using f-strings:

![image](https://user-images.githubusercontent.com/8678523/59792613-d7a2bf00-92d4-11e9-894c-524eae2bc171.png)

Are there any plans on supporting 3.7 as it has been out a while now?

**Comment by macskay** [comment]
Nevermind, I found out that this is a problem with flake8. I updated flake8 and now it's not reporting any issues with the f-strings.

**Comment by lcd047** [comment]
The easiest approach to deal with Python 3 is still the one mentioned in the [FAQ][FAQ].

[FAQ]: https://github.com/vim-syntastic/syntastic#faqpython
