### ISSUE TITLE
Syntastic keep using pylint to check *.py files even python checker is set to 'flake8'

### ISSUE THREAD

**Issue by imnnquy** [vim-syntastic/syntastic#2269]
I set the python checker to `flake8`

`let g:syntastic_python_checkers = ['flake8']`

But when I open *.py file to edit, pylint shows a lot of issues

![image](https://user-images.githubusercontent.com/6952157/59905901-f1a9e200-9439-11e9-8633-fa77a6180265.png)

**Comment by lcd047** [comment]
That is not syntastic running pylint.

**Comment by imnnquy** [comment]
Thanks @lcd047 for your confirmation, it's not `syntastic` running pylint. Closing this issue
