### ISSUE TITLE
Vim-Syntastic showing ignored python errors Ubuntu 16.04

### ISSUE THREAD

**Issue by tmandal1988** [vim-syntastic/syntastic#2273]
`Syntastic` and `flake8` in `vim` not ignoring errors provided in `flake8` config file.

I am using `flake8` for python code linting with `Syntastic` in `vim`. I have a `flake8` config file per `flake8` documentation `absolute_path_to_home/.config/flake8` which ignores error `E251`. Now, when I run `flake8` from command line  by typing 
```
flake8 --config=absolute_path_to_home/.config/flake8 my_python_code_that_is_being_checked.py
``` 
then `flake8` ignores the error `E251`. However, when I run `flake8` inside vim using `<F7>` the error window inside vim shows `E251` despite it being ignored in the `flake8` config file.

To make sure that `Syntastic` is calling the `flake8` with right arguments I added the following to my `.vimrc`

```
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_python_flake8_args='--config=absolute_path_to_home/.config/flake8'
let g:syntastic_debug = 1
```
I checked the `Syntastic` call inside `vim` using `:messages` and get the following info

```
syntastic: 4.483755: CacheErrors: Invoking checker: python/flake8
syntastic: 4.484046: SyntasticMake: called with options: {'errorformat': '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %m,%A%f:%l: %m,%-G%.%#', 
'makeprg':'flake8 --config=absolute_path_to_home/.config/flake8 my_python_code_that_is_being_checked.py', 'env': {'TERM': 'dumb'}}
syntastic: 4.615727: system: command run in 0.131497s
syntastic: 4.617432: getLocList: checker python/flake8 returned 1
syntastic: 4.618452: getLocList: checker python/flake8 run in 0.134634s
```
So if the message above is to be believed then `Syntastic` is indeed calling `flake8` with the right config file so I am not sure why `E251` is still being displayed. For good measures below is what my `absolute_path_to_home/.config/flake8` file
```
[flake8]
ignore = E251
```
Is this a known bug? What am I doing wrong? Will appreciate any help. Thank you.

**Comment by lcd047** [comment]
Syntastic doesn't invent error messages by itself, so what you're seeing is either because the message isn't actually produced by syntastic, or the `flake8` run by syntastic is not the same `flake8` you run in a terminal, or (pretty unlikely but not unheard of) `flake8` run from inside Vim produces different results than `flake8` run in a terminal.

Please set `syntastic_debug` to 3, run the checker, and post the (entire) output of `:mes`.

**Comment by tmandal1988** [comment]
Here is the output after setting `syntastic_debug` to 3
```
"absolute_path_to_home/project_dir/src/work_dir/my_python_code_that_is_being_checked.py" 432L, 26159C written
syntastic: 6.320162: g:syntastic_version = '3.9.0-31 (Vim 704, Linux)'
syntastic: 6.320326: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 6.320859: UpdateErrors (auto): default checkers
syntastic: 6.321233: CacheErrors: default checkers
syntastic: 6.321970: g:syntastic_aggregate_errors = 0
syntastic: 6.322183: getcwd() = 'absolute_path_to_home/project_dir/src/work_dir'
syntastic: 6.328272: CacheErrors: Invoking checker: python/flake8
syntastic: 6.328620: SyntasticMake: called with options: {'errorformat': '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %m,%A%f:%l: %m,%-G%.%#', 'makeprg': 'flake8 --config=absolute_path_to_home/.config/flake8 absolute_path_to_home/project_dir/src/work_dir/my_python_code_that_is_being_checked.py', 'env': {'TERM': 'dumb'}}
syntastic: 6.490698: system: command run in 0.161861s
syntastic: 6.490803: checker output: ['absolute_path_to_home/project_dir/src/work_dir/my_python_code_that_is_being_checked.py:157:201: E501 line too long (281 > 200 characters)', 'absolute_path_to_home/project_dir/src/work_dir/my_python_code_that_is_being_checked.py:205:201: E501 line too long (235 > 200 characters)', '']
syntastic: 6.491056: raw loclist: [{'lnum': 157, 'bufnr': 1, 'col': 201, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'E501 line too long (281 > 200 characters)'}, {'lnum': 205, 'bufnr': 1, 'col': 201, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'E501 line too long (235 > 200 characters)'}]
syntastic: 6.491246: getLocList: checker python/flake8 returned 1
syntastic: 6.491361: python/flake8 raw: [{'lnum': 157, 'bufnr': 1, 'col': 201, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'E', 'pattern': '', 'subtype': 'Style', 'text': 'line too long (281 > 200 characters) [E501]'}, {'lnum': 205, 'bufnr': 1, 'col': 201, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'E', 'pattern': '', 'subtype': 'Style', 'text': 'line too long (235 > 200 characters) [
E501]'}]
syntastic: 6.491487: quiet_messages filter: {'type': 'style'}
syntastic: 6.491607: filtered by quiet_messages: []
syntastic: 6.491673: getLocList: checker python/flake8 run in 0.163336s
syntastic: 6.491810: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
Press ENTER or type command to continue
```

**Comment by lcd047** [comment]
There is no E251 in the output of `flake8`.  There are two E501, and they are both removed by your `quiet_messages`.  If you see any error output at all it comes from a different plugin, not syntastic.

**Comment by tmandal1988** [comment]
Thanks for clarifying, I think nvie/vim-flake8 (which I have in my .vimrc) is what is showing me the error inside my vim and not Syntastic. Syntastic is correctly ignoring the errors in flake8 config but vim-flake8 is not reading the flake8 config file properly I assume. Thanks again.
