### ISSUE TITLE
Feature: fish syntax checker

### ISSUE THREAD

**Issue by tycho01** [vim-syntastic/syntastic#2275]
It would be nice to have syntax support added for [fish](https://github.com/fish-shell/fish-shell).

**Comment by lcd047** [comment]
What kind of support do you have in mind?

**Comment by tycho01** [comment]
oh just syntax highlighting (colors) really.
just found @dag's [`vim-fish`](https://vimawesome.com/plugin/vim-fish) offers this for syntastic, which seems to work great! just unfortunate it's a bit easier to miss as it's not included by default. :sweat_smile:

**Comment by lcd047** [comment]
> oh just syntax highlighting (colors) really.

Well sadly syntastic has nothing to do with syntax highlighting.
