### ISSUE TITLE
python - f-string always show error

### ISSUE THREAD

**Issue by qipoy** [vim-syntastic/syntastic#2280]
python has an f-string formatting mechanism like 

```
first_name = 'John'
last_name = 'Lennon'

full_name = f'{first_name} {last_name}'
```
![screenshot](https://user-images.githubusercontent.com/15064152/63923820-666c4e80-ca71-11e9-823a-e04b60c8000b.png)

anyone can fix it?

**Comment by lcd047** [comment]
Please read the [FAQ][FAQ].

[FAQ]: https://github.com/vim-syntastic/syntastic#faqpython

**Comment by qipoy** [comment]
thanks, @lcd047 
it solved. i just run 

```
$pipenv run vim
``` 
:smile:
