### ISSUE TITLE
python PEP 498

### ISSUE THREAD

**Issue by isomorphisms** [vim-syntastic/syntastic#2281]
https://www.python.org/dev/peps/pep-0498/

Syntastic doesn’t seem to be aware of this new syntax for python 3.

**Comment by lcd047** [comment]
That's fine, syntastic is a Vim script, it doesn't need to care about Python syntax.  You on the other hand might consider reading the [FAQ][FAQ].

[FAQ]: https://github.com/vim-syntastic/syntastic#faqpython

**Comment by isomorphisms** [comment]
I did.

> The preferred place for posting suggestions, reporting bugs, and general discussions related to syntastic is the issue tracker at GitHub.

**Comment by lcd047** [comment]
Ok, you seem to be confused.  From the manual, first paragraph:

> Syntastic is a syntax checking plugin that runs files through external syntax linters.

Translation: syntastic doesn't know, nor particularly cares, about the contents of your files.  It runs **external** linters, parses their output, and shows you the result in a window.  If you're unhappy with the output of said linters it's up to you to configure what linters syntastic runs, and with what options.

In the particular case of Python, it's up to you to tell syntastic to run Python 3 linters for Python 3 code, and Python 2 linters to check Python 2 code.  The easiest way to do that is described in the [FAQ][FAQ], as I pointed in my first message.  Quoting from there:

> __4.11. Q. How can I check scripts written for different versions of Python?__
>
> A. Install a Python version manager such as [virtualenv][virtualenv] or [pyenv][pyenv], activate the environment for the relevant version of Python, and install in it the checkers you want to use.  Set `g:syntastic_python_checkers` accordingly in your `vimrc`, and run [Vim][vim] from the virtual environment.

See also #2280, from two days ago.  Other options are available too, provided that you read the manual.

[FAQ]: https://github.com/vim-syntastic/syntastic#faqpython
[pyenv]: https://github.com/yyuu/pyenv
[virtualenv]: https://virtualenv.pypa.io/en/stable/
[vim]: http://www.vim.org/
