### ISSUE TITLE
Syntastic does not invoke linters in specific project 

### ISSUE THREAD

**Issue by MaxG87** [vim-syntastic/syntastic#2282]
Hi to everyone.

I try to write code for [TD-Watson](https://github.com/TailorDev/Watson). I think the project itself is irrelevant but it might be handy to have a look at the code.

The problem I am facing is as follows. Everything works fine in my other codebases. In the code for TD-Watson, if I open `watson/watson.py` my second linter (flake8) is not invoked. I am not sure for the first one. If I change directory to `watson/` and open `watson.py` while in that directory, the second linter is invoked.

I would like Syntastic to invoke the second linter always.

Output of `vim --version`:

    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
    Inklusive der Patches: 1-1453
    Verändert von pkg-vim-maintainers@lists.alioth.debian.org
    Übersetzt von pkg-vim-maintainers@lists.alioth.debian.org
    Riesige Version mit GTK2 GUI.
     Ein- (+) oder ausschließlich (-) der Eigenschaften:
    +acl               +farsi             +mouse_sgr         -tag_any_white
    +arabic            +file_in_path      -mouse_sysmouse    +tcl
    +autocmd           +find_in_path      +mouse_urxvt       +termguicolors
    -autoservername    +float             +mouse_xterm       +terminal
    +balloon_eval      +folding           +multi_byte        +terminfo
    +balloon_eval_term -footer            +multi_lang        +termresponse
    +browse            +fork()            -mzscheme          +textobjects
    ++builtin_terms    +gettext           +netbeans_intg     +timers
    +byte_offset       -hangul_input      +num64             +title
    +channel           +iconv             +packages          +toolbar
    +cindent           +insert_expand     +path_extra        +user_commands
    +clientserver      +job               +perl              +vertsplit
    +clipboard         +jumplist          +persistent_undo   +virtualedit
    +cmdline_compl     +keymap            +postscript        +visual
    +cmdline_hist      +lambda            +printer           +visualextra
    +cmdline_info      +langmap           +profile           +viminfo
    +comments          +libcall           -python            +vreplace
    +conceal           +linebreak         +python3           +wildignore
    +cryptv            +lispindent        +quickfix          +wildmenu
    +cscope            +listcmds          +reltime           +windows
    +cursorbind        +localmap          +rightleft         +writebackup
    +cursorshape       +lua               +ruby              +X11
    +dialog_con_gui    +menu              +scrollbind        -xfontset
    +diff              +mksession         +signs             +xim
    +digraphs          +modify_fname      +smartindent       +xpm
    +dnd               +mouse             +startuptime       +xsmp_interact
    -ebcdic            +mouseshape        +statusline        +xterm_clipboard
    +emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
    +eval              +mouse_gpm         +syntax            
    +ex_extra          -mouse_jsbterm     +tag_binary        
    +extra_search      +mouse_netterm     +tag_old_static    
              System-vimrc-Datei: "$VIM/vimrc"
            Benutzer-vimrc-Datei: "$HOME/.vimrc"
     zweite Benutzer-vimrc-Datei: "~/.vim/vimrc"
             Benutzer-exrc-Datei: "$HOME/.exrc"
             System-gvimrc-Datei: "$VIM/gvimrc"
           Benutzer-gvimrc-Datei: "$HOME/.gvimrc"
    zweite Benutzer-gvimrc-Datei: "~/.vim/gvimrc"
          defaults Datei: "$VIMRUNTIME/defaults.vim"
               System-Menü-Datei: "$VIMRUNTIME/menu.vim"
         Voreinstellung für $VIM: "/usr/share/vim"
    Übersetzt: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-8l5tlu/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
    Linken: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm     

I configured Syntastic as follows:

    " Syntastic configuration
    let g:syntastic_python_mypy_args = "--ignore-missing-imports"
    let g:syntastic_python_flake8_args = "--max-complexity 5"
    let g:syntastic_python_checkers = ["mypy", "flake8"]

I would love to see this bug fixed and would provide further information. I also would like to know how to workaround this bug.

**Comment by lcd047** [comment]
Please read `:h syntastic-aggregating-errors`.  If that doesn't address your problem please explain what did you do, what did you expect to happen, and what happened instead.  How did you infer your "second linter (flake8) is not invoked"?  What did you do to trigger it?

**Comment by MaxG87** [comment]
Thank you for your prompt reply.

If I issue `let g:syntastic_aggreate_errors = "on"` (or "true"/"yes") the problem still persists.

What did I do: I switched to the Watson root directory and opened `watson/watson.py`. I applied the following patch and saved. The patch is 
    diff --git a/watson/watson.py b/watson/watson.py
    index e32abd7..1edff69 100644
    --- a/watson/watson.py
    +++ b/watson/watson.py
    @@ -1,5 +1,6 @@
     # -*- coding: utf-8 -*-
     
    +import numpy
     import datetime
     from functools import reduce
     import json
    @@ -7,10 +8,10 @@ import operator
     import os
     import uuid
     
    -try:
    -    import configparser
    -except ImportError:
    -    import ConfigParser as configparser
    +# try:
    +import configparser
    +# except ImportError:
    +#     import ConfigParser as configparser
     import arrow
     import click
     import requests

What did I expect: I expected that Syntastic would invoke `flake8` and report the superfluous import of numpy.

What happened instead: No error is reported, the file looks error free from inside VIm.

**Comment by lcd047** [comment]
Ok, please quit Vim and open your test file again, set `g:syntastic_debug` to 3, run the checker, then run `:mes` and post the output.  See `:h :redir` if you need to redirect the output of `:mes` to a file.

**Comment by MaxG87** [comment]
Übersetzt von Christian Brabandt <cb@256bit.org>
    "watson/watson.py" 570L, 17944C
    "watson/watson.py" 570L, 17944C geschrieben
    syntastic: 10.744626: g:syntastic_version = '3.8.0-2 (Vim 800, Linux, GUI)'
    syntastic: 10.744762: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
    syntastic: 10.745163: UpdateErrors (auto): default checkers
    syntastic: 10.745426: CacheErrors: default checkers
    syntastic: 10.745935: g:syntastic_aggregate_errors = 0
    syntastic: 10.746071: getcwd() = '/home/mgoerner/CodeUndDaten/Watson'
    syntastic: 10.753470: CacheErrors: Invoking checker: python/mypy
    syntastic: 10.753932: SyntasticMake: called with options: {'preprocess': 'mypy', 'errorformat': '%f:%l:%m', 'defaults': {'type': 'E'}, 'makeprg': 'mypy --ignore-missing-imports watson/watson.py', 'returns': [0, 1]}
    syntastic: 11.185357: system: command run in 0.431163s
    syntastic: 11.185505: checker output: ['watson/config.py:9: error: Name ''RawConfigParser'' already defined (possibly by an import)', 'watson/frames.py:10: error: List or tuple literal expected as the second argument to namedtuple()', 'watson/utils.py:28: error: Name ''unicode'' is not defined', 'watson/utils.py:30: error: Incompatible types in assignment (expression has type "Type[str]", variable has type "Tuple[Type[str], Any]")', '']
    syntastic: 11.186414: preprocess: ['watson/config.py:9:Name ''RawConfigParser'' already defined (possibly by an import)', 'watson/frames.py:10:List or tuple literal expected as the second argument to namedtuple()', 'watson/utils.py:28:Name ''unicode'' is not defined', 'watson/utils.py:30:Incompatible types in assignment (expression has type "Type[str]", variable has type "Tuple[Type[str], Any]")']
    syntastic: 11.186907: raw loclist: [{'lnum': 9, 'bufnr': 2, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Name ''RawConfigParser'' already defined (possibly by an import)'}, {'lnum': 10, 'bufnr': 3, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'List or tuple literal expected as the second argument to namedtuple()'}, {'lnum': 28, 'bufnr': 4, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Name ''unicode'' is not defined'}, {'lnum': 30, 'bufnr': 4, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'Incompatible types in assignment (expression has type "Type[str]", variable has type "Tuple[Type[str], Any]")'}]
    syntastic: 11.187219: getLocList: checker python/mypy returned 1
    syntastic: 11.187331: python/mypy raw: [{'lnum': 9, 'bufnr': 2, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'E', 'pattern': '', 'text': 'Name ''RawConfigParser'' already defined (possibly by an import)'}, {'lnum': 10, 'bufnr': 3, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'E', 'pattern': '', 'text': 'List or tuple literal expected as the second argument to namedtuple()'}, {'lnum': 28, 'bufnr': 4, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'E', 'pattern': '', 'text': 'Name ''unicode'' is not defined'}, {'lnum': 30, 'bufnr': 4, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': 'E', 'pattern': '', 'text': 'Incompatible types in assignment (expression has type "Type[str]", variable has type "Tuple[Type[str], Any]")'}]
    
    E488: Überschüssige Zeichen

**Comment by lcd047** [comment]
So `mypy` is run and it finds a number of issues, then you get an `E488` and syntastic gets aborted.  It's up to you to find out where this `E488` comes from.  Do you get the same output if you disable all other plugins and leave only syntastic?

**Comment by MaxG87** [comment]
I tried to investigate the issue a bit further. I am very sorry, but I cannot reproduce the E488 message :-(. However, I came up with a minimum working example that might help to find the cause of this bug.

It turns out that the MWE is very simple:

    import numpy

Running `mypy --ignore-missing-imports` on `watson/mwe.py` results in the following output:

    watson/config.py:9: error: Name 'RawConfigParser' already defined (possibly by an import)
    watson/frames.py:10: error: List or tuple literal expected as the second argument to namedtuple()
    watson/utils.py:28: error: Name 'unicode' is not defined
    watson/utils.py:30: error: Incompatible types in assignment (expression has type "Type[str]", variable has type "Tuple[Type[str], Any]")


Copying `watson/` to `/tmp` and then invoking `mypy` on that results in no output, as expected.

I think this is a mypy issue then. Thank you very much to help me find this out. I am sorry for the caused inconveniences.

**Comment by lcd047** [comment]
Sorry but that doesn't explain the logs above.  Syntastic recognized the errors produced by `mypy` (regardless of why they were produced), but then it got aborted by `E488` before it could display them.  That shouldn't happen, you probably have a rogue plugin that does that, or perhaps a conflicting Vim mapping.  The problem is unlikely to be syntastic itself, but it will still prevent syntastic to work. _shrug_

**Comment by MaxG87** [comment]
I created an issue in mypy which hopefully leads to clarifications. See https://github.com/python/mypy/issues/7484.
