### ISSUE TITLE
Support `javascriptreact` filetype

### ISSUE THREAD

**Issue by NickCis** [vim-syntastic/syntastic#2283]
I've recently updated VIM, and `jsx` files start being recognized as `javascriptreact` instead of `javascript`.

On my distribution, Arch Linux, `ftplugin`, `syntax` and `indent` folders have a `javascriptreact.vim` which load `javascript` configuration:
For example, `ftplugin/javascriptreact.vim`:

```vim
" Placeholder for backwards compatilibity: .jsx used to stand for JavaScript.
runtime! ftplugin/javascript.vim
```

Is there a way to achieve the same thing in syntastic? (If not, I could send the PR copying all javascript `syntax_checkers` with the `javascriptreact` name, but I don't feel the react approach).

SyntasticInfo output:
```
:SyntasticInfo
Syntastic version: 3.9.0 (Vim 801, Linux, GUI)
Info for filetype: javascriptreact
Global mode: active
Filetype javascriptreact is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
```

Thanks in advanced!

**Comment by lcd047** [comment]
Please read `:h 'syntastic_filetype_map'`.

**Comment by NickCis** [comment]
Thanks, I couldn't find that configuration!
