### ISSUE TITLE
Some random text in file.c

### ISSUE THREAD

**Issue by killerqhk** [vim-syntastic/syntastic#2285]
Hello,
If you look at the end of line 1, you will see some text. I don't know what those text is about. If I resize the terminal, those text will disappear. Sometimes, those text display in the middle of the screen also. Does any one have experiences in how to fix that ? 
![Bug](https://user-images.githubusercontent.com/51982310/66688561-2d6cef80-ec55-11e9-9030-60016a4db1a0.jpg)

**Comment by lcd047** [comment]
Please see #822 (TL;DR: it's Vim, not syntastic).

**Comment by killerqhk** [comment]
Thank you for your information. Have a good day!
