### ISSUE TITLE
Add support for `shfmt`

### ISSUE THREAD

**Issue by go2null** [vim-syntastic/syntastic#2286]
*shfmt*
- https://github.com/mvdan/sh

An existing vim-plugin
- https://github.com/z0mbix/vim-shfmt

**Comment by lcd047** [comment]
Added in eff1f1b6.

**Comment by go2null** [comment]
does it automatically set `-ln posix` for `#!/bin/sh`?

**Comment by lcd047** [comment]
No, you have to set it manually.  The problem with setting it automatically is this action couldn't be overridden when needed.

**Comment by go2null** [comment]
I have the following, but it doesn't update the file (`-w` writes changes to the file)
```
let g:syntastic_sh_shfmt_args = '-ln posix -i 0 -bn -ci -kp -w'
```
I also tried `:w` followed by `:e`, but still no updates to the file.

I also tried with `-w`
```
let g:syntastic_sh_shfmt_args = '-ln posix -i 0 -bn -ci -kp'
```
but suggested changes do not show up in the location window

NOTE: If I run the command itself, it works
```
!shfmt -ln posix -i 0 -bn -ci -kp -w
```

So, how do I use it?

**Comment by lcd047** [comment]
You don't, syntastic doesn't allow changing the files it checks.  Consider using [ALE][ALE] instead, which does a lot more than syntastic and is actually maintained.

[ALE]: https://github.com/w0rp/ale

**Comment by go2null** [comment]
thanks, will look into it.
(hopefully `s/syntastic/ale/g` will work :))
