### ISSUE TITLE
lintr for R disabled for security reasons with enable_checker set to 1

### ISSUE THREAD

**Issue by lyh970817** [vim-syntastic/syntastic#2289]
It seems that with the following settings in the `.vimrc` file `lintr` is not working.

```
let g:syntastic_r_checkers = ['lintr']
let g:syntastic_enable_r_checker = 1
```

`:SynstasticInfo` suggests `lintr` is currently enabled but disabled for security reasons.

**Comment by lcd047** [comment]
According to the manual the relevant variable is called `g:syntastic_enable_r_lintr_checker`.  Have you tried that?
