### ISSUE TITLE
Feature Request : Option for disabling pep8 recomendations

### ISSUE THREAD

**Issue by Chidhambararajan** [vim-syntastic/syntastic#2291]
I am currently using python 3.7

In vim while saving files ,the syntastic plugin starts to work.. I really like the error indication part ,
but can i disable the part which gives pip8 recomendations for the beautification of code alone and just use the error indication?

**Comment by lcd047** [comment]
You can save a lot of time by reading the manual.  In this particular case: `:h syntastic-filetype-checkers`.

**Comment by Chidhambararajan** [comment]
Thanks for the quick reply, got the fix!
