### ISSUE TITLE
jsyaml wont recognise cloudformation tags

### ISSUE THREAD

**Issue by adikari** [vim-syntastic/syntastic#2300]
Within my `cloudformation.yml` file my jsyaml complains about the un-recognised tags. 

In VS-Code we can have way to specify overrides form yaml lint as such:

```
    "yaml.customTags": [
        "!Equals sequence",
        "!FindInMap sequence",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!Join sequence",
        "!Ref",
        "!Select sequence",
        "!Split sequence",
        "!Sub"
    ]
```

Is there a way to do this in syntastic configuration?

![image](https://user-images.githubusercontent.com/1757714/78244488-754c3f80-7531-11ea-84a0-f881d94c84d9.png)

**Comment by lcd047** [comment]
I'm afraid this is a question for the developers of `jsyaml` / `yamllint` / `yamlxs`.  Syntastic doesn't care about the content of the files it checks, it just runs linters against your files and shows you the results.  If you want to change the results returned by linters you need to pass the appropriate flags to said linters.
