### ISSUE TITLE
Default checkers don't working

### ISSUE THREAD

**Issue by spongedoc** [vim-syntastic/syntastic#2301]
Hi

I'm struggeling with this problem more than 1 days. It's started when I tried to use syntastic on my work computer. I tought there is an environment problem, so I just booted up a bare centOS on my home computer. I followed the install steps (use pathogen), but I got the same error like on my work computer:

> syntastic: 38.218503: g:syntastic_version = '3.10.0-7 (Vim 704, Linux)'
> syntastic: 38.218600: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
> syntastic: 38.219145: UpdateErrors (auto): default checkers
> syntastic: 38.219848: CacheErrors: default checkers
> syntastic: 38.221296: g:syntastic_aggregate_errors = 0
> syntastic: 38.221791: getcwd() = '/home/spongedoc'
> syntastic: 38.222933: CacheErrors: Checker html/tidy is not available
> syntastic: 38.223327: CacheErrors: no checkers available for html
> syntastic: 38.223542: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}

This is the output with debug level 3. I tried to find the solution, but all of the error reports based on python, or java syntax checker errors. And tidy is a basic checker.

This is the output of the SyntasticInfo:

> Syntastic version: 3.10.0-7 (Vim 704, Linux)
> Info for filetype: html
> Global mode: active
> Filetype html is active
> The current file will be checked automatically
> Available checkers: validator w3
> Currently enabled checkers: -
> syntastic: 10.377349: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''

Please help me :)

**Comment by lcd047** [comment]
Please see the [FAQ][FAQ].

[FAQ]: https://github.com/vim-syntastic/syntastic#faqinfo
