### ISSUE TITLE
Help commands fail when syntastic is installed with Vim's built-in package manager

### ISSUE THREAD

**Issue by tompreston** [vim-syntastic/syntastic#2307]
Hi,
I use Vim's (8.2.587) built-in package manager to load packages (recommended by [tpope's vim-pathogen README.markdown](https://github.com/tpope/vim-pathogen/blob/master/README.markdown)). Syntastic appears to load and check programs, however the following commands (mentioned in the [syntastic/README.markdown](https://github.com/vim-syntastic/syntastic/blob/master/README.markdown)) don't work:

```
:Helptags
E492: Not an editor command: Helptags

:help syntastic-checkers
E149: Sorry, no help for syntastic-checkers
```

Does pathogen do something extra with the docs that Vim's built-in package manager doesn't? How can I fix these doc commands?

**Comment by lcd047** [comment]
Try `:helptags ALL`.

**Comment by tompreston** [comment]
Thanks for the quick response. That fixed it!

For anyone else, you can find out more information like so:
```
:help helptags
:100verbose :helptags ALL
```

See also: https://vi.stackexchange.com/questions/17210/generating-help-tags-for-packages-that-are-loaded-by-vim-8s-package-management
