### ISSUE TITLE
Quiet messages for lacheck and chktex

### ISSUE THREAD

**Issue by tobiasweede** [vim-syntastic/syntastic#2311]
Hello everybody,

I'm struggling with the quiet_message regex syntax for lacheck:

My config looks like this:

let g:syntastic_tex_lacheck_quiet_messages = { 'regex': [                       
             \ '\Vmissing',                                                               
             \ '\Vpossible unwanted space',                                      
             \ '\Vperhaps you should insert a'] }

---
However the following error still shows up:
lacheck: missing `\ ' after "d.h." (E)

I tried many different versions but can't get rid of this message :(

Any idea or advice how to debug it?

Best,
Tobias

**Comment by lcd047** [comment]
This doesn't seem to be a syntastic message.  The syntastic message looks like this:

![2020-05-22-193424_643x337](https://user-images.githubusercontent.com/1281736/82689684-8da02700-9c63-11ea-91a4-19d54f38b0f8.png)

**Comment by tobiasweede** [comment]
Omg, I disabled syntastic and indeed.
Seems like Neomake triggers lacheck as well.

Thanks a lot and sorry for inconvenience!
