### ISSUE TITLE
Feature Request: Python Black Support

### ISSUE THREAD

**Issue by jackno** [vim-syntastic/syntastic#2312]
Consider adding support for [Black](https://github.com/psf/black).

**Comment by lcd047** [comment]
This isn't suitable for syntastic.  Black is a code formatter, and syntastic assumes the linters it runs don't change the files under its feet.  Also syntastic is essentially dead, you might want to look at [ALE][ALE] instead.

Sorry, but no.

[ALE]: https://github.com/dense-analysis/ale
