### ISSUE TITLE
How to use Stylelint for SASS file

### ISSUE THREAD

**Issue by ndr47** [vim-syntastic/syntastic#2313]
Why it is not available stylelint for sass file?

Is there a way to activate it?

Thank you

**Comment by lcd047** [comment]
Please see the [FAQ][FAQ].  On a side note: syntastic defaults make zero sense in most concrete cases.  Please consider reading the manual to learn how to make it useful for your particular situation.

[FAQ]: https://github.com/vim-syntastic/syntastic#faqinfo

**Comment by ndr47** [comment]
I read the FAQ. In particular the number 4.3

But it says that the limter must be available in :SyntasticInfo, hence my question. 

Why it is not available stylelimter for sass when it is available for css. 

Thank you

**Comment by lcd047** [comment]
> Why it is not available stylelimter for sass when it is available for css.

Because nobody has written a syntastic `stylelint` checker for `sass`.  You can still run it as `:SyntasticCheck css/stylelint`.
