### ISSUE TITLE
Easier/more-standard way to hide syntastic output?

### ISSUE THREAD

**Issue by ns-cweber** [vim-syntastic/syntastic#2314]
I can never remember the right incantation. `:SyntasticToggle` used to work, and now it doesn't. Everything else in vim lets me use `:q` to quit the pane (or whatever the vim term for the widget is). Could we get this for syntastic?

**Comment by lcd047** [comment]
It's `:SyntasticReset`.  I'm pretty sure `:SyntasticToggle` never had any effect on the error window.
