### ISSUE TITLE
Improve your program, I m doing python and it shows error on good working program.

### ISSUE THREAD

**Issue by machinexa2** [vim-syntastic/syntastic#2315]
Lets say you have a file called main.py with this as content 
```py
data = "Hello World"
print(f"{data}")
```
It prints ERROR.  WHAT :(
Take another example
```py
data = "Hello World"
def hello_world(data: str) -> str:
      return data
```
Again it prints error. Maybe you should read (Type Hinting)[https://realpython.com/lessons/type-hinting/] and fix both errors.

**Comment by machinexa2** [comment]
and this too https://realpython.com/python-f-strings/

**Comment by machinexa2** [comment]
Then try to fix the bug OKAY!!! :)

**Comment by lcd047** [comment]
Please see [item 4.11. in the FAQ](https://github.com/vim-syntastic/syntastic#faqpython).  You're supposed to understand what syntastic does and configure it according to your needs before using it.
