### ISSUE TITLE
New feature cfn_nag checker

### ISSUE THREAD

**Issue by ionutz89** [vim-syntastic/syntastic#2316]
It will be great if we can integrate cfn_nag with this tool.

https://github.com/stelligent/cfn_nag

**Comment by lcd047** [comment]
On a quick look I'd say `cfn_nag` wouldn't play well with syntastic for many reasons, one of them being that syntastic is no longer actively maintained.  You could however look at [ALE][ALE] instead.

[ALE]: https://github.com/dense-analysis/ale
