### ISSUE TITLE
checkers don't run if files are open with FZF

### ISSUE THREAD

**Issue by dvarrazzo** [vim-syntastic/syntastic#2321]
I'm testing FZF, pretty much adding this module to my .vimrc: https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim

When a file is open with this command, syntastic doesn't run automatically on save. It works fine otherwise: typing `:e` to re-open the file in place, or running `:SyntasticCheck` works fine.

Any hint about what signal gets lost and how it can be fixed?

My vim configuration is this: https://github.com/dvarrazzo/dotfiles/blob/f116a4b14cc5d4effff240d576451b52c921700a/vim/vimrc#L240

**Comment by dvarrazzo** [comment]
Uhm: I'm afraid the problem does not repeat consistently. In the meantime I have discovered `g:syntastic_debug` so I'll try to use it next time something like this happens.

**Comment by lcd047** [comment]
Syntastic relies on `BufWritePost` to run checks on write, that's basically all there is to it.  On a quick look I see no reason why FZF would interfere with it, but then again syntastic UI was written for Vim 7.4, and there were corner cases that were never handled correctly.  So if you expect robust behavior that didn't happen even in its prime.  You should consider using [ALE][ALE] instead, as it's written for Vim 8 and it's actively maintained.

[ALE]: https://github.com/dense-analysis/ale
