### ISSUE TITLE
Current file will not be checked (Diff Mode) error

### ISSUE THREAD

**Issue by lakshits11** [vim-syntastic/syntastic#2322]
How to resolve it??

SCREENSHOT LINK:-

https://drive.google.com/file/d/1mzSvB3bb_W545xJMbC0jmbd9a8oR62ji/view?usp=sharing

**Comment by lcd047** [comment]
"Doctor, it hurts when I do X". :smile:

There are various aspects of `diff` mode that prevent syntastic from working when `diff` mode is active.  This is a limitation of syntastic, and there is no reasonable way to fix it (other than you turning off diff mode, that is).  So just don't do that.

On a side note, you might want to take a look at [ALE][ALE]: it's newer than syntastic, it's actively maintained, and it might actually work in `diff` mode.

[ALE]: https://github.com/dense-analysis/ale
