### ISSUE TITLE
Java javac executable can't be overridden in the config (with fix)

### ISSUE THREAD

**Issue by ygt-mikekchar** [vim-syntastic/syntastic#2323]
If you set `g:syntastic_java_javac_executable` to a different executable, Syntastic always runs `javac`.

Apologies for not just sending a PR.  It's a really trivial fix.

In https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/java/javac.vim#L26-L28

Where it says `g:syntastic_java_javac_executable` it should be `g:syntastic_java_javac_exec`

**Comment by lcd047** [comment]
Thank you.  Fixed in 63b74a74.
