### ISSUE TITLE
Feature: g:syntastic_check_on_write

### ISSUE THREAD

**Issue by cheery** [vim-syntastic/syntastic#2327]
Syntastic is used with purescript's [psc-ide-vim], where it works very well for working through errors. It is nice to use except for this one detail that perhaps could be added.

Purescript's file checking command takes about enough time to be noticed when it is hooked into `:w` through syntastic. Could we add something like `g:syntastic_check_on_open`, but on the write side?

I read your contribution guidelines, and I can draft the modification. Just let me know if you like to let me try it. Also, please inform if this is a redundant modification and it can be already done somehow.

 [psc-ide-vim]: https://github.com/FrigoEU/psc-ide-vim

**Comment by lcd047** [comment]
Please read: `:h 'syntastic_mode_map'`.

**Comment by cheery** [comment]
This seems to do it!
> "mode" can be mapped to one of two values - "active" or "passive". When set
> to "active", syntastic does automatic checking whenever a buffer is saved or
> initially opened. When set to "passive" syntastic only checks when the user
> calls `:SyntasticCheck`.
I will try it out, if it works, I'll close the commit next.

**Comment by cheery** [comment]
Thanks for the help. This does work. I'm sorry that I didn't read the documentation in whole. This feature is described in the section `2. Functionality provided`.
