### ISSUE TITLE
Julia support is broken

### ISSUE THREAD

**Issue by alhirzel** [vim-syntastic/syntastic#2336]
Currently, syntastic uses the Lint.jl package, [which has been deprecated](https://github.com/tonyhffong/Lint.jl/issues/269). The recommendation is to use [StaticLint.jl](https://github.com/julia-vscode/StaticLint.jl).

**Comment by lcd047** [comment]
Well, syntastic itself is mostly deprecated these days.  `StaticLint` is not a drop-in replacement for `Lint`, so patches are welcome.  Failing that, I suppose the action to take would be just remove the support for Julia.  In the mean time [ALE][ALE] is actively maintained, it does have support for Julia as a language server, and it can do asynchronous checks.

[ALE]: https://github.com/dense-analysis/ale

**Comment by lcd047** [comment]
The latter option it is then.  Patch dd226673.
