### ISSUE TITLE
syntastic_ignore_files pattern not matching expected files

### ISSUE THREAD

**Issue by heytrav** [vim-syntastic/syntastic#2338]
I'm having a bit of trouble finding the right pattern to prevent syntastic from checking files in specific subdirectories.

For context, I have a directory in my project (`ansible/roles`) that contains ansible roles installed using `ansible-galaxy`. These are 3rd party code which I didn't write, so I'm not interested in seeing their syntax errors.

```    
project/
| ansible/
| | files/
| | inventory/
| | roles/                                                    # <---
| | | christiangda.amazon_cloudwatch_agent
| | | geerlingguy.docker
       .
       .
| | tasks/
| | templates/
```

I'm trying to get syntastic to ignore files under that directory, but do not seem to figure out the right regular expression to make this happen. Here are some things I've tried:
```    
let g:syntastic_ignore_files = ['\m\cansible/roles']
```

```    
let g:syntastic_ignore_files = ['roles']
```

```
let g:syntastic_ignore_files = ['\mansible/roles.*\.yml$']
```

_Desired_ behaviour is that it just checks files that are _not_ in the `ansible/roles` subdirectory and displays syntax errors.

Actual behaviour: It doesn't seem to matter what pattern I use, syntastic still checks everything under the `ansible/roles` directory. Consequently a large part of my error list are files that aren't part of my project:
```
ansible/roles/christiangda.amazon_cloudwatch_agent/handlers/main.yml|19 error 208| File permissions unset or incorrect [ansible/ansible_lint]
ansible/roles/christiangda.amazon_cloudwatch_agent/handlers/main.yml|28 error 208| File permissions unset or incorrect [ansible/ansible_lint]
ansible/roles/christiangda.amazon_cloudwatch_agent/tasks/configure.yml|39 error 208| File permissions unset or incorrect [ansible/ansible_lint]
ansible/roles/christiangda.amazon_cloudwatch_agent/tasks/configure.yml|46 error 208| File permissions unset or incorrect [ansible/ansible_lint]
ansible/roles/christiangda.amazon_cloudwatch_agent/tasks/configure.yml|54 error 208| File permissions unset or incorrect [ansible/ansible_lint]
ansible/roles/christiangda.amazon_cloudwatch_agent/tasks/configure.yml|63 error 208| File permissions unset or incorrect [ansible/ansible_lint]

```

Not really sure what I'm missing in the regex syntax. Any assistance would be appreciated.

**Comment by heytrav** [comment]
I figured out that this was an ansible-lint issue and not a syntastic one. Adding a `.ansible-lint` file in my project solved it.

```
exclude_paths:
  - ./ansible/roles
```

**Comment by lcd047** [comment]
Please note that `syntastic_ignore_files` limits the files passed on the command line to the linter.  It does nothing to limit the results of linting (i.e. excluded files can still be shown in error messages if said messages came from checking other files).  Use `syntastic_quiet_messages` to limit the results (cf. `:h 'syntastic_quiet_messages'`).
