### ISSUE TITLE
Snake case error

### ISSUE THREAD

**Issue by Gako358** [vim-syntastic/syntastic#2340]
I write in both python and C, my problem is in python i use camel case variables and functions names, then it fills my error tab with each function name and variable name not being snake case. How can i fix this?

In python i am using pylint, if that have anything to say?

**Comment by lcd047** [comment]
Find out what checker produces those errors and configure it accordingly.  Syntastic doesn't care about the contents of your files, it just runs third-party linters and shows you the results in a window.  It's up to you to configure said linters to give you useful results.

**Comment by Gako358** [comment]
Hey, thanks for replying. I am using pylint, and how to i configure it?

**Comment by lcd047** [comment]
You can tell syntastic to pass options to `pylint` on the command line (see `:h syntastic-config-makeprg` and `:h syntastic-debug`), or you can pass options in a `pylintrc`.  Beyond that, perhaps consider reading `pylint`'s manual?
