### ISSUE TITLE
Displayed scrapped after warning message with Gruvbox

### ISSUE THREAD

**Issue by GCorbel** [vim-syntastic/syntastic#2344]
I use the scheme [Gruvbox](https://github.com/morhetz/gruvbox). When I have the message "WARNING: The file has been changed since reading it!!!" when I tried to write a file modified elsewhere, the display is scrapped. This is fixed when I go to the bottom of the file and go back.

![Peek 26-11-2020 11-27](https://user-images.githubusercontent.com/1296201/100374587-7fe4a900-2fda-11eb-8a53-c5aba680b189.gif)

Here is my .vimrc 

```
filetype off
set rtp+=~/.config/nvim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'scrooloose/syntastic'
Plugin 'morhetz/gruvbox'

call vundle#end()            " required
filetype plugin indent on    " required

syntax on
set background=dark
let g:gruvbox_contrast_light='hard'
let g:gruvbox_contrast_dark='hard'
colorscheme gruvbox
```

**Comment by lcd047** [comment]
So why do you suspect this has anything to do with syntastic?

**Comment by GCorbel** [comment]
I don't have the problem when I remove syntastic in the config file. Honestly, I don't know if it comes from Synstastic or Gruvbox. It's a conflict between the two plugins.

**Comment by lcd047** [comment]
So when syntastic is disabled you can open the file, modify it under Vim's feet, then try to write it and Vim doesn't complain?  I can't reproduce that here. :smile:

**Comment by GCorbel** [comment]
I always have the warning message when I try to write a file modified from outside, and it's normal, but I don't have the display issue.

**Comment by lcd047** [comment]
Syntastic has no control over low-level redraws, Vim does.  There is an ongoing struggle to fix redraws in all scenarios, it might help to report the problem to `vim_dev`.  See also #822.
