### ISSUE TITLE
Possibility to run a checker inside a docker container

### ISSUE THREAD

**Issue by 3ddiddE** [vim-syntastic/syntastic#2346]
I could not find any information about this, but is there any way to let the cppchecker run inside a docker environment?
I really like the feature of [vscode to develop apps that run inside a container](https://code.visualstudio.com/docs/remote/containers).
Currently I am using coc.nvim for completions etc. but as far as I understand it, the error checks on a buffer are done via syntastic (and cpplint in my case).
Also if this is the wrong place to ask, I would be really glad if you could point me to some other resource (IRC, website, whatever) that could help me with this issue.

**Comment by 3ddiddE** [comment]
I also had ALE installed and additionally coc.nvim ist also running diagnostics on a file.
So my solution for now (and working setup) is:
* disable diagnostics of coc.nvim: set ```diagnostics.enable: false```
* uninstall syntastic
* only use ALE and run the linter via a shell script that starts the actual linter within a docker instance

It does not feel exactly right to do it that way. Although this is the proposed solution by ALE developers, I am pretty sure that vscode is doing it differently, with less overhead.
The cons are now, that I have to maintain several additional scripts:
1. The one that executes the linter in docker
2. The coc config which is local to the repository via ```:CocLocalConfig```
3. A local vimrc to the project, to set all the necessary stuff for ALE

So I will leave  it up to you, if you have a better (more performant) solution I will be happy to hear it. Or else you can close this issue if you want to.
Also I am not sure, whether this might be some sort of feature request for syntastic?

**Comment by lcd047** [comment]
This has been discussed in the past (cf. f.i. #2270).  Basically, running checkers in containers return filenames relative to the container's root while Vim sees the real root.  Bun syntastic has been superseded by ALE these days, so if you have a solution for ALE go with that.
