### ISSUE TITLE
Strange escape sequence on console when starting vim/gvim

### ISSUE THREAD

**Issue by philpem** [vim-syntastic/syntastic#2350]
When I start Gvim from the command line and have the Syntastic plugin enabled, an escape sequence is printed to the console.

```
$ gvim
[>4;m[>4;2m
```

Vim version is 8.2 (8.2.1897-0york0~18.04)  from ppa:jonathonf/vim, running on Linux Mint "tessa" (Ubuntu 18.04/bionic equivalent).

I've also tested:

  * Ubuntu 'bionic' (18.04) + Vim 8.0 from the repo -- works fine, no escape sequence printing
  * Ubuntu 'focal' (20.04) + Vim 8.1 from the Ubuntu repos -- works fine
  * Ubuntu 'focal' (20.04) + Vim 8.2 from Jonathon F.'s PPA -- works fine

**Comment by lcd047** [comment]
Syntastic doesn't write anything to the console.  Whatever happens to get you there may be triggered by syntastic, but it isn't controlled by syntastic.  Please report the problem to `vim_dev`.
