### ISSUE TITLE
Conflict with vim-airline plugin

### ISSUE THREAD

**Issue by sproot1979** [vim-syntastic/syntastic#2351]
Hello, 

I have a problem using the vim-airline and syntastic plugins together. When the error window appears, the vim-airline theme is reset after fixing the errors. I tested this on the most minimal .vimrc settings, when only these two plugins are in the config. At the same time, if turn off the syntastic plugin, then airline works fine with the lopen and lclose functions. The most interesting thing is that on another computer with a different version of vim everything works. I also created a ticket from the author of the vim-airline upstream: [Ticket](https://github.com/vim-airline/vim-airline/issues/2316). Maybe you will have ideas on how to fix this.

**Comment by lcd047** [comment]
I really don't see how this could be related to syntastic.  That is, the problem you're seeing may be triggered by syntastic, but syntastic doesn't control refreshes of the status line.  As far as I can tell it's all between airline and Vim.

That said, syntastic is essentially dead these days, and I haven't followed Vim development for a few years now.  Syntastic was written for Vim 7, and while it appears to still work with Vim 8, it doesn't take advantage of Vim 8 features, and it doesn't know about Vim 8 quirks.  You should consider switching to [ALE][ALE] instead, which is actively maintained and allows asynchronous checks.

[ALE]: https://github.com/dense-analysis/ale

**Comment by sproot1979** [comment]
Thanks for the answer! I have already migrated to ALE and everything works for me. I'll close the ticket.
