### ISSUE TITLE
python/python: cant parse version string (abnormal termination?)

### ISSUE THREAD

**Issue by SherzodOtajonov** [vim-syntastic/syntastic#2353]
i ran `:!python check.py` on nvim and got this error. i dont understand what the problem is. please help me
![Screenshot (65)](https://user-images.githubusercontent.com/64304214/106577281-788fcd80-653e-11eb-936c-49e0b04f82a0.png)

**Comment by lcd047** [comment]
I take it you read "syntastic" in the error message, and now you expect me to figure out what's going on and fix your problem.  Sadly that's not how it works, the main problem here seems to be the second one, "shell failed to start", which is a Vim configuration problem.  If you fix it the syntastic error _should_ go away too.  So please fix the "shell failed to start" first, and reopen this if the syntastic error persists after that.

**Comment by SherzodOtajonov** [comment]
> I take it you read "syntastic" in the error message, and now you expect me to figure out what's going on and fix your problem. Sadly that's not how it works, the main problem here seems to be the second one, "shell failed to start", which is a Vim configuration problem. If you fix it the syntastic error _should_ go away too. So please fix the "shell failed to start" first, and reopen this if the syntastic error persists after that.

hey
yeah, i changed my shell, and its now working. thanks
and im sorry for make an issue with so little information.
