### ISSUE TITLE
Open location with Nerdtree mirror : "NERDTree: No trees to mirror"

### ISSUE THREAD

**Issue by dominiquefournier** [vim-syntastic/syntastic#2354]
I use Nerd Tree with the option "autocmd BufWinEnter * NERDTreeMirror". In that case, when you open a new Tab, the NERDTree is automatically re-open.
But when I open the Location list (with :Errors), there is an error displayed : 
```
NERDTree: No trees to mirror
Erreur détectée en traitant function 194[2]..195[4]..205 :
ligne    6 :
E788: L'édition d'un autre tampon n'est plus permise
Erreur détectée en traitant function 194[2]..195 :
ligne    4 :
E170: :endfor manquant
Erreur détectée en traitant function SyntasticErrors[1]..333 :
ligne    6 :
E171: :endif manquant
```
How could I remove this error which is displayed each time ?

Thanks
VIM - Vi IMproved 8.1 (Debian Buster)
Syntastic version: 3.10.0-22 (Vim 801, Linux, GUI)

**Comment by lcd047** [comment]
> I use Nerd Tree with the option "autocmd BufWinEnter * NERDTreeMirror".

You could try adding `nested` to your `autocmd`.  If that doesn't fix your problem though you might write it off as an unsupported configuration, sorry.  Interaction between `autocmd`s has always been a mess, it has changed a few times in recent versions of Vim, and I have no resources left for trying to figure out what's going on this time.  Please consider using [ALE][ALE] instead: it's actively maintained, it takes advantage of Vim 8 features, and it's essentially the successor of syntastic.

[ALE]: https://github.com/dense-analysis/ale

**Comment by dominiquefournier** [comment]
I try nested and it doesn't work.
I'll check ALE.
I open an issue on NERDTree : #preservim/nerdtree/issues/1226
Thanks a lot
