### ISSUE TITLE
UnityEngine.dll could not be found

### ISSUE THREAD

**Issue by xibz** [vim-syntastic/syntastic#2356]
I have been using syntastic with vim and Unity and noticed that it fails to load the UnityEngine.dll. Do I have to specify this DLL or something in the .vimrc?

**Comment by lcd047** [comment]
Syntastic as shipped has nothing to do with Unity.  If you think it has please explain what did you do, what did you expect to happen, and what happened instead.

**Comment by xibz** [comment]
@lcd047 I understand that. My question was around if it is unable to find the `UnityEngine.dll` do I have to specify? As in how do I include external DLLs? How does syntastic find DLLs?

**Comment by lcd047** [comment]
Syntastic is a Vim script.  What it does is it runs a number of third-party linters against your files, and shows their results in a window.  Syntastic itself doesn't need, knows, or cares about any DLL, all it needs to work is Vim.  Some of the linters might use DLLs to do their work, and it's up to you to configure them properly.  To the best of my knowledge none of the linters supported by syntastic is remotely related to Unity, or any of its DLLs.  But if you can make a case to the contrary, this is your chance.

**Comment by xibz** [comment]
Ah okay, I get what you are saying. Basically this is calling in this case `mcs` which is running into the DLL issue. I'll go ahead and close this as that points me in the right direction. Cheers
