### ISSUE TITLE
Feature: Semgrep checker for Python

### ISSUE THREAD

**Issue by mschwager** [vim-syntastic/syntastic#2357]
Hi there,

I was hoping to add [Semgrep](https://github.com/returntocorp/semgrep) as a Syntastic checker. I'm happy to create a PR adding the checker myself, but first I wanted to check that Syntastic is still actively accepting new checkers, and that Semgrep looks like a viable addition.

Thanks for your work on Syntastic - it's a crucial part of my daily workflow :)

**Comment by lcd047** [comment]
Syntastic has been superseded by [ALE][ALE], its use these days is essentially limited to systems that (for whatever reasons) are still running Vim 7.  What this means is that I'm doing maintenance for it as long as it doesn't involve too much trouble for me.  If you were to add a new checker then you'd promptly go on with your life, and leave me to maintain it as part of syntastic.  Now, `semgrep`, while very powerful, seems to be pretty complicated, and completely outside my range of knowledge.  That doesn't seem remotely trouble-free.  So the TL;DR is, you should focus on [ALE][ALE] instead, and if syntastic really is a "crucial" part of your workflow just write an [external checker][external] for it.  Thank you for your understanding.

[ALE]: https://github.com/dense-analysis/ale
[external]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide#external

**Comment by mschwager** [comment]
I appreciate the honesty, thanks for point me at the external checker docs. I went ahead and did that: https://github.com/returntocorp/semgrep.vim. I'll make sure to take a look at ALE too :+1: 

Thanks again for maintaining Syntastic!
