### ISSUE TITLE
How to enable syntastic checker for C++?

### ISSUE THREAD

**Issue by IlliaShafranskyi** [vim-syntastic/syntastic#2359]
Hi guys, 
maybe my question will be silly for you, but:
I installed syntastic via vim-plug, then I add recommended settings. I also add checker for c++:  let g:syntastic_cpp_checkers = ['clang_tidy']

But I don't see any errors. I type :SyntasticInfo and than I seen, that: 
Available checkers: -
Currently enabled checkers: -

How can I enable checkers?

**Comment by lcd047** [comment]
You must have `clang-tidy` installed and Vim has to "see" it for the `clang_tidy` checker to work.  See also the [FAQ][FAQ].  However for C++ you probably want a specialized linter instead, such as [YCM][YCM].  Syntastic is more of a generic framework, its interface is essentially useless for C and C++.

[FAQ]: https://github.com/vim-syntastic/syntastic#faqinfo
[YCM]: https://github.com/ycm-core/YouCompleteMe

**Comment by IlliaShafranskyi** [comment]
@lcd047 thx you very much
