### ISSUE TITLE
Want to get rid of a python error

### ISSUE THREAD

**Issue by pavanscoding** [vim-syntastic/syntastic#2360]
Whenever I use the pylint checker, I always get the error message 
```[missing-module-docstring] Missing module docstring```
I have tried many things such as 
```let g:syntastic_python_checker= ["flake8"]```
but whenever I use this, it tells me that I cannot use this interpreter to check my code. I have tried to change this to other interpreters, but it doesn't work. This results in the code not being checked at all.
I also used
```let g:syntastic_quiet_messages = { 'regex': 'C0111' }```
because I think that is the error message for the docstring error.  However, this doesn't work either.
Can you guys help me fix this?
Thanks!!

**Comment by lcd047** [comment]
There are many ways to disable a `pylint` message.  You can edit `~/.pylintrc` and add `missing-module-docstring` to the `disable` list.  Or you can tell syntastic to pass the relevant option to `pylint`:
```vim
let g:syntastic_python_pylint_args = '-d missing-module-docstring'
```
Or you can tell syntastic to remove the message:
```vim
let g:syntastic_python_pylint_quiet_messages = { 'regex': 'missing-module-docstring' }
```
As for the `flake8` not working, your `flake8` script is probably broken, unrelated to syntastic.

**Comment by pavanscoding** [comment]
Thank you so much. That fixed my error messages.
