### ISSUE TITLE
Execution of checker in the detached process

### ISSUE THREAD

**Issue by Letme** [vim-syntastic/syntastic#2362]
I have a long-running process (for example big compilation), which is executed through Syntastic. What I am bothered with is, that VIM is blocked while Syntastic executes and there is also no progress (debug information on stdout) printed.

So my question is: could we detach a process and just display a "Syntastic running pid $pid" message instead of errors?

**Comment by lcd047** [comment]
No.  Syntastic was written for Vim 7, and it doesn't support any form of job control.  You might consider switching to [ALE][ALE] instead, which is newer and actively maintained.

[ALE]: https://github.com/dense-analysis/ale
