### ISSUE TITLE
Confution about why the path of the checker can't be found

### ISSUE THREAD

**Issue by daybreaktexas** [vim-syntastic/syntastic#2365]
![屏幕截图 2021-06-06 211819](https://user-images.githubusercontent.com/79646273/120925886-3d302600-c70d-11eb-999b-18dfcff43ff6.png)
![屏幕截图 2021-06-06 211916](https://user-images.githubusercontent.com/79646273/120925891-415c4380-c70d-11eb-944d-e37d6a7bec8f.png)
I have installed pylint and added it in the path, as you can see in the picture uploaded.
However it still can't be found by syntastic even it's in the particular path.

I've didn't installed ycm or things like that, and I am using wsl, may that the problem?
Any suggestions will be appreciated.

**Comment by lcd047** [comment]
Why are you trying to check a file with filetype `vim` with `pylint`?
