### ISSUE TITLE
Using sparse in Vim

### ISSUE THREAD

**Issue by Stephen2252Ro** [vim-syntastic/syntastic#2367]
I installed sparse, and add its installed path "/usr/bin" to PATH. And I set the checker in .vimrc. But I still cannot use it in Vim. I only can use it at shell.
Please help me.

**Comment by lcd047** [comment]
Please open a C file, run `:SyntasticInfo`, and post the output.

**Comment by Stephen2252Ro** [comment]
It said this.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vim-syntastic/syntastic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月19日(星期六) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vim-syntastic/syntastic] Using sparse in Vim (#2367)





 
Please open a C file, run :SyntasticInfo, and post the output.

**Comment by lcd047** [comment]
That doesn't look like the output from `:SyntasticInfo`.  Also, I don't speak Chinese.

**Comment by Stephen2252Ro** [comment]
Here is the screenshot of .vimrc:

Here is the output from :SyntasticInfo in Vim window, in which I opened a "test.c" file:

No matter I set splint or sparse in .vimtc file, the syntastic cannot work for C file.


Best regards,







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vim-syntastic/syntastic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月20日(星期天) 中午11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vim-syntastic/syntastic] Using sparse in Vim (#2367)





 
That doesn't look like the output from :SyntasticInfo.  Also, I don't speak Chinese.

**Comment by lcd047** [comment]
Whatever you're trying to do isn't working, your screenshots are not getting attached.  Please use copy & paste rather than screenshots, I only need the text anyway.
