### ISSUE TITLE
Erroneous syntax error when destructuring using the star operator (python)

### ISSUE THREAD

**Issue by OmnipotentEntity** [vim-syntastic/syntastic#2377]
In python, it is possible to destructure lists and tuples using the star operator:

```
a, *b = [1, 2, 3, 4]
print(a) # 1
print(b) # [2, 3, 4]
```

However, syntastic thinks that this is invalid syntax.

`demo.py|1 col 4 error| invalid syntax`

**Comment by OmnipotentEntity** [comment]
This is being caused by `python` being python2 on my system.  But I'm targeting python3.  Looking at the compile.py script, I see some effort has been made to bridge some of the 2 vs 3 issues (`from __future__ import print_function` for instance).  Is there a way to instruct syntastic to compile using `python3` instead?

**Comment by lcd047** [comment]
Your easier is often a maintainer's time waster happily ever after.  Syntastic has been blissfully unaware of the Python 2 vs Python 3 mess to this day, please don't try to force it down it's throat now.  Also please refrain from submitting patches for things that can already be achieved without code changes, PRs like that aren't even considered.

Unrelated: please note that syntastic is essentially dead these days.  It has been obsoleted by [ALE][ALE] which takes advantage of Vim 8 features and is actively maintained.

[ALE]: https://github.com/dense-analysis/ale

**Comment by OmnipotentEntity** [comment]
Thank you.  I was unaware that syntastic was in maintenance-only mode.  Again, my objective isn't to annoy or torment you, and I apologize if that was the end result nevertheless.  I will migrate to ALE.  And thank you for taking the time to answer my question.
