### ISSUE TITLE
Allow execution of multiple linters

### ISSUE THREAD

**Issue by spaceone** [vim-syntastic/syntastic#2380]
I configured `let g:syntastic_python_checkers = ['flake8', 'pycodestyle']` (and some others).
When one of the tools reports issues, the other tool is not executed anymore.
I would like that the output of both/all tools is combined.

**Comment by lcd047** [comment]
Please read `:h 'syntastic_aggregate_errors'`.

**Comment by spaceone** [comment]
Great!
