### ISSUE TITLE
stylelint scss: -s option not available anymore in recent stylelint versions

### ISSUE THREAD

**Issue by phloxic** [vim-syntastic/syntastic#2384]
```sh
$stylelint --version
14.0.1
$ stylelint -f json -s scss somefile.scss | head -1
Error: The "syntax" option is no longer available. You should install an appropriate syntax, e.g. postcss-scss, and use the "customSyntax" option
```
It seems to work when I just omit `-s scss`.

**Comment by phloxic** [comment]
FWIW, my stylelintrc is mainly extending [stylelint-config-standard-scss](https://github.com/stylelint-scss/stylelint-config-standard-scss#usage) which is probably one way to replace the commandline option.

**Comment by lcd047** [comment]
Thank you for letting me know, I removed the checkers `less/stylelint` and `scss/stylelint` (commit 2c4b33f6).  There are probably better ways to fix this, but syntastic is dead (you should consider switching to [ALE][ALE]), and I don't have time to attempt to understand what was the point of `-s`, what would be a reasonable replacement for it, and how that would play with syntastic.  Sorry about that.

[ALE]: https://github.com/dense-analysis/ale

**Comment by phloxic** [comment]
@lcd047 - oh, did not realize I was working with a zombie ;-)

I'll look into migrating my habits to ALE then.

FWIW, this https://github.com/stylelint/stylelint/blob/14.0.0/docs/migration-guide/to-14.md sums up the changes for stylelint v14.

Thanks.
