### ISSUE TITLE
autocmd example for finding checker config file doesn't work as is

### ISSUE THREAD

**Issue by numericillustration** [vim-syntastic/syntastic#2387]
in the `My favourite checker needs to load a configuration file from the project's root` section there is a helpful autocmd to find a config file in alternate directories, but doesn't work as is since it prefixes the new variable setting with `b` rather than `g`.

**Comment by lcd047** [comment]
Yes, `b` is intentional, it allows you to have several unrelated projects open at the same time, with different configurations.  Can you please post an example of what doesn't work?
