### ISSUE TITLE
Checkers problem

### ISSUE THREAD

**Issue by mrAibo** [vim-syntastic/syntastic#2391]
Hi all,
I have carefully read the documentation, tried everything, but unfortunately I have not succeeded.
I tried to enable Ansible and Python checkers, but something does not work.
The strange thing is that the sh checker is detected on Shell.
Can anyone tell me what I'm doing wrong?
Here's what I have in .vimrc
```
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_yaml_checkers = ['yamllint']
let g:syntastic_ansible_checkers = ['ansible_lint']
let g:syntastic_sh_checkers = ['shellcheck', 'sh']
let g:syntastic_python_checkers = ['pylint']
```

This is what I get in the yaml or python file when I command :SyntasticInfo

```
Syntastic version: 3.10.0-32 (Vim 801, Linux)
Info for filetype: yaml
Global mode: active
Filetype yaml is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
```

In the *.sh script the command :SyntasticInfo outputs:
```
Syntastic version: 3.10.0-32 (Vim 801, Linux)
Info for filetype: sh
Global mode: active
Filetype sh is active
The current file will be checked automatically
Available checker: sh
Currently enabled checker: sh

```

```
$ which ansible-lint
/usr/bin/ansible-lint
```

Thanks in advance

**Comment by lcd047** [comment]
First please note that syntastic is dead, if you're using Vim 8 or later you should consider switching to [ALE][ALE] instead, which is actively maintained and takes advantage of Vim 8 features.

If you insist to get this working though please add this to your `vimrc`: `let g:syntastic_mode_map = {'mode': 'passive'}`, then open an `ansible` test file, set `g:syntastic_debug` to 3, run `:SyntasticInfo`, and post the output.

[ALE]: https://github.com/dense-analysis/ale

**Comment by lordkage** [comment]
If this project is now unmaintained, it would be great to update the README indicating the lack of support.
