### ISSUE TITLE
How highlight full word (not line) warning or error in code?

### ISSUE THREAD

**Issue by G28XYZ** [vim-syntastic/syntastic#2393]
Hello ! :)
![r8iqopaef1581](https://user-images.githubusercontent.com/49811827/150727034-8ee8e311-580a-4894-a802-b461ed138ed7.png)

https://preview.redd.it/r8iqopaef1581.png?width=2294&format=png&auto=webp&s=e54546460e0face0719f9bef88920f93cbde8a95

Thank you for attention! :)

**Comment by lcd047** [comment]
Please note that syntastic is dead, you might consider switching to [ALE][ALE] instead.  If you still want this feature you'll need to write the relevant [`GetHighlightRegex()`][hl] function.  Depending on the linter you want to change this may be trivial or more involved.

[ALE]: https://github.com/dense-analysis/ale
[hl]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide#gethighlightregexitemcallback

**Comment by G28XYZ** [comment]
Thanks
I'll try to use this function for now. And I can go to ALE at any time.
