### ISSUE TITLE
Multiple error windows opened for the same project.

### ISSUE THREAD

**Issue by RootOperator** [vim-syntastic/syntastic#2397]
When I split a different file from the same project another error window will open above the already existing one.
I'm not sure if this is done intentionally or if there is a way to only allow 1 error list to be opened at a time.

![image](https://user-images.githubusercontent.com/20143055/156168360-940d13d0-3a2a-4a5d-9d89-3075b1a3684e.png)

**Comment by lcd047** [comment]
This is #400 anniversary edition. :smile: Meanwhile syntastic died of Vim 8 related causes, and you should perhaps consider using [ALE][ALE] instead.

[ALE]: https://github.com/dense-analysis/ale

**Comment by RootOperator** [comment]
my bad, did not see that issue.
