### ISSUE TITLE
Syntastic Not finding checker [merlin]

### ISSUE THREAD

**Issue by ac1dbyte** [vim-syntastic/syntastic#2398]
I have this in my .vimrc:
`let g:syntastic_ocaml_checkers = ['merlin']`
But when I use vim on an ocaml file I get this for my SyntasticInfo: 
`Syntastic version: 3.10.0-32 (Vim 800, Neovim, Linux)
Info for filetype: ocaml
Global mode: active
Filetype ocaml is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -`
And error checking (obviously) does not work
When I run `:echo syntastic#util#system('echo "$PATH"')`
I get: 
`/home/[REDACTED]/.opam/default/bin:/home/[REDACTED]/bin:/usr/lib/ccache/bin/:/sbin:/usr/bin:/usr/sbin
:/usr/local/bin:/usr/local/sbin:/opt/bin:/usr/bin/core_perl:/usr/games/bin:/usr/local/bin:/us
r/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/
usr/bin/core_perl`
here is my /home/[REDACTED]/.opam/default/bin: 
`bdump                lambda-term-actions  ocamlbuild.byte     ocamlrpcgen         utop-full
cppo                 menhir               ocamlbuild.native   ocaml-syntax-shims  ydump
netplex-admin        ocamlfind           safe_camlp4
dot-merlin-reader    ocaml                ocamlmerlin         utftrip
dune                 ocamlbuild           ocamlmerlin-server  utop`

**Comment by ac1dbyte** [comment]
here is the syntax checker file, i'm not sure if this is the problem: 
`[~/.local/share/nvim/plugged/syntastic/syntax_checkers/ocaml]
>>> ls
camlp4o.vim`

**Comment by lcd047** [comment]
The `merlin` linter is not part of syntastic, it's provided by the [`merlin`][merlin] plugin.  Please complain there if it doesn't work.  Also syntastic is dead, you might consider  switching to [`ALE`][ALE] instead.

[merlin]: https://github.com/the-lambda-church/merlin
[ALE]: https://github.com/dense-analysis/ale
