### ISSUE TITLE
How can I disable Syntastic active mode if opened read-only (via "view" command)

### ISSUE THREAD

**Issue by househead** [vim-syntastic/syntastic#2405]
I would ideally like to disable syntax checking when a file is opened read-only. Is this possible?

**Comment by lcd047** [comment]
You could try setting an `autocmd`:
```vim
autocmd BufRead * if &readonly | let b:syntastic_mode = 'passive' | endif
```
(not tested).  But this only makes sense for checkers that check a single file.

On a side note: syntastic is dead, you might consider switching to [ALE][ALE] which takes advantage of Vim 8 features and is actively maintained.

[ALE]: https://github.com/dense-analysis/ale

**Comment by househead** [comment]
Thank you, @lcd047 this meets my need well.

I'll have a look at ALE when I get a little more time! All the best.
