### ISSUE TITLE
Pylint comments are not disabling errors

### ISSUE THREAD

**Issue by alac1984** [vim-syntastic/syntastic#2407]
**Expected behavior:**

When I use a comment for disabling a error (i.e: `# pylint: disable=E501`) I expect that this erro would be ignored by pylint.

**What is happening:**

I'm using the comment but the error still being showed by pylint.

**What I'm using**

Ubuntu 22.04
Neovim 0.6.1
Features: +acl +iconv +tui
Complete init.vim: [https://pastebin.pl/view/a422c0e8](https://pastebin.pl/view/a422c0e8)

**Syntastic options used in init.vim:**

```
let g:syntastic_python_pylint_args = '--rcfile=/home/andre/.pylintrc'
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 1
```

**What I've tried**

I read Syntastic manual (`:help syntastic`) but I didn't found any configuration that enables or disables comments.

**Additional info**

I use `poetry` to manage virtual environments, I always activate a venv using `poetry shell` before I open NeoVim instance and, for a reason that I don't quite understand, I have to install `pylint` as a dev-dependency in all my projects, otherwise I do not get its functionality.

**Comment by lcd047** [comment]
Syntastic is dead, you might consider using [ALE][ALE] instead.

But if you insist on debugging this, please open a (preferably minimal) test file illustrating the problem, set `g:syntastic_debug` to 3, run the checker, run `:mes`, and post the output.

[ALE]: https://github.com/dense-analysis/ale
