### ISSUE TITLE
Syntax checkers for Groovy/Grails?

### ISSUE THREAD

**Issue by fmahnke** [vim-syntastic/syntastic#917]
I am doing quite a bit of Grails development lately and hate the IDEs. I will try to start some support on this if there isn't any yet. Any forks with syntax checkers for Groovy/Grails?

**Comment by ejaz-ahmed** [comment]
Checkout this one https://github.com/sighforever/vim-syntastic-java-gradle-plugin

**Comment by Scuilion** [comment]
That looks as though it only supports Java.
